### PR TITLE
Add `continue-in-finally` documentation examples 

### PR DESCRIPTION
**Pull request by mbyrnepr2**
Add `continue-in-finally` documentation examples based on the `pylint-errors` project.

Co-authored-by: Vladyslav Krylasov <vladyslav.krylasov@gmail.com>

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|    | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Partially addresses https://github.com/PyCQA/pylint/issues/5953

### CODE REVIEW

**Review by DanielNoord — APPROVED** [review]

**Review by Pierre-Sassoulas — DISMISSED** [review]

**Comment by mbyrnepr2** [comment]
Something to do with py_version @Pierre-Sassoulas. I copied the pylintrc from the functional tests. Can revisit later today

**Comment by Pierre-Sassoulas** [comment]
We have the same issue in #6583, we probably need to set ``py-version`` because running the documentation test on multiple interpreters would be too much..

**Comment by DanielNoord** [comment]
@mbyrnepr2 Are you still looking to finish this PR or should we close it?

**Comment by mbyrnepr2** [comment]
> @mbyrnepr2 Are you still looking to finish this PR or should we close it?

@DanielNoord sorry about the delay. I'm not sure how I can fix the CI issue. The py-version doesn't affect the test if I remember correctly.

**Comment by DanielNoord** [comment]
It's weird as the CI runs on 3.8. Would bumping to `3.10` help?

**Comment by mbyrnepr2** [comment]
> It's weird as the CI runs on 3.8. Would bumping to `3.10` help?

Not sure I follow - the test needs to run on something older than 3.8 to trigger the `continue-in-finally` message.

**Comment by DanielNoord** [comment]
> Not sure I follow - the test needs to run on something older than 3.8 to trigger the `continue-in-finally` message.

Ah my bad, I mixed up my "older" with "higher number". Would the fix be to fix support for `py-version` for this message? I don't think we should rely on the interpreter to be able to emit certain message and instead handle such differences with that option flag.

**Review by Pierre-Sassoulas — APPROVED** [review]
LGTM ! Thank you for the extra-work on py-version @mbyrnepr2 !

**Pull request merged**
