### PR TITLE
Fix bug if encoding in #coding is 'bad' (not exists)

### PR DESCRIPTION
**Pull request by proggga**
### Fixes / new features
If you make mistake in 
`#coding utf-8`
like:
`#coding utd-8`
Pylint fails without running test
I made simple, it show message on file, but not fail, idk how it should be, pls check it out and fix

### CODE REVIEW

**Comment by proggga** [comment]
Please help, I wanna help, but it not easy when don't know this project as well

**Comment by proggga** [comment]
I found that bug only in 2.7 where if you put module docstring first, and second line is #coding, then pylint crushes, if had write the 'fix' but it not proper, pls help me write test only for 2.7 version

**Comment by rogalski** [comment]
@proggga See *.rc files stored along with (some of) functional tests.

**Comment by proggga** [comment]
Now I completed this fix, for version 2.7 and test for it
Bug is: when in "coding" line written wrong encoding and this line goes after module docstring like:

```
'''Module dosctring'''
 # coding: utX-8
```

**Pull request closed without merging**
