### PR TITLE
Added threading.local to ignored classes default list

### PR DESCRIPTION
**Pull request by jhermann**
### Fixes / new features
- Added "threading.local" to ignored classes default list (as "thread._local" and "_thread._local")

Note that the implementation names for Python 2/3 are used (threading.local is an alias). Also changed related places for consistency.

### CODE REVIEW

**Comment by PCManticore** [comment]
Thank you for the pull request. Can you add these two values here as well https://github.com/PyCQA/pylint/blob/master/pylint/checkers/typecheck.py#L357? By doing this, all instances of thread.local will not be analyzed any longer for no-member errors, which will result in less false positives emitted when working with these objects, as pylint has a hard time understanding when they are modified dynamically.

**Comment by jhermann** [comment]
And I assume that means *all* (four) defaults? That 's the reason I did not find that place, since the existing defaults aren't listed there, either.

**Comment by PCManticore** [comment]
There are only two, no? thread._local and _thread.local. I don't mean SQLObject, that should be decided by the user, but at least for standard library we could offer good defaults.

**Comment by PCManticore** [comment]
3, sorry, including optparse.

**Comment by PCManticore** [comment]
Thank you.

**Pull request merged**
