### PR TITLE
Add regression test for issue #5408

### LINKED ISSUE #5408: pylint endless recursion with short example using setuptools.build_meta import
### Bug description

```python
""" Nuitka python -m build integration """

# This lines triggers the bug
from setuptools.build_meta import anything
```

The bug must be coming due to the module imported, if I change the name, no crash.

### Command used

```python
['/usr/bin/python3', 
'-m', 
'pylint', 
'--init-hook=import sys;sys.setrecursionlimit(1024*sys.getrecursionlimit())', 
'--disable=I0011,I0012,no-init,bad-whitespace,bad-continuation,E1103,W0632,W1504,C0123,C0411,C0413,R0204,similar-code,cyclic-import,duplicate-code,deprecated-module,deprecated-method,deprecated-argument,assignment-from-none,ungrouped-imports,no-else-return,c-extension-no-member,inconsistent-return-statements,raise-missing-from,import-outside-toplevel,useless-object-inheritance,useless-return,assignment-from-no-return,redundant-u-string-prefix,consider-using-f-string', 
'--enable=useless-suppression', 
'--msg-template="{path}:{line} {msg_id} {symbol} {obj} {msg}"', 
'--reports=no', 
'--persistent=no', 
'--method-rgx=[a-z_][a-zA-Z0-9_]{2,40}$', 
'--module-rgx=.*', 
'--function-rgx=.*', 
'--variable-rgx=.*', 
'--argument-rgx=.*', 
'--dummy-variables-rgx=_.*|trace_collection', 
'--ignored-argument-names=_.*|trace_collection', 
'--const-rgx=.*', 
'--max-line-length=125', 
'--no-docstring-rgx=.*', 
'--max-module-lines=5000', 
'--min-public-methods=0', 
'--max-public-methods=100', 
'--max-args=11', 
'--max-parents=13', 
'--max-statements=50', 
'--max-nested-blocks=10', 
'--max-bool-expr=10', 
'--score=no', 
'--rcfile=/dev/null', 
'--notes=', 
'nuitka/distutils/Build.py']
```

See above, I am using the init hook, because I have hit recursion limits in the past and there expanding them was helpful. With my command though it was a segfault, so it's clearly going endless.

### Pylint output

Error, segfault from pylint. It sees if I remove my recursion limit init hook, I am getting this as an infinite trace:

```shell
    yield next(generator)
  File "/home/hayen/.local/lib/python3.7/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/hayen/.local/lib/python3.7/site-packages/astroid/bases.py", line 156, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/home/hayen/.local/lib/python3.7/site-packages/astroid/nodes/node_ng.py", line 170, in infer
    for i, result in enumerate(generator):
  File "/home/hayen/.local/lib/python3.7/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
```

### Expected behavior

Do not crash.

### Pylint version

```shell
pylint==2.12.1
astroid==2.9.0
setuptools 45.3.0 from /usr/local/lib/python3.7/dist-packages (Python 3.7)
```

### OS / Environment

Debian Buster, Github Actions too, I don't think OS related

### Additional dependencies

setuptools 45.3.0 code is what actually triggers it apparently

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Depends on https://github.com/PyCQA/astroid/pull/1392
Closes #5408.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
👌

**Comment by jacobtylerwalls** [comment]
(Don't forget to remove the `diofant` submodule.)

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
(diofant need to be removed)

**Comment by DanielNoord** [comment]
Pff, VS Code is really bad in showing whenever you add a submodule accidentally (or I am just bad at noticing). Changed! Thanks @jacobtylerwalls

**Review by Pierre-Sassoulas — APPROVED** [review]

**Pull request merged**
