### PR TITLE
Update astroid to 2.8.2

### PR DESCRIPTION
**Pull request by cdce8p**
https://github.com/PyCQA/astroid/releases/tag/v2.8.1

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
> If you like, I can take care of updating / merging all requires astroid update PRs afterwards.

I would appreciate that, thanks :smile: !

**Comment by cdce8p** [comment]
Before we merge it, did you plan on releasing astroid `2.8.3` with just the wrapt update or would you like to wait a bit longer?

**Comment by Pierre-Sassoulas** [comment]
I can't right now but that would make sense. I can do that in ~= 6 hours . If you want you can try the release process ;)

**Comment by cdce8p** [comment]
> I can't right now but that would make sense. I can do that in ~= 6 hours . If you want you can try the release process ;)

I'll leave that to you (for now at least) 😅 Just wanted to know if I should wait before merging this one. No need to hurry for the release then. This won't be the last time we update the version before pylint `2.12` anyway.

**Pull request merged**
