### PR TITLE
make default identifier rules closer to naming scope rules

### PR DESCRIPTION
**Pull request by eliasdorneles**
### Default config update
- relax character limit for method and function names that starts with `_`
- relax character limit for variable names

This will let people to use longer names for methods and functions that have a shorter scope (to be considered private), thus not discouraging people to write nice descriptive names.

The same idea applies to variable names, only with an inverse rule (you want long descriptive names for variables with bigger scope, like globals).

Thoughts?

### CODE REVIEW

**Comment by moylop260** [comment]
IMHO the `pylintrc` is just for self-pylint
You should use your own configuration file and run command with: `pylint --rcfile=my_custom_file.cfg`
Or you can create the default one in `~/.pylintrc` and run normal command: `pylint`

**Comment by PCManticore** [comment]
@eliasdorneles This makes sense, but as @moylop260 said, this file is used only for pylinting pylint on our CI. If you want to modify these values, you have to go to their source, check where the options are defined inside the checkers/ directory.

Also, some tests with these defaults would be nice to have.

**Comment by eliasdorneles** [comment]
Oh right, thanks for reviewing, lemme redo it! :+1:

**Comment by eliasdorneles** [comment]
Updated!
Does it look good now?
Thanks!

**Comment by PCManticore** [comment]
Amazing! Could you also do two more things? First of all, you can add yourself to CONTRIBUTORS. Secondly, this change would need a changelog entry (which can be pretty short) and a What's New entry, for which you can use the description you put into this issue. The what's new docs are in doc/whatsnew/2.0.rst.

Thank you. ;-)

**Comment by eliasdorneles** [comment]
Done! :+1:

**Comment by PCManticore** [comment]
Merged locally, https://github.com/PyCQA/pylint/commit/0a19131d0757781891fc076697790c21d5d9db75. Thank you!

**Pull request closed without merging**
