### PR TITLE
Remove six package from install_requires

### PR DESCRIPTION
**Pull request by sushobhit27**
### Fixes / new features
-

### CODE REVIEW

**Comment by PCManticore** [comment]
@sushobhit27 there's something weird with this PR as it seems to remove stuff that already was removed in #2151

**Comment by sushobhit27** [comment]
@PCManticore can you give example, so that I can look further into it.

**Comment by PCManticore** [comment]
Yes, for instance for `reporters/__init__.py` both PRs show that they remove the `encode` function.

**Comment by sushobhit27** [comment]
@PCManticore ohh I guess PR #2152 is also taking all files/ commits from #2151 into account, as #2151 had 17 changed files and #2152 has 4 changed files but 2152 is showing 21 changed files.

**Pull request merged**
