### PR TITLE
Run PyPy 3.8 and 3.9 in CI

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

Blocked by https://github.com/PyCQA/astroid/pull/1520.

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Should we move that to 2.15 ?

**Comment by DanielNoord** [comment]
Yes!

**Comment by cdce8p** [comment]
Unfortunately, there is still one failing test even with the latest astroid changes.

```
__________________ test_functional[unspecified_encoding_py38] __________________

self = <pylint.testutils.lint_module_test.LintModuleTest object at 0x000000000bbc6aa0>

    def runTest(self) -> None:
>       self._runTest()
E       AssertionError: Wrong results for file "unspecified_encoding_py38":
E       
E       Expected in testdata:
E         13: unspecified-encoding
E         14: unspecified-encoding
E         15: unspecified-encoding
E         16: unspecified-encoding
E         17: unspecified-encoding
E         26: unspecified-encoding
E         29: unspecified-encoding
E         33: unspecified-encoding
E         38: unspecified-encoding
E         39: unspecified-encoding
E         40: unspecified-encoding
E         41: unspecified-encoding
E         50: unspecified-encoding
E         53: unspecified-encoding
E         57: unspecified-encoding
E        149: unspecified-encoding
E        161: bad-open-mode
E        161: unspecified-encoding
E        164: bad-open-mode
E        164: unspecified-encoding
E 
```

**Comment by DanielNoord** [comment]
The open issue is due to `astroid` on ``PyPy`` failing the following test:

```python
def test_open_pypy() -> None:
    """Regression test for inference of open() call.

    Previously we failed to infer this on PyPy.
    """
    node: nodes.Call = builder.extract_node("""open("foo.py", "w", encoding="utf-8")""")
    inferred = node.func.inferred()
    assert len(inferred) == 1
    assert isinstance(inferred[0], nodes.FunctionDef)
    assert inferred[0].name == "open"
```

I think this is due to how `builtins` are defined but I am by no means a `PyPy` expert..

**Comment by DanielNoord** [comment]
I have published a fix for the inference of `open` to `astroid`. Apparently this was a very old issue, which now finally has a solution :)

**Comment by DanielNoord** [comment]
Actually was able to run on `3.9` as well with some minor changes 😄

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Gentle ping, I feel you might have missed this. Never mind if you just haven't gotten to it!

**Review by Pierre-Sassoulas — APPROVED** [review]
Thank you for the reminder, I did miss it :) Looks great !

**Comment by cdce8p** [comment]
Thanks for working on this @DanielNoord! Saw you added PyPy 3.9 already. AFAIK we do have one more issue with it in astroid. Last I checked it was something with detecting the `builtins` module. Not sure if that has already been fixed in the mean time.

**Comment by DanielNoord** [comment]
> Thanks for working on this @DanielNoord! Saw you added PyPy 3.9 already. AFAIK we do have one more issue with it in astroid. Last I checked it was something with detecting the `builtins` module. Not sure if that has already been fixed in the mean time.

I don't think so, but with my new experience with `builtins` and `io` I might be able to tackle it! I'll try and have a look at some point.

**Pull request merged**
