### PR TITLE
Backport (#7987)

### PR DESCRIPTION
**Pull request by clavedeluna**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Manual backport from this PR https://github.com/PyCQA/pylint/pull/7987

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
The pre-commit error seems genuine but also it seems it might be pre-existing ?

**Comment by clavedeluna** [comment]
I believe I've cherry-picked the right commit to fix the issue.

**Comment by Pierre-Sassoulas** [comment]
The problem with pre-commit will be fixed with https://github.com/DanielNoord/pydocstringformatter/pull/214

**Comment by DanielNoord** [comment]
I don't really understand. This issue should have been fixed in a release that was already released and is being used by `pre-commit`. I'm rerunning the CI.

**Comment by DanielNoord** [comment]
Ah, we need to cherry pick the `pre-commit` config as well. The maintenance branch is using `0.7.0` which is indeed broken.

**Comment by clavedeluna** [comment]
@DanielNoord ok since you know a bit more about what's going on, I'll let you handle any removal of commits here or anything like that.

**Comment by DanielNoord** [comment]
@clavedeluna You can just copy the `.pre-commit-config.yaml` from `main` to this PR. That should fix it 😄

**Comment by Pierre-Sassoulas** [comment]
I've done it but this is not that simple. I think we should release astroid 2.13.0 and pylint 2.16.0. Cherry-picking is not working automatically half the time right now, cherry-picking all the pre-commit upgrade is going to be a lot of work.

**Comment by clavedeluna** [comment]
Since this is causing so much trouble, I have to ask something that's been on my mind for a few weeks. Is the backporting procedure an absolute necessity for pylint? Could the repo not benefit from always forward-looking release of code? Or what is the great benefit of backporting certain PRs to an already-released minor version? I guess it's to avoid having to tell people to upgrade?

**Comment by Pierre-Sassoulas** [comment]
We were doing the "simple version" without cherry-picking at some point, but it means we can't release some time, or we can't merge enhancement some of the time, or we introduce new bugs with each version, or we do not follow semver... Right now the problem we have is that 1189 in astroid is stuck and we did not release for a long time with a lot of change on the main branch since. I'm very close to merging 1189 now and dealing with small comments later.

**Review by Pierre-Sassoulas — APPROVED** [review]

**Pull request merged**
