### PR TITLE
Add missing checks for deprecated functions

### PR DESCRIPTION
**Pull request by federicobond**
## Description

This PR removes some checks for deprecated functions that have been removed since Python 3.5 (Pylint's oldest supported version) and add some missing checks for functions that have been deprecated since.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
I don't understand this pull request that well. What is the disadvantage of keeping the check for deprecated function removed after python 3.5 ? Also what if someone want to launch pylint using python 3.6 to analyses the code of a python 2.6 codebase?

**Comment by federicobond** [comment]
I had not considered that use case to be honest. Not sure anybody uses pylint in that way but I could keep the checks in that case.

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by hippo91** [comment]
@federicobond  @Pierre-Sassoulas what is the status of this PR?
I saw that it was approved but given @Pierre-Sassoulas 's last comment, i don't know what to think about it.

**Comment by federicobond** [comment]
Not sure either, should I re-add the 2.6.0 deprecation checks?

**Comment by Pierre-Sassoulas** [comment]
Hello, sorry, I approved when I should have "requested a change" :) Let's put back the deprecation check for 2.6 code.

**Comment by federicobond** [comment]
@Pierre-Sassoulas @hippo91  done!

**Comment by Pierre-Sassoulas** [comment]
Merged ! Thank you for this :)

**Comment by hippo91** [comment]
@federicobond and @Pierre-Sassoulas many thanks!

**Pull request merged**
