### PR TITLE
empty-comment line number bug fix

### LINKED ISSUE #4009: Wrong line number for empty-comment message
### Steps to reproduce
1. create a file with empty comment, for instance:

```
""" test"""
#
```

2. run Pylint with the empty-comment extension  #3870

    for example in command line with a file named `temp.py`:

`pylint --load-plugins=pylint.extensions.empty_comment temp.py`

3. Watch Pylint output in the console.

### Current behavior
You get the following message output:
`temp.py:1:0: R2044: Line with empty comment (empty-comment)`

with line number `1`.

### Expected behavior
You would expect line number `2`, i.e with output:
`temp.py:2:0: R2044: Line with empty comment (empty-comment)`

### pylint --version output
pylint 2.6.1-dev1
astroid 2.5.0
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]

running on Windows 10 64-bit

### PR DESCRIPTION
**Pull request by orSolocate**
## Steps

- [X] Add yourself to CONTRIBUTORS if you are a new contributor.
- [X] Add a ChangeLog entry describing what your PR does.
- [X] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [X] Write a good description on what the PR does.

## Description
Fixed empty-comment wrong line number in its message. Was 1 line behind the actual line number.
Fixed implementation and unittest.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
|   | :sparkles: New feature |
|   | :hammer: Refactoring  |
|   | :scroll: Docs |

## Related Issue
#4009

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Thank you for this fix, it seems pretty straightforward. Could you just add a functional test in `tests/functional/e/empty_comment.py`, please ?

**Review by Pierre-Sassoulas — APPROVED** [review]
Hmm, sorry, what I asked for is impossible as functional test need non empty comments to work.

**Comment by Pierre-Sassoulas** [comment]
I merged it, your change will be available when we release `2.6.1` or `2.7.0` (soon!) :) ! Congrats on becoming a pylint's contributor  !

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  Thanks for accepting it. Hopefully more contributions will follow :)

**Pull request merged**
