### PR TITLE
Documentation fixes

### LINKED ISSUE #3747: Documentation: Custom Regular Expressions example actually matches snake_case and UPPERCASE, not snake_case and camelCase
I apologize if this is not the correct place to report errors in the documentation. I could not locate any specific places to file such issues.

### Current behavior
The [User Guide options documentation page](http://pylint.pycqa.org/en/latest/user_guide/options.html#custom-regular-expressions) provides example regex for if the user wanted to support both snake_case and camelCase function names. The provided regex, `(?:(?P<snake>[a-z_]+)|(?P<camel>_?[A-Z]+))$`, actually matches both snake_case and UPPERCASE name formats, not camelCase.

image

### Expected behavior
I would expect the regex to actually match both snake_case and camelCase rather than snake_case and UPPERCASE. I personally use the following regex to do so: `(?:(?P<snake>[a-z_]+)|(?P<camel>_?(?:[a-z]+[A-Z]*)+))` but I doubt this is the optimal regex to use.

### pylint --version output
N/A

### LINKED ISSUE #4541: Documenting ignore-paths in example pylintrc
### Is your feature request related to a problem? Please describe

I refer to https://github.com/PyCQA/pylint/blob/master/examples/pylintrc for information on configuring pylint.  Though technically I configure pylint via `pyproject.toml`.

In https://github.com/PyCQA/pylint/pull/4516 the `ignore-paths` config directive was added.  Can we please add this to the [example `pylintrc`](https://github.com/PyCQA/pylint/blob/master/examples/pylintrc)?

### Describe the solution you'd like

Just a brief entry in `pylintrc` similar to the others.

### PR DESCRIPTION
**Pull request by DudeNr33**
## Steps

- [x] Write a good description on what the PR does.

## Description
A few minor documentation fixes:

- Fix regular expression for camelCase naming style example (#3747)
- Add ``ignore-paths`` to example pylintrc
- Change verbatim name of ``ConfusingConsecutiveElifChecker`` to ``confusing_elif`` so that it does not appear as "Confusing Elif Checker Checker" anymore
- Fix some improperly indented bullet points in ``ChangeLog`` so building the docs works again.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Related Issue

Closes #3747
Closes #4541

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
Thank you for the cleanup :) !

**Comment by Pierre-Sassoulas** [comment]
Regarding the issue with the changelog, do you think it would be possible for the check to fail if the format is'nt valid ? Maybe we could change the name so it's clear it's .rst formatting and prettier would check it automatically ?

**Comment by DudeNr33** [comment]
I will have a look how this could be checked, haven't done this for .rst files before. Time to learn something new!

**Comment by Pierre-Sassoulas** [comment]
I'm merging so the fix is in 2.9.0 :) Checking automatically is a bonus, we can do it in another MR. Thank you again for handling this !

**Comment by DudeNr33** [comment]
No problem, I'll open a new one.
I'm already testing my changes for the automatic check - I put it into ``script/fix_documentation.py`` at the moment, because this is already used as a pre-commit hook to fix .rst files.
The new check however only outputs the errors and warnings, but can't fix them. But I think having it all in one place is better than being pedantic about the naming.

**Comment by Pierre-Sassoulas** [comment]
This is the perfect place for this 👍

**Pull request merged**
