### PR TITLE
Docstr comment

### LINKED ISSUE #3786: Spell-checker crashes if a regex('^ +#') line in a docstring contains a typo
### Steps to reproduce
1.  `pip install pyenchant`
2.  Create the file `test.py` with contents
    ```python
    def foo():
        """
        # tpyo
        """
    ```
3.  `pylint --disable all --enable spelling --spelling-dict en_US test.py`

### Current behavior
```
Traceback (most recent call last):
  File "/home/ganden/.pyenv/versions/jlab-test/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/lint/run.py", line 349, in __init__
    linter.check(args)
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 862, in check
    self._check_files(
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 896, in _check_files
    self._check_file(get_ast, check_astroid_module, name, filepath, modname)
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 922, in _check_file
    check_astroid_module(ast_node)
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1054, in check_astroid_module
    retval = self._check_astroid_module(
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1099, in _check_astroid_module
    walker.walk(ast_node)
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    self.walk(child)
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/checkers/spelling.py", line 397, in visit_functiondef
    self._check_docstring(node)
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/checkers/spelling.py", line 411, in _check_docstring
    self._check_spelling("wrong-spelling-in-docstring", line, start_line + idx)
  File "/home/ganden/.pyenv/versions/3.8.3/envs/jlab-test/lib/python3.8/site-packages/pylint/checkers/spelling.py", line 347, in _check_spelling
    col = line_segment.index(word)
ValueError: substring not found
```

### Expected behavior
Find `tpyo` correctly.

### pylint --version output
```
pylint 2.6.0
astroid 2.4.2
Python 3.8.3 (default, Jul 24 2020, 19:51:30)
[GCC 10.1.0]
# and also
pyenchant 3.1.1
enchant 2.2.8
nuspell 3.1.2
```

### More info

The following do not crash pylint (they behave as expected):

```python
def foo():
    """# tpyo"""
```

```python
"""# tpyo"""
```

```python
def foo():
    """
# tpyo
    """
```

```python
def foo():
    """
    # cat
    """
```

```python
def foo():
    """
    tpyo # cat
    """
```

```python
def foo():
    """
    cat # tpyo
    """
```

### PR DESCRIPTION
**Pull request by gschaffner**
## Steps

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description

Fix spell-checker crash on indented docstring lines that look like `# comments`. See #3786 for more info.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

## Related Issue

Closes #3786

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Hello, thank you for the PR. The examples you gave in #3786 seems good candidates for a functional test, you can add them in `tests/functional/`. Also, I don't know what kind of work would be involved or if I understood what was done correctly, but would it be possible to fix the "docstring" msgid treatment instead of skipping it?

**Comment by gschaffner** [comment]
Hi, thanks for the reply! I do not understand `tests/functional` very well, and I cannot seem to find any functional tests of the spell checker. Would https://github.com/PyCQA/pylint/blob/3e7e3ca443b9355cbc13467d9c3b8fa794647410/tests/checkers/unittest_spelling.py be a better place to add such tests? Something like https://github.com/PyCQA/pylint/blob/3e7e3ca443b9355cbc13467d9c3b8fa794647410/tests/checkers/unittest_spelling.py#L175-L191

Also, I may be misunderstanding you but I don't _think_ that my change skips any treatment. A line of a docstring that looks like a comment should not have its leading `#` trimmed off as if it was a comment. To the interpreter, such a line isn't a comment—it's part of a string.

**Comment by Pierre-Sassoulas** [comment]
No problem ! Yes adding unit test would be a plus too :)

For functional tests, you can add your example like what was done [in this merge request](https://github.com/PyCQA/pylint/pull/3076/files) in `tests/functional/l/line_too_long.py ` and `tests/functional/l/line_too_long.txt `. You can create both files with the name you want or use another pre-existing file, it have to be inside "tests/functional/" and have a .py and a .txt with the same basename.

**Comment by gschaffner** [comment]
It seems to me that this needs to be covered by unit tests rather than functional tests. I believe there aren't currently any functional tests of the spell checker because (AFAIK)
* There is not a way to set `--spelling-dict en_US` for functional tests. Pylint won't report spelling issues if spelling-dict is not set.
* There is not a way to handle multiline pylint errors (like `wrong-spelling-in-docstring`) in `tests/functional/f/foo.txt`.

**Comment by Pierre-Sassoulas** [comment]
Ho, ok, I did not use spell checking much. It makes sense to just use unit test then.

**Review by Pierre-Sassoulas — APPROVED** [review]
This seems ready for merging, thank you. @gschaffner, could you rebase on the latest master to fix the conflicts, please ?

**Comment by gschaffner** [comment]
Done! @Pierre-Sassoulas

**Pull request merged**
