### PR TITLE
[Readme] Add information on how to launch tests fast

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Description

One of the major pain point of developing pylint
for me was the 30s to launch even a single test
with tox and then not have coverage, so I think
this doc will be helpful for future contributors.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :scroll: Docs |

### CODE REVIEW

**Comment by mattlbeck** [comment]
It might be good to recommend cloning the astroid repo and installing it from master when running with pytest because the astroid dep not being cutting-edge up-to-date caused me considerable confusion at first.

**Comment by Pierre-Sassoulas** [comment]
@mattlbeck right, I had to open #3022 myself. I didn't know if cloning astroid was the best way to fix though. Seems like it is :).

**Comment by gyermolenko** [comment]
+1 to show how to run single test module
Wouldn't it be nice to make some sections of readme same as in `/doc/development_guide/contribute.rst` ? (include parts of the document etc)

**Comment by Pierre-Sassoulas** [comment]
@gyermolenko I don't have a strong opinion about it, but we should do it in another merge request.

**Pull request merged**
