### PR TITLE
Extend SphinxDocstring class to support Epytext comments

### LINKED ISSUE #1029: Support epytext in check_docs
Could you please support epytext in check_docs extension?
Epytext comments are basically sphinx comments with one character changed. Instead of `:param name:`, you write `@param name:`.
It's used in PyCharm. Links:
https://www.jetbrains.com/help/pycharm/2016.1/using-docstrings-to-specify-types.html#d386378e169
https://www.jetbrains.com/help/pycharm/2016.1/creating-documentation-comments.html#d848203e314
Thank you.

### PR DESCRIPTION
**Pull request by balta2ar**
The difference is very small, I'm not sure whether I should have created a new class for that. Also, I didn't touch tests, if there are any.

fix #1029

### CODE REVIEW

**Comment by moylop260** [comment]
IMHO is better create your own class inheriting from similar one.

You are modifying one class that is reused in other classes of docstring and this should give us result unexpected.

You could use the init method to overwrite just the variable needed.

By example, I saw that epytext support
`@param `
But I don't saw that epytext support
`:param`
Same case for sphinx.

Then you could start to split your class.

But you should wait the amswer from maintainers

**Comment by AWhetter** [comment]
Hey @balta2ar This looks very promising! @moylop260 is right. Please create a new class.

**Comment by balta2ar** [comment]
@AWhetter Please review.

**Comment by AWhetter** [comment]
This is looking much better! I do have another point. You've had to copy quite a lot of regex from `SphinxDocstring` into the new class. Please could you keep the raw regex strings on `SphinxDocstring` and edit them slightly in the `EpytextDocstring` class (similarly to how `NumpyDocstring` uses `re_container_type` from `GoogleDocstring`).

Something like:
```python
class SphinxDocstring(Docstring):
    re_param = r"""
        :param            # Sphinx keyword
    ...
    """.format(re_type)
    re_param_in_docstring = re.compile(re_param, re.X ...)

class EpytextDocstring(SphinxDocstring):
    re_param_in_docstring = re.compile(
        SphinxDocstring.re_param.replace(':', '@', 1),
        re.X ...)
```

**Comment by balta2ar** [comment]
@AWhetter I left `re_rtype_in_docstring` and `re_returns_in_docstring` as is because the first one differs not only in semicolon (it adds `returntype`), and the second one is rather short.

**Comment by AWhetter** [comment]
It definitely made sense to keep those. Thank you for your contribution!

**Pull request closed without merging**
