### PR TITLE
Add regression test for #5770

### LINKED ISSUE #5770: AstroidSyntaxError when parsing NewType
[pylint-crash-2022-02-04-15.txt](https://github.com/PyCQA/pylint/files/8004129/pylint-crash-2022-02-04-15.txt)

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #5770
Refs https://github.com/PyCQA/astroid/pull/1400

### CODE REVIEW

**Review by DanielNoord — APPROVED** [review]

**Comment by jacobtylerwalls** [comment]
Hold on -- I have to change the variable name back to `t`! (Why?) I changed it to avoid a disable.

**Comment by jacobtylerwalls** [comment]
Had to enable an extension. Better to leave it here or with the tests for this extension?

**Comment by DanielNoord** [comment]
Better to test there I think. The crash probably also occurs in the extension?

**Comment by jacobtylerwalls** [comment]
> The crash probably also occurs in the extension?

The crash _only_ occurs with the extension. I didn't notice because pylint's own `pylintrc` enables it.

> Better to test there I think. 

Sorry, just to check: you're saying move to `tests/functional/ext/redefined_variable_type`?

**Comment by DanielNoord** [comment]
> The crash _only_ occurs with the extension. I didn't notice because pylint's own `pylintrc` enables it.

Ah yeah, that's what I meant.. English 😓 

> Sorry, just to check: you're saying move to `tests/functional/ext/redefined_variable_type`?

Yes 👍

**Review by DanielNoord — APPROVED** [review]

**Pull request merged**
