### PR TITLE
Pin pytest to resolve issue with pytest-benchmark

### PR DESCRIPTION
**Pull request by cdce8p**
## Description
Fix issue with pytest `v7.2.0` and `pytest-benchmark` discovered in #7671
Ref: https://github.com/ionelmc/pytest-benchmark/issues/226

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by cdce8p** [comment]
Seems like we shouldn't use auto-merge 🤔
It merged the PR before the Windows tests were run.

**Comment by cdce8p** [comment]
> > Seems like we shouldn't use auto-merge
> 
> Right, I forgot. We could add more required tests but it can be annoying when we want to merge fast.

I've added `run / 3.11 / Linux` and `run / 3.11 / Windows`. That way we know that at least `some` things are working before an auto-merge.

**Comment by Pierre-Sassoulas** [comment]
>  run / 3.11 / Windows

The problem was that this is one of the slower tests (only primer is longer). Ho well, we're just going to wait a little longer before merging typo-MR 🤷

**Comment by Pierre-Sassoulas** [comment]
Beside we'll be able to enable auto-merge which was the point. Now that I think about it we could add primers and always be able to use auto-merge ?

**Comment by cdce8p** [comment]
> Beside we'll be able to enable auto-merge which was the point. Now that I think about it we could add primers and always be able to use auto-merge ?

The primer tests will / should never fail. I don't think that will work as intended. Even if it's a bit more work, doing the merge manual is the best option for us I think.

**Comment by Pierre-Sassoulas** [comment]
The issue with required job like this is that for documentation merge request where we don't want to run all the tests we can't merge them if tests are required.

**Comment by cdce8p** [comment]
We could always modify the branch protection rules and remove the `Do not allow bypassing the above settings` option. Something I would recommend anyway as it's limited to admins and even we would need to click a checkbox before we can merge something without all checks.

**Comment by Pierre-Sassoulas** [comment]
Agreed and done !

**Pull request merged**
