### PR TITLE
Use codecov instead of coveralls for coverage reporting

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Write a good description on what the PR does.
- [x] Create a news fragment with `towncrier create <IssueNumber>.<type>` which will be
  included in the changelog. `<type>` can be one of: breaking, user_action, feature,
  new_check, removed_check, extension, false_positive, false_negative, bugfix, other, internal.
  If necessary you can write details or offer examples on how the new change is supposed to work.
- [x] If you used multiple emails or multiple names when contributing, add your mails
      and preferred name in ``script/.contributors_aliases.json``

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Closes https://github.com/PyCQA/pylint/issues/6935

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
Very nice 👍 ! I don't know anything about codecov so this might be a lot of work or even impossible, but maybe it's possible to merge test's and primer's coverage ? It was impossible to do with coveralls.

**Comment by DanielNoord** [comment]
> Very nice +1 ! I don't know anything about codecov so this might be a lot of work or even impossible, but maybe it's possible to merge test's and primer's coverage ? It was impossible to do with coveralls.

That is certainly possible, although we don't record coverage currently when running the primer. That would probably slow it down significantly, so I'm not sure how useful that would be.
We could start collecting coverage for PyPY and Windows though. That would be nice I guess as that would be the only way to ever reach 100% :smile:

**Comment by Pierre-Sassoulas** [comment]
Yeah you're right, forget about primers, windows pypy  and lower/upper python interpreter makes a lot more sense

**Comment by Pierre-Sassoulas** [comment]
This looks amazing by the way, I'm already like "What is this red little square there 😠 ??!"

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by DanielNoord** [comment]
Yeah I much prefer both the comment and the site of `codecov`. I'm going to (auto-)merge and then let `codecov` do one of the open PRs to make sure the settings are correct.

**Pull request merged**
