### PR TITLE
Fix false positive for `while-used`

### LINKED ISSUE #7748: `while_used` checker shouldn't report `while True`
### Current problem

Currently, the `while_used` checker reports `while-used` for a `while True` loop:
```py
from time import sleep

while True:
    sleep(1)
```
```
main.py:3:0: W0149: Used `while` loop (while-used)
```
The documentation says:
> Unbounded while loops can often be rewritten as bounded for loops.

Which is untrue for `while True` loops.
It is possible with an infinite generator, but `while True` makes much more sense.

### Desired solution

The `while_used` checker should not report an error for a `while True` loop.

### Additional context

`pylint --version` output:
```
pytpylint 2.15.5
astroid 2.12.12
Python 3.8.12
[GCC 10.3.0]
```

### PR DESCRIPTION
**Pull request by GideonBear**
The `while_used` checker now no longer reports `while-used` when the condition of the while loop is a constant

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Refs #XXXX

Closes #7748

### CODE REVIEW

**Review by jacobtylerwalls — CHANGES_REQUESTED** [review]
Thanks for the quick PR, but as I mentioned on the issue I'd like to invite some more discussion first.

**Comment by GideonBear** [comment]
Primer / Run / Run / 3.7: `git.exc.NoSuchPathError: /home/runner/work/pylint/pylint/tests/.pylint_primer_tests/PyCQA/astroid`
Is this normal?

**Comment by jacobtylerwalls** [comment]
> Primer / Run / Run / 3.7: git.exc.NoSuchPathError: /home/runner/work/pylint/pylint/tests/.pylint_primer_tests/PyCQA/astroid
Is this normal?

Been like that for a couple days after #7717. We're aware of the issue. Haven't found time to debug it yet. I lack some context around how the PR job is supposed to share a cache with the main job; others might know more.

**Review by nickdrozd — APPROVED** [review]
I would describe this as a new feature rather than a bug fix, but other that it looks good :laughing:

**Comment by Pierre-Sassoulas** [comment]
Closing following vote on : https://github.com/PyCQA/pylint/issues/7748#issuecomment-1312576854

**Pull request closed without merging**
