### PR TITLE
Fixed bug that showed uncalled function with decorator as unused added corresponding test case in tests/functional/d/decorator_unused*

### LINKED ISSUE #4254: False positive: decorated "unused" function
### Steps to reproduce

Given a file `a.py`:
```python
# pylint: disable=C
def foo():
    _dispatch = {}

    def save(fn):
        _dispatch[fn.__name__] = fn
        return fn

    @save
    def bar():
        ...
    # do whatever
foo()
```

### Current behavior

```
/tmp/a.py:10:4: W0612: Unused variable 'bar' (unused-variable)
```

### Expected behavior

No warning.

### pylint --version output

Result of `pylint --version` output:
```
pylint 2.7.2
astroid 2.5.1
Python 3.9.1+ (default, Feb  5 2021, 13:46:56) 
[GCC 10.2.1 20210110]
```

### PR DESCRIPTION
**Pull request by elizabethbott**
## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [ ] Write a good description on what the PR does.

## Description
Previously gave false positive unused variable warnings for decorated functions.
Patch passes all Pylint test cases.

Given the code below (this is also found in tests/functional/d/decorator_unused.py):
```
# pylint: disable=C
def foo():
    _dispatch = {}

    def save(fn):
        _dispatch[fn.__name__] = fn
        return fn

    @save
    def bar():
        ...
    # do whatever
foo()
```

Previously outputted:
```/tmp/a.py:10:4: W0612: Unused variable 'bar' (unused-variable)```

Now outputs:
No warning

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue
Closes #4254

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Thank you for fixing this :) Could you remove the classes.dot file, the .DS_Store files and the comment `# changed code`, please ? You can do:
```
git reset (hash of first commit before your change)
git add . -p
git commit -am "New message"
```

**Comment by Pierre-Sassoulas** [comment]
Thank you, but I think it did not work as the current merge request would still add some unwanted Mac specific files. Maybe you need to pull before the reset and then force push the corrected commit ?

**Comment by elizabethbott** [comment]
Was unable to resolve, see pull request #4373 from @haasea. We are working together, and we think his pull request does not contain these extra files. Thank you for help!

**Comment by Pierre-Sassoulas** [comment]
Closed in favor of #4373

**Pull request closed without merging**
