### PR TITLE
Pass ``msg_store`` and ``node`` to ``FileState``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Write a good description on what the PR does.
- [x] If you used multiple emails or multiple names when contributing, add your mails
   and preferred name in ``script/.contributors_aliases.json``

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |

## Description

Base change required for https://github.com/PyCQA/pylint/pull/6556.
Let's also make `modname` required. It's a bit strange that we create a `FileState` before even encountering a file in the `__init__`, but refactoring that is not part of my plan for now.

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
It looks like it broke the config functional tests (report not generated anymore ?). I agree with the refactoring and deprecation in general. 

(I think ``self.file_state = FileState("BaseState", self.msgs_store)`` might be defined before we needs it so it's not Optional and so it's defined in the ``__init__`` ? I agree it's strange to do it like this.)

**Comment by DanielNoord** [comment]
> It looks like it broke the config functional tests (report not generated anymore ?). I agree with the refactoring and deprecation in general.
> 
> (I think `self.file_state = FileState("BaseState", self.msgs_store)` might be defined before we needs it so it's not Optional and so it's defined in the `__init__` ? I agree it's strange to do it like this.)

I don't really know why this breaks 😓 

I think it has something to do with the mocking we do in the tests. For some reason not passing `self.msgs_store` in `self.file_state = FileState("BaseState", self.msgs_store)` fixes it. That doesn't seem like it should actually break but is more indicative of inter-test dependency.

**Comment by DanielNoord** [comment]
Finally pass all tests on all platforms 🎉

**Review by Pierre-Sassoulas — APPROVED** [review]
👍

**Pull request merged**
