### PR TITLE
Updated mypy checks

### PR DESCRIPTION
**Pull request by cdce8p**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description
https://github.com/PyCQA/pylint/pull/4887#discussion_r693329085 mentioned that `platformdirs` is now fully typed.

To be able to remove the import ignore from `setup.cfg`, we would need to add `platformdirs` as an additional dependency in `.pre-commit-config.yaml`. Long term it might be better to just run mypy in the local environment instead.

If the PR is accepted, I'll update `astroid` as well.

### CODE REVIEW

**Comment by cdce8p** [comment]
I've rebased the PR onto #4890

**Comment by cdce8p** [comment]
Seems like pre-commit.ci needs to be updated as well.

**Comment by Pierre-Sassoulas** [comment]
I like the isolation that pre-commit does.  This permit to not have to handle the mypy environnement ourselves 'locally or in github action) and will reduce problem as pre-commit configuration is the source of truth and there would be no human intervention. We can add something in ``additional_dependencies: ["types-pkg_resources==0.1.3", "types-toml==0.1.3"]`` or we could even use the mypy option to auto-install missing stubs.

**Comment by cdce8p** [comment]
> I like the isolation that pre-commit does. This permit to not have to handle the mypy environnement ourselves 'locally or in github action) and will reduce problem as pre-commit configuration is the source of truth and there would be no human intervention.

We already have all additional typing dependencies in `requirement_test.txt` as they are necessary for local runs.

> We can add something in `additional_dependencies: ["types-pkg_resources==0.1.3", "types-toml==0.1.3"]` or we could even use the mypy option to auto-install missing stubs.

That's the way we do it at the moment. One more won't make a difference, but I think in the future we might want to reuse the local environment as it's easier to deal with.

**Comment by cdce8p** [comment]
@Pierre-Sassoulas I updated the PR to only add `platformdirs` as additional dependency. Might be best to squash merge this one.

**Review by Pierre-Sassoulas — APPROVED** [review]

**Pull request merged**
