### PR TITLE
[IMP] Enable profiling report

### PR DESCRIPTION
**Pull request by moylop260**
### Fixes / new features
- Show a report to detect expensive checks
screen shot 2016-05-23 at 7 01 25 pm

This is useful when you create a refactory and need have a reference of performance improvement

### CODE REVIEW

**Comment by PCManticore** [comment]
I'm sorry, but I don't see the usefulness of this. If we want to look into performance, it should be something more granular and readable, with proper time regressions and whatnot, things that a cprofile don't provide for now. I feel it clutters the already cluttered output of the CI, without providing real value.

**Comment by moylop260** [comment]
@PCManticore 
Ok thank for reply

IMHO The first step is detect a global spent time, by example `checkers/python3.py` and `checker/variables.py` are the top of spent time.

And `similar.py`, `format.py`, `exceptions.py` have a times executed very high.

Next step is a granular and readable report just of top files (not all), this should be provided by [line profiler](https://github.com/rkern/line_profiler)

The ideal case is have a github statuses like as `coverage & coveralls`, but that is the last step.
For now, we can live with read the output and detect if a change of performance is better than other one and detect that method need help to increase the performance.

What do you think?

NOTE: My idea don't is a large conversation then your last answer will be the conclusion of this thread.
Thanks again for reply.

**Comment by PCManticore** [comment]
The thing is that this doesn't provide the details we need in order to detect the bottlenecks. Most of the performance critical code is coming anyway from astroid, from the inference, rather than the checkers themselves. If we want to spend time into improving the performance, this must be done at the cause root. Also, take in account that I don't necessarily have a performant astroid in my plans for now, because we're actually planning to improve its capabilities, which will incur more hits to the performance.

**Comment by moylop260** [comment]
I got it
Thanks for reply

**Pull request closed without merging**
