### PR TITLE
Dockerfile: add alpine-based docker image

### PR DESCRIPTION
**Pull request by 7AC**

### CODE REVIEW

**Comment by hippo91** [comment]
@7AC thanks for this PR. What is the reason you made it? Can you explain a bit please?

**Comment by 7AC** [comment]
We have use docker in our CI infra and use it to run the various tools that are part of it. It's a pretty standard way of using Jenkins and other systems. We use pylint to lint all our python code.

**Comment by hippo91** [comment]
@7AC i understand but what will be the interest for the `pylint`s community to have this docker image inside `pylint`?

**Comment by 7AC** [comment]
It's pylint inside docker not the other way around, which is a pretty common way to package tools. The community can use the tool in that format without having to build their own image, and the image can get built directly from the source repo and be automatically in sync with the code.

**Pull request merged**
