### PR TITLE
Release 2.15.5

### PR DESCRIPTION
**Pull request by cdce8p**
## Description
My first try doing a release 😄

Cherry-picking worked fine. Ran into a few issues with the contributors-txt script and towncrier though.
1. Running  `python3 script/create_contributor_list.py` only adds new contributors to the bottom. Is that correct, are they ordered somehow?
2. Should we add aliases even if they only have one email?
3. `python3 script/bump_changelog.py {new_version}` changes the version in `towncrier.toml`. Should they be reset? I saw that this wasn't included in previous patch releases.
https://github.com/PyCQA/pylint/blob/f324be7de7dd20ac7763954d98d831140c6d5a91/towncrier.toml#L2-L4

Which command do you use to merge the changes into main afterwards? Just `git merge upstream/maintenance/2.15.x` or something else?

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
> Running python3 script/create_contributor_list.py only adds new contributors to the bottom. Is that correct, are they ordered somehow?

The script is not doing it properly, I've been manually sorting contributors. tbh I did not find the time to fix it but someone else making the release and having to do the manual sort make the shame sting a little now. If we want to fix this it might be easier to move the additional descriptions to json and then recreate the full file from scratch instead of parsing it each time. 

> Should we add aliases even if they only have one email?

No we don't have too, only if there's duplicate and an error during generation.

> Should they be reset? I saw that this wasn't included in previous patch releases.

I don't really know so I deselected this change because it's less thing to care about when merging the maintenance branch in main later (otherwise we need to revert it manually).

**Comment by Pierre-Sassoulas** [comment]
> Which command do you use to merge the changes into main afterwards? Just git merge upstream/maintenance/2.15.x or something else?

This command but things you also need to know:
- the changelog is duplicated silently so in astroid you need to check the changelog for the next patch version
- It's probably possible to fix conflict with a ``git checkout --ours`` but I feel the risk / reward ratio is really too high so I just fix conflict manually
- I check the diff with ``git diff upstream/main`` before opening a PR (for pylint) or pushing (for astroid) the merge commit to main.

**Comment by cdce8p** [comment]
> > Which command do you use to merge the changes into main afterwards? Just git merge upstream/maintenance/2.15.x or something else?
> 
> This command but things you also need to know:
> 
> * the changelog is duplicated silently so in astroid you need to check the changelog for the next patch version
> * It's probably possible to fix conflict with a `git checkout --ours` but I feel the risk / reward ratio is really too high so I just fix conflict manually
> * I check the diff with `git diff upstream/main` before opening a PR (for pylint) or pushing (for astroid) the merge commit to main.

👍🏻 I just tested the merging and it seem to work. At least the final diff is as expected. Had to resolve a few conflicts but was fairly strait forward.

> > Should they be reset? I saw that this wasn't included in previous patch releases.
> 
> I don't really know so I deselected this change because it's less thing to care about when merging the maintenance branch in main later (otherwise we need to revert it manually).

Having tested the back-merge, I think it's safe to include the change (in the maintenance branch). It will be resolved during the merge and even if not updated when the `bump_changelog.py` script is run.

> > Running python3 script/create_contributor_list.py only adds new contributors to the bottom. Is that correct, are they ordered somehow?
> 
> The script is not doing it properly, I've been manually sorting contributors. tbh I did not find the time to fix it but someone else making the release and having to do the manual sort make the shame sting a little now. If we want to fix this it might be easier to move the additional descriptions to json and then recreate the full file from scratch instead of parsing it each time.

It fine. We can add it to our long ToDo list 😄 I was just confused why it wasn't working / if it was working correctly since I  didn't follow the discussions around it.

--

I think the release is ready then.

**Review by Pierre-Sassoulas — APPROVED** [review]
Just FYI Daniel suggested to create a backporting merge request and then a subsequent release branch to be able to review the release easily, let's do it next time :)

**Comment by cdce8p** [comment]
> Just FYI Daniel suggested to create a backporting merge request and then a subsequent release branch to be able to review the release easily, let's do it next time :)

Not exactly sure what you mean. E.g. I needed to redo #7662 to include the merge commit.
Or just open it for comparison, do everything else, rebase / redo the backporting merge request?

**Comment by Pierre-Sassoulas** [comment]
> Not exactly sure what you mean.

I meant opening a MR for the cherry-picking (backporting) in maintenance/2.15.x and another one for the release (tbump command)  in maintenance/2.15.x before the release of 2.15.5. Like for #7591 / #7590.

That way it's easier to see what the tbump command did. It's the only thing that really need review at release time (if there wasn't any conflict during cherry-picking).

But, this is just a remark for next release: let's not redo everything for the sake of it, I do not mind reviewing everything in batch personally.

**Comment by cdce8p** [comment]
> > Not exactly sure what you mean.
> 
> I meant opening a MR for the cherry-picking (backporting) in maintenance/2.15.x and another one for the release (tbump command) in maintenance/2.15.x before the release of 2.15.5. Like for #7591 / #7590.

Think I got it now. So separating the backporting PR form the actual release. My impression was that it's easy enough to view just the last commit (the one from tbump) so it wouldn't be necessary. Additionally, IMO it's quite nice to have all commits regarding a patch release in one PR.

**Comment by Pierre-Sassoulas** [comment]
> Think I got it now. So separating the backporting PR form the actual release. My impression was that it's easy enough to view just the last commit (the one from tbump) so it wouldn't be necessary. Additionally, IMO it's quite nice to have all commits regarding a patch release in one PR.

What do you think @DanielNoord ?

**Comment by DanielNoord** [comment]
For `pylint` the PRs can get very large. Since cherry picked commits can still be completely different than the actual commit we preferably also check those to make sure nothing bad slipped in.
Together with the many changes in contributors and new changelog generation those PRs got a little too big to review easily.

**Comment by cdce8p** [comment]
> For `pylint` the PRs can get very large. Since cherry picked commits can still be completely different than the actual commit we preferably also check those to make sure nothing bad slipped in.
> Together with the many changes in contributors and new changelog generation those PRs got a little too big to review easily.

They are large either way. Splitting it into two doesn't reduce the line count. IMO it's fairly easy to separate the changelog and contributor changes during the review with commit ranges. E.g. https://github.com/PyCQA/pylint/pull/7660/files/9c239c2eecb5925a4aabc73423c65eb67fdf151d

Creating a second PR is just more work and will make it more difficult later to understand what the actual release was.

> Since cherry picked commits can still be completely different than the actual commit we preferably also check those to make sure nothing bad slipped in.

That's always an issue with cherry-picking for patch releases since theoretically you could hide something just in the maintenance branch. In the end, I think the best solution here would be to release more often so the diffs are smaller. Besides that only a select few (at the moment maybe we three) should do them at all.

Just for reference, this is a PR for a Home Assistant patch release. Note that the last commit / the version bump is included. https://github.com/home-assistant/core/pull/80691

**Comment by DanielNoord** [comment]
Yeah, agreed but this was mainly due to the issues we had with the new changelog, contributor list and copyright notices. We had to rebase and force push many times. In those cases it was much easier to just merge the commits first.
A changelog change can easily be reviewed from mobile, that also helps.

I mean if you want to keep doing them like this that is also fine with me of course!

**Pull request merged**
