### PR TITLE
Decrease number of runners used in CI

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

This should improve the speed of our CI. Since all tests jobs now depend on `Linux` passing there is really no need to separate these set-ups steps. They just take extra time setting up Python, checking out code and restoring the venv. That can all be done in the same runner: freeing up more runners and decreasing the overall runtime of the CI.

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
But isn't having multiple step better from a caching point of view ?

**Comment by DanielNoord** [comment]
> But isn't having multiple step better from a caching point of view ?

I don't think so in this instance. If you look at which steps gets removed those exact steps are take in the prepare step as well. The only difference is `Create Python virtual environment` and `Fail job if Python cache restore failed`. In the preparation job we create a new `venv` if we fail to restore it and in the test job we fail.

**Comment by Pierre-Sassoulas** [comment]
I also realized (because the number of jobs is more manageable surely) that we're running the benchmark for 3.8 and 3.9. Should we also run it just for one interpreter ? (Especially seeing we never did anything with the result.)

**Comment by DanielNoord** [comment]
> I also realized (because the number of jobs is more manageable surely) that we're running the benchmark for 3.8 and 3.9. Should we also run it just for one interpreter ? (Especially seeing we never did anything with the result.)

Might as well? Want me to add a commit to this PR to change it?

**Comment by Pierre-Sassoulas** [comment]
I'm close to removing it completely, but I think we could do a github action on the model you did for pylint false positive we just do the benchmark on top of it. And we display new message, removed message and the modification of the time compared to the previous commit.

**Comment by cdce8p** [comment]
Saw this PR today. Thanks @DanielNoord for doing it! We should probably do that change for astroid, too.

A bit more background information: The original structure (separate jobs for prepare and test) was similar to the one Home Assistant uses. For HA it has serval advantages that don't fully apply here.
* We only have a few dependencies, so creating the venv is fairly quick. In comparison HA has multiple hundreds deps.
* `prepare-tests` was only really used to run the `tests` itself. HA runs 4 different checks afterwards.
* I believe the "new" cache is only stored if the job itself completes successfully. That isn't a problem when venv creation is quick. For HA, it would be a noticeable slowdown.

**Pull request merged**
