### PR TITLE
Fix pylintrc file

### PR DESCRIPTION
**Pull request by cdce8p**
## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description
While checking #4272 I noticed that the `pylintrc` file used outdated syntax and the `bad_builtin` extension wasn't loaded although `bad-functions` where defined.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
|  | :hammer: Refactoring  |

## Related Issue
--

### CODE REVIEW

**Comment by cdce8p** [comment]
While trying to replace `filter`, I noticed that the code almost always got more complicated without it. To give an example
https://github.com/PyCQA/pylint/blob/3cbc6d60290c4aa630a96d3885c77a82e5ee86c2/pylint/checkers/format.py#L529-L532
Would become
```py
line = next(
    (self.linter._pragma_lineno.get(name) for name in names
     if self.linter._pragma_lineno.get(name) is not None),
    1,
)
```

This would work much better with assignment expressions, but those require Python 3.8

--
List of all other places that use `filter`: https://github.com/PyCQA/pylint/runs/2246931694#step:8:35

**Review by Pierre-Sassoulas — APPROVED** [review]
Nice cleanup on top of the fix !

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
I approved a little too fast, would it be possible to add a functional test for that ?

**Comment by cdce8p** [comment]
@Pierre-Sassoulas What do you had in mind? I could add a functional test for the extension functionality but there is already [test_bad_builins.py](https://github.com/PyCQA/pylint/blob/121530dd82bd89dca9cbc44193618177140b86d7/tests/extensions/test_bad_builtin.py). The issue here probably was a refactoring into the extensions module without updating the `pylintrc` file.

**Comment by Pierre-Sassoulas** [comment]
Something like a `tests/functionall/b/bad_builtins.rc` containing:
```ini
[pylint.DEPRECATED_BUILTINS]

# List of builtins function names that should not be used, separated by a comma
bad-functions=map,input,print,filter
```
With `tests/functionall/b/bad_builtins.py` 
```python
input("Yes or no ? (Y=1, n=0)") # [bad-builtins]
print(map(str, filter(1, [1,2,3])) # [bad-builtins, bad-builtins,bad-builtins]
```

**Comment by cdce8p** [comment]
I mind be missing something, but the functional test doesn't work. As far as I can tell the code to load the extension is never even executed. This might also be the reason why an extra unittest exists: [tests/extensions/test_bad_builtin.py](https://github.com/PyCQA/pylint/blob/master/tests/extensions/test_bad_builtin.py)

For reference, I tested these files:
```py
# pylint: disable=missing-docstring
input("Yes or no ? (Y=1, n=0)")  # [bad-builtins]
print(map(str, filter(1, [1, 2, 3])))  # [bad-builtins, bad-builtins,bad-builtins]
```

```ini
[MASTER]
load-plugins = pylint.extensions.bad_builtin

[pylint.DEPRECATED_BUILTINS]
bad-functions=map,input,filter,print
```

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
Ho ok I did'nt know, this is something we could change in the functional test so it works but unrelated to this MR.

**Pull request merged**
