### PR TITLE
Update docs to explain escape character not valid

### PR DESCRIPTION
**Pull request by tbennett0**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

This just adds the note from #5415 to docs to explain that `\` is not valid in ignore-paths per https://github.com/PyCQA/pylint/issues/5398#issuecomment-981156554 because it also currently is needed to support Windows path normalization. This will help avoid additional issues being created (like the one I created in #7089 and also someone else in #7094) to reduce the burden on pylint maintainers/developers.

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
Thank you for contributing to pylint ! Indeed we should have documented this better. I think the file you modified is autogenerated, could you search for the Python file with the same text and modify this one instead, please ?

**Review by Pierre-Sassoulas — APPROVED** [review]
Thanks a lot, and congratulation on becoming a pylint contributor :) !

**Comment by tbennett0** [comment]
@Pierre-Sassoulas it looks the the auto-upgrading tools rst doc removed my escape of the `\` and now it doesn't render correctly in docs:

image

What's the best way around that? Do I need to escape it again?

**Comment by Pierre-Sassoulas** [comment]
Does double escape work ? ``\\`` (sometime even ``\\\\``)

**Pull request merged**
