### PR TITLE
Fixed false positive of ``no-member`` for methods of namedtuples instances

### LINKED ISSUE #4377: E1101: false positive with urlparse.ParseResult geturl() after <instance>._replace(...)
New look of https://github.com/PyCQA/pylint/issues/597:
I got `no-member` warnings from code like this:

```py
    parsed_url = parse.urlparse(url)
    sorted_query = parse.urlencode(sorted(parse.parse_qsl(parsed_url.query), key=lambda param: param[0]))
    new_parsed_url = parse.ParseResult._replace(parsed_url, query=sorted_query)
    new_url = new_parsed_url.geturl()
```

if I use an instance of `ParseResult` (new_parsed_url) instead of  class static method, like:
`    new_parsed_url = parsed_url._replace(query=sorted_query)`

the warning disappears.

```
$ pylint --version

pylint 2.7.4
astroid 2.5.3
Python 3.8.7 (default, Mar  9 2021, 10:52:42)
[Clang 12.0.0 (clang-1200.0.32.29)]
```

### Steps to reproduce

pylint

Output is:

```
tests/api_test.py:28:14: E1101: Instance of 'ParseResult' has no 'geturl' member (no-member)
```

### PR DESCRIPTION
**Pull request by yushao2**
## Steps

- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`. (not sure if important bugfix)
- [x] Write a good description on what the PR does.

## Description

From investigation, it seems like _replace() yields a NamedTuple instance and ``.geturl()`` is not a valid attribute -- therefore the warning is triggered.

```python
>>> pprint(instance.as_string())
('\n'
 '\n'
 'class ParseResult(tuple):\n'
 '    __slots__ = ()\n'
 "    _fields = ['scheme', 'netloc', 'path', 'params', 'query', 'fragment']\n"
 '    \n'
 '    def _asdict(self):\n'
 '        return self.__dict__\n'
 '    \n'
 '    @classmethod\n'
 '    def _make(cls, iterable, new=tuple.__new__, len=len):\n'
 '        return new(cls, iterable)\n'
 '    \n'
 '    def _replace(self, scheme=None, netloc=None, path=None, params=None, '
 'query=None, fragment=None):\n'
 '        return self\n'
 '    \n'
 '    def __getnewargs__(self):\n'
 '        return tuple(self)\n'
 "    scheme = property(lambda self: self[0], doc='Alias for field number 0')\n"
 "    netloc = property(lambda self: self[1], doc='Alias for field number 1')\n"
 "    path = property(lambda self: self[2], doc='Alias for field number 2')\n"
 "    params = property(lambda self: self[3], doc='Alias for field number 3')\n"
 "    query = property(lambda self: self[4], doc='Alias for field number 4')\n"
 "    fragment = property(lambda self: self[5], doc='Alias for field number "
 "5')\n")
``` 

Therefore to circumvent this false-positive,

1) Check that it is a function call
2) instance's class can be inferred to be derived from tuple
--> Then we don't fire the error

I'm not too sure if this is the correct approach and thus it's marked as a draft PR, but opening this PR to get reviews / thoughts on whether this might be a potential solution / how to approach this issue

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

Closes #4377

### CODE REVIEW

**Comment by yushao2** [comment]
Marking this as ready for review to get some comments -- to see if this is the correct approach to the issue

**Review by Pierre-Sassoulas — APPROVED** [review]
Look good to me :)

**Review by cdce8p — COMMENTED** [review]
I'm not sure this should be fixed in pylint. To me it looks like a issue with the `astroid` inference of `namedtuples`. A smiliar one seems to be #4370

@nelfin Do you have an idea how to fix it? If I remember correctly, you've already worked on `brain_namedtuple_enum.py`.

**Comment by nelfin** [comment]
> I'm not sure this should be fixed in pylint. To me it looks like a issue with the `astroid` inference of `namedtuples`. A smiliar one seems to be #4370
> 
> @nelfin Do you have an idea how to fix it? If I remember correctly, you've already worked on `brain_namedtuple_enum.py`.

I'll have a look, it doesn't seem like it's an issue with subclassing `NamedTuple`s at first glance. The `sorted_query` lines in the test are a red herring as well, I can make the same test give a false-positive with this:
```python
from urllib import parse
parsed_url = parse.urlparse("http://www.this-is-weird.com")
a = parse.ParseResult._replace(parsed_url, query='foo')
b = a.geturl()  # false-positive: no-member
```

> From investigation, it seems like _replace() yields a NamedTuple instance and .geturl() is not a valid attribute -- therefore the warning is triggered.

`_replace` returns `self`, not a new `NamedTuple` instance. I think what's happening here is `urllib.parse` defines a namedtuple and assigns it to a different name (which the astroid namedtuple brain ignore), then later subclasses that base namedtuple. I think then pylint attempts to infer that class definition and it only sees the first one, but I'm less familiar with pylint that I am with astroid.

```python
# snippet from urllib.parse
_ParseResultBase = namedtuple('ParseResult', 'scheme netloc path params query fragment')
# ...
class ParseResult(_ParseResultBase, _NetlocResultMixinStr):
    __slots__ = ()
    def geturl(self):
        return urlunparse(self)
```

**Comment by Pierre-Sassoulas** [comment]
Closing because @nelfin convinced me it should be fixed in astroid instead.

**Pull request closed without merging**
