### PR TITLE
Use the ``argparse`` config handler in ``imports.py``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

Blocked by #6109.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
Maybe we could rename ``linter.namespace`` to ``linter.config``  or ``linter.option`` ?

**Comment by DanielNoord** [comment]
> Maybe we could rename `linter.namespace` to `linter.config` or `linter.option` ?

Shall we do that once I have done all checkers? I can imagine that we might not actually want to put it on the `linter` but set it as `config` on each `checker` for example.

**Comment by Pierre-Sassoulas** [comment]
It depends if cleaning up later costs more than doing it since the beginning, I'll let you be the judge of that 😄

**Comment by DanielNoord** [comment]
> It depends if cleaning up later costs more than doing it since the beginning, I'll let you be the judge of that 😄

I'll probably use a replace all for that. I think for now I'll continue like this.

**Pull request merged**
