### PR TITLE
Add examples for ``bad-str-strip-call``

### PR DESCRIPTION
**Pull request by DudeNr33**
- [x] Write a good description on what the PR does.
- [x] If you used multiple emails or multiple names when contributing, add your mails
   and preferred name in ``script/.contributors_aliases.json``

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|    | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description
Add examples and explanation for ``bad-str-strip-call``.

Ref: #5953

### CODE REVIEW

**Review by DanielNoord — APPROVED** [review]

**Comment by DanielNoord** [comment]
Learned something new today 😄

**Comment by DudeNr33** [comment]
It also took me a long time to figure that one out. 😀 That's why I thought adding a bit more info in the ``details.rst`` would be reasonable here.

**Comment by DanielNoord** [comment]
> It also took me a long time to figure that one out. 😀 That's why I thought adding a bit more info in the `details.rst` would be reasonable here.

We might also want to update the message description and what is emitted. The description is actually more helpful than the actual message.

**Comment by Pierre-Sassoulas** [comment]
I opened a follow-up #6093 to try to make it easier to understand without reading the python documentation

**Pull request merged**
