### PR TITLE
Avoid raising `undefined-loop-variable` twice on same line

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

See https://github.com/PyCQA/pylint/pull/6923#discussion_r895134495 for report.

This call has been here since the initial commit, but nothing fails when I remove it. Let's see what the primer says.

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
I spot-checked the messages from sentry, and found that they were duplicates that are now just emitted once.

**Review by DanielNoord — APPROVED** [review]
While checking if `self._loopvar_name(node)` is still being used I noticed that the other use is guarded by `if self._is_undefined_loop_variable_enabled`.

This breaks `useless-suppression`. We could fix that in this PR as well or do a follow-up.

**Review by Pierre-Sassoulas — APPROVED** [review]
👌

**Comment by Pierre-Sassoulas** [comment]
Nice catch @DanielNoord. Let's do a follow-up as it's another issue.

**Pull request merged**
