### PR TITLE
Add the `coverage` package to the primer suite.

### PR DESCRIPTION
**Pull request by mbyrnepr2**
## Description
Adding the package to the primer test suite as [discussed](https://github.com/PyCQA/pylint/issues/5359#issuecomment-1291843791).

Refs #5359

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]

**Comment by Pierre-Sassoulas** [comment]
(Regarding the milestone, we're trying to remove documentation/maintenance/skip news from the milestone so it's easier to look what is in a release in github)

**Comment by mbyrnepr2** [comment]
> (Regarding the milestone, we're trying to remove documentation/maintenance/skip news from the milestone so it's easier to look what is in a release in github)

Ok clear - I've added a fragment & removed the `skip news` & `maintenance` labels.

**Comment by Pierre-Sassoulas** [comment]
Sorry I meant it's better to not define the milestone for maintenance issue or issue with skip news so the gtihub milestone is not flooded with non user facing merge request. This is why I removed the 2.16.0 milestone previously. You were right to add skip news and maintenance, this does not need to be documented :)

**Comment by mbyrnepr2** [comment]
> Sorry I meant it's better to not define the milestone for maintenance issue or issue with skip news so the gtihub milestone is not flooded with non user facing merge request. This is why I removed the 2.16.0 milestone previously. You were right to add skip news and maintenance, this does not need to be documented :)

Its too early for me haha! Of course I'll remove the fragment.

**Review by Pierre-Sassoulas — APPROVED** [review]
👍

**Pull request merged**
