### PR TITLE
Move ``TestVariablesChecker`` to functional tests

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

Step one of many.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
I like the fact that you did it for one file only, it makes it more manageable as there are small moving part to takes into account during review. What do you think about the time it took you to do the refactor ? Was it worth it ? If that's the case I'll open an issue to track each file we need to move.

**Comment by DanielNoord** [comment]
This one was okay, but I looked at some of the other files and they might be more difficult. There are tests such as `TestImportsChecker` and `TestDeprecatedChecker`  which are not as straightforward..

**Comment by Pierre-Sassoulas** [comment]
> There are tests such as TestImportsChecker and TestDeprecatedChecker which are not as straightforward..

Let's not focus too much on this then, clearly, it's not a high priority issue. I think more typing in astroid will yield better result

**Comment by Pierre-Sassoulas** [comment]
Although clearly this make pylint more friendly for new contributors and removing almost 100 lines of code is obviously a very good thing..

**Comment by DanielNoord** [comment]
> it's not a high priority issue.

I don't necessarily agree.

See L160 in `tests/checkers/unittest_unicode.py` in #5311. Contributors are running into issues with this and are forced to ignore `end_column`. In the end that means we will only need to update more code. I think this is actually quite high priority and the checking of `end_column` should be turned on sooner than later.

**Comment by Pierre-Sassoulas** [comment]
>  In the end that means we will only need to update more code.

True, true. Also unittest are very hard to understand comparatively. For maintenance work it's pretty high on the list for sure. I was comparing the priority to the json output for 3.0 alpha that will make vscode and pycharm better or other high value issues directly affecting known bugs or highly demanded features.

**Pull request merged**
