### PR TITLE
Add check against initializing and then mutating a dictionary

### LINKED ISSUE #2876: New check: Use single-statement dict initialization
Here's an ugly pattern, commonly found in eg config files:

```python
config = {}
config['dir'] = 'bin'
config['user'] = 'me'
config['workers'] = 5
```

An empty dict is initialized and then mutated several times. It would
be better to use declarative literal syntax:

```python
config = {
    'dir': 'bin',
    'user': 'me',
    'workers': 5,
}
```

No mutation! No repetition!

I'm imagining a check that would look for an empty dict initialization
and then see if any following lines are bare dict assignments. It
could get tricky though, as this pattern horrible pattern is sometimes
recursive:

```python
config = {}
config['dir'] = 'bin'
config['user'] = 'me'
config['workers'] = 5
config['options'] = {}
config['options']['debug'] = False
config['options']['verbose'] = True
```

Yuck!

And I know, a check like this gets released, CIs start showing failing
builds, and everyone thinks the sky is falling. Maybe make it
optional? Or a warning or something? Anything to discourage this
pattern.

### PR DESCRIPTION
**Pull request by nickdrozd**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Description

Add a new optional check against initializing a dictionary and then immediately mutating it.

Closes #2876

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
I'm putting this in 2.14 as I'm hoping to release 2.13 at some point and it's becoming huge. We'll still have python 3.7 support in 2.14so the code should be compatible with it.

**Comment by DanielNoord** [comment]
Hi @nickdrozd,

We have been working on the documentation of the messages that pylint emits. As this PR adds a new message could I ask you to rebase on `main` and add two examples for bad and good code like explained in https://github.com/PyCQA/pylint/issues/5953? That way we immediately help users understand what this new message will do 😄

**Comment by clavedeluna** [comment]
@nickdrozd do you still have bandwidth to work on this?

**Comment by nickdrozd** [comment]
@clavedeluna Yes, although if it interests you, please feel free to take it over!

**Comment by clavedeluna** [comment]
Yes I can take over. I may just need to create a separate PR tho, to avoid permission issues. May be easy to fix but idk how exactly.

**Pull request closed without merging**
