### PR TITLE
Subclass ``BaseRawFileChecker`` and ``BaseTokenChecker``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

Ref. #2287

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
I think the how to implement a checker doc should be updated a little, right ?

**Comment by DanielNoord** [comment]
> I think the how to implement a checker doc should be updated a little, right ?

I'll do a check for any `interfaces....` code/text after the `DeprecationWarning` gets emitted. Only two/three PRs remain for this to be done.

_Perhaps wait with the 2.14 pre-release and get this as well? Should be able to finish this tonight/tomorrow?_

**Comment by Pierre-Sassoulas** [comment]
Yeah I'm too sleepy to release anything right now anyway 😄

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
Also I need to create a namespace test repository for https://github.com/PyCQA/pylint/pull/5235

**Pull request merged**
