### PR TITLE
Remove the python3 porting mode from the codebase

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

It's possible to use the python3 porting checker from
an older pylint version. But it's not evolving anymore
and was costing resource to maintain.

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
@DanielNoord, I opened that following your suggestion in #4940

**Comment by DanielNoord** [comment]
Looks good, quite a lot of work!

I will rebase #4940 after this has been merged and see if there are any remaining issues.

**Comment by DanielNoord** [comment]
Doing a quick search through the repo I think the following issues can be closed after merging this PR:

#4174, #3928, #3487, #3051, #2674, #2582, #2130

These are all issues occurring with the `--py3k` flag.

**Review by cdce8p — APPROVED** [review]
Looks good! As this is quite a large change, would you mind adding an entry in `whatsnew`?

**Comment by Pierre-Sassoulas** [comment]
Thank you for checking the issue we can close @DanielNoord :)

**Pull request merged**
