### PR TITLE
[openssf] Add the badge for the openssf foundation

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

Add the badge for the openssf fondation. Follow-up to #7267 that was already documented in the changelog.

### CODE REVIEW

**Review by DanielNoord — APPROVED** [review]

**Comment by DanielNoord** [comment]
Is that link correct?
It seems to link to the direct `api` output:
https://api.securityscorecards.dev/projects/github.com/PyCQA/pylint

**Comment by Pierre-Sassoulas** [comment]
> Is that link correct?

Yeah, that's what is suggested by openssf. (Personally I would link the dashboard)

**Comment by DanielNoord** [comment]
> > Is that link correct?
> 
> Yeah, that's what is suggested by openssf. (Personally I would link the dashboard)

Oh wow... That's really unuserfriendly 😅

**Comment by Pierre-Sassoulas** [comment]
Apparently security oriented persons can read the matrix. It seems an API is super user friendly compared to bisecting an entry in a database based on response time of SQL injection requests 🤷 (:trollface: )

**Pull request merged**
