### PR TITLE
Fix python3 checker to handle raising an empty tuple.

### PR DESCRIPTION
**Pull request by dbaum**
I'm new to working with pylint - please let me know if there's a better way to make this change.

### CODE REVIEW

**Comment by PCManticore** [comment]
This should probably be fixed into astroid itself, so that unpack_infer won't raise StopIteration anymore.

**Comment by dbaum** [comment]
I'm unfamiliar with astroid, but the docstring for unpack_infer states:

"""recursively generate nodes inferred by the given statement.
    If the inferred value is a list or a tuple, recurse on the elements
    """

From that, I believe unpack_infer is basically flattening the inferred results.  Flattening, by its very nature, discards the tuple/list structures:
  [1, 2, [3, 4]] -> 1, 2, 3, 4
  [1, [], 2, 3] -> 1, 2, 3
  [] -> 

Are you proposing that we yield empty lists/tuples as-is but still flatten non-empty ones?
[] -> []
[1, [], 2, 3] -> 1, [], 2, 3
[1, [2], 3] -> 1, 2, 3

That seems like a fairly big change to unpack_infer's intended operation.  Are you certain it won't cause even more problems elsewhere?

If this is really the best change, then I'll give it a try.  But it seems to me that the real problem isn't unpack_infer, but the fact that visit_raise() calls next() and assumes there will be at least one result.

**Comment by PCManticore** [comment]
The problem is that unpack_infer lets StopIteration to propagate, whilst it should raise a custom exception instead, in this case InferenceError. It might be decorated with astroid.decorators.raise_if_nothing_inferred and that should fix the problem. A test will also be needed.

**Comment by dbaum** [comment]
I hate to keep bugging you, but I'm seeing some very strange behavior.  I
decorated unpack_infer() as you suggested, ran the existing tests, and saw
this failure:

FAIL: test_builtin_fromlineno_missing (unittest_nodes.ArgumentsNodeTC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File
"/Users/dbaum/Desktop/pylint/astroid/astroid/tests/unittest_nodes.py", line
500, in test_builtin_fromlineno_missing
    self.assertEqual(new.args.fromlineno, 0)
AssertionError: 1 != 0

This appears to be an intermittent failure.  For example, if I make a
change to the unittest_nodes.py and then run all tests like this:

python -Wi -m unittest discover -p "*test_*.py"

Everything passes the first time I run the tests, then I see the failure if
I run the tests a second time.  If I run just the one test file:

python unittest_nodes.py

Then I never see the failure.  Could this be related to whether the test is
running from a .py or .pyc file?  If so, why does my change to
unpack_infer() lead to this?  What's a reasonable fix?

**Comment by dbaum** [comment]
Strange - I haven't been able to get that test to fail at all in the last
15 minutes or so.  I still believe there is something flaky about that
test, but it is unclear to me whether unpack_infer() should impact it, and
I'm not really sure how to deal with the test.

Dave

**Comment by The-Compiler** [comment]
I don't remember where it was, but somewhere @PCManticore commented today that this was a flaky test, so I think you should be fine.

**Comment by dbaum** [comment]
ok, I'll start a pull request and we'll see if all the checks pass (is
there a way to kick off all of the checks before bugging you with a pull
request?)

Dave

**Comment by PCManticore** [comment]
@dbaum you could run tox locally, if you have it installed.

Something along the lines of ``tox -e py27`` or simply ``tox`` should do the trick.

**Comment by PCManticore** [comment]
I'm going to close this since the fix in astroid is the good one.

**Pull request closed without merging**
