### PR TITLE
Rephrase Functional tests section in writing_test docs page

### PR DESCRIPTION
**Pull request by orSolocate**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|    | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

The `Functional tests` section in the [Writing Test docs page](https://pylint.pycqa.org/en/latest/development_guide/contributor_guide/tests/writing_test.html) is unclear in the example for the `n` lines option:

```
# +1: [empty-comment]
#
```

The second line with `#` can be easily mistaken for being part of the syntax, or meaning some line, where the true meaning is the `empty-comment` error itself..
This PR offers a much better example, which doesn't mix up the syntax of what the example trying the show and the example itself.

see discussion in [the comment here](https://github.com/PyCQA/pylint/pull/7745#discussion_r1034965689).

Refs #7745.

### CODE REVIEW

**Comment by orSolocate** [comment]
why is it failing? Is the `newsfragment` is a must for a PR? There is no category for `docs` though... so it is confusing..

**Review by DanielNoord — COMMENTED** [review]
Shouldn't we use double back ticks everywhere?

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
LGTM, thank you  ! We need to fix the backtick like @DanielNoord said.

**Comment by orSolocate** [comment]
Thanks guys, if that's all I think this one is ready to go!

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
Thank you for making the doc better !

**Pull request merged**
