### PR TITLE
Added chained-comparison message example

### PR DESCRIPTION
**Pull request by matusvalo**
Co-authored-by: Vladyslav Krylasov <vladyslav.krylasov@gmail.com>

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|     | :bug: Bug fix          |
|     | :sparkles: New feature |
|     | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Related: #5953

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Aren't good and bad inverted here ?

**Comment by matusvalo** [comment]
> Aren't good and bad inverted here ?

https://vald-phoenix.github.io/pylint-errors/plerr/errors/refactoring/R1716

```
matus@MacBook-Pro:~/dev/pylint/doc$ cat test.py
a = int(input())
b = int(input())
c = int(input())
if a < b and b < c:
    pass
matus@MacBook-Pro:~/dev/pylint/doc$ pylint test.py
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test.py:4:3: R1716: Simplify chained comparison between the operands (chained-comparison)

------------------------------------------------------------------
Your code has been rated at 6.00/10 (previous run: 6.00/10, +0.00)
```

**Comment by Pierre-Sassoulas** [comment]
I mean the `` a < b and b < c: # [chained-comparison]`` is actually in the good.py file not the bad.py. Probably something that our documentation tests should catch now that I think of it.

**Comment by matusvalo** [comment]
Yes you are right nie I see it. I will fix it.

**Comment by matusvalo** [comment]
> Aren't good and bad inverted here ?

fixed

**Comment by matusvalo** [comment]
> Probably something that our documentation tests should catch now that I think of it

created #6145

**Review by Pierre-Sassoulas — APPROVED** [review]
Thanks for the generic fix, much appreciated !

**Pull request merged**
