### PR TITLE
[primer] stop overwriting `--rcfile`

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description
~Move everything into the new primer and increase the timeout on the `main` job. (3.7 is about 2x as slow as 3.10)
Follow up to #6761 and #6753.~

Never mind, we will have to discuss that separately.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
The error of the CI is strange, it seems there's a mix up between django and black

**Comment by DanielNoord** [comment]
@jacobtylerwalls Did you test this on your local branch to see the time differences?

**Comment by jacobtylerwalls** [comment]
Good point, I hadn't. I just did. I removed `keras` to try to get the job under 45m. With just `django` and `music21`, added, the 3.10 job finishes in 30 minutes. 3.7 seems to take 1.5x as long, which just barely exceeds 45m (hard to tell, but that's my guess.)

Neither of the two projects I'm adding support 3.7 anymore. I'm wondering if we even need that job?

**Comment by jacobtylerwalls** [comment]
The changes in `astroid` are to be expected because we're using the correct `--rcfile` now.

I plan to merge this tonight based on Pierre's approval earlier of the cleanups.

I'll move discussion about adding packages to #5359, since I think it's clear we need to look at parallelization instead of just adding packages to a single run. The 3.10 (the faster one!) errored out on CI with an out of memory error, probably trying to deal with the massive list of messages.

**Pull request merged**
