### PR TITLE
Remove docs and code associated with the removed W0623 (redefine-in-handler) checker

### PR DESCRIPTION
**Pull request by lorena-b**
## Description

Refactoring the code so that it no longer contains code associated with the removed W0623 (redefine-in-handler) checker. 

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring |

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
I don't understand this change, I don't think ``redefine-in-handler`` was removed ? Or do you want to remove it ?

**Comment by Pierre-Sassoulas** [comment]
If you want to remove a warning or a checker, let's keep it as a non default one instead and let's discuss it first in #3512.

**Comment by lorena-b** [comment]
> If you want to remove a warning or a checker, let's keep it as a non default one instead and let's discuss it first in #3512.

I am not trying to remove the checker for `redefine-in-handler`, this checker is no longer implemented. The checker is still written in the documentation however which caused confusion for my team who is developing a linter based on Pylint. The checker was removed in this commit: [](https://github.com/PyCQA/pylint/commit/0a90b4a0b369d75a3e2aee9a4ad57ce264bc18a0). Unused code and the message related to this checker was left in the repository so I thought removing it would clear up any confusion.

**Comment by lorena-b** [comment]
> Looking at the commit you provided it seems that the checker it removed where `relative-import`, `invalid-encoded-data`, and `missing-super-argument`, am I missing something ?

If you scroll down (or ctrl+F) to the changes made in pylint/checkers/variables.py, it looks like the entire checker for `redefine-in-handler` was removed. Maybe the commit message forgot to include this checker.

**Comment by Pierre-Sassoulas** [comment]
Right, my bad ! Thank you for the cleanup then 😄

**Comment by Pierre-Sassoulas** [comment]
I think the error in the tests suite is due to the message being disabled while it does not exists(``bad-option-value``). It could be fixed by removing the disable. Would you mind doing that @lorena-b ?

**Comment by Pierre-Sassoulas** [comment]
Thank you for the cleanup, and congratulation on becoming a pylint contributor with 12 time more deletion than addition 😄

**Pull request merged**
