### PR TITLE
Enable checking of rst files during build

### PR DESCRIPTION
**Pull request by pheanex**
At the moment we have ~242 rst lint issues.
=> We probably want to fix them (here?) as well (build fails otherwise so far).
PR already opend to discuss if this is a viable way and what kind of issues we want rst-lint to report ("INFO"?)

### CODE REVIEW

**Comment by pheanex** [comment]
#2150

**Comment by brycepg** [comment]
I'm definitely for this seeing that some of the rst code examples are hidden in the whatsnew dialogue.

**Comment by brycepg** [comment]
It looks like building `build-sphinx` docs already offers some warnings -- do we just want to add `-W` to those to turn those warnings into errors or does this linter provide more functionality?

**Comment by brycepg** [comment]
I wish `sphinx-build` would output more than just one warning at a time with the `-W` option.. Although that might be ok once we fix all the errors

**Comment by brycepg** [comment]
I'm looking at the rst linter, and it looks like it doesn't understand sphinx defined roles (which creates a lot of false positives), so I think we should just stick with `-W`

Fixed sphinx-build warnings in #2370 (I don't think I can push to here)

Can you remove the (no longer needed) dependency for this PR?

**Comment by brycepg** [comment]
Sorry I messed this branch up

**Comment by PCManticore** [comment]
Thank you both for working on this!

**Pull request merged**
