### PR TITLE
Allow lists of default values in parameter documentation for ``Numpy``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes https://github.com/PyCQA/pylint/issues/4035.

I really don't want to talk about the number of hours it took me to get this regex right. The fact that I assigned this to myself in October is a small indication...

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
I think we're hitting the limit of what regex are good for, but as you spent 9 months to birth it let's put a diaper on the little ``re_param_line`` and try to keep it alive and clean now 😄

**Comment by DanielNoord** [comment]
> I think we're hitting the limit of what regex are good for, but as you spent 9 months to birth it let's put a diaper on the little `re_param_line` and try to keep it alive and clean now 😄

It's also that some of these regexes are really quite bad. Using both f-strings and regular expressions from different classes and in different recursive patterns is awful to work with. You can't easily copy them to `regex101` and try to fix something.
That made this really difficult.

**Comment by Pierre-Sassoulas** [comment]
Outch should have waited for the primer, before approving.

**Comment by Pierre-Sassoulas** [comment]
Hmm right, we have most message with actually a more accurate message with one param that do not warn anymore. This is why we need the better primer diff, I need to do it from scratch again though 😄

**Pull request merged**
