### PR TITLE
Deprecate extension-pkg-whitelist

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

Ref. https://github.com/PyCQA/pylint/issues/5465

Doesn't close as I also need to deprecate the `black_list` options.

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
I don't think we should actually deprecate this one. If we have the capability to auto-upgrade the configuration we don't need to deprecate, and if we don't then it's forcing work on our user to fix something that is not broken.

**Comment by DanielNoord** [comment]
I mean, I'm not personally offended by this in anyway but if some users are, why wouldn't we put in a little effort to alleviate that? We already have the functionality to do so, so why not use it? I get that the discussion is a bit political, but it doesn't really hurt those who aren't offended and might help those who are.

**Comment by Pierre-Sassoulas** [comment]
> but if some users are, why wouldn't we put in a little effort to alleviate that?

It's not only us doing the effort but every users that will need to upgrade their conf for 3.0. I don't want users to have to upgrade their conf in general... but in particular I don't want them to have to upgrade their configuration for political reasons.  And I especially don't want to deal with bigots that had to upgrade their configuration and now have a strong desire to tell us about the etymology of blacklist. Let's not create political breaking change, and let's not trigger anyone. 

If we do https://github.com/PyCQA/pylint/issues/5462 then we'll be able to clean up configuration. The amount of work to do this issue is tiny in comparison of the work involved for all pylint users to upgrade all their conf and probably comparable to the bigot handling we'd have to do for this anyway.

**Comment by DanielNoord** [comment]
Should we close the related issue then?

@jacobtylerwalls I noticed the `primer` diff here. Something is up with my recent `astroid` PR 😅

**Comment by Pierre-Sassoulas** [comment]
Yeah, sorry about that, #5465 only has reference to a very lengthy discussion in another PR so it's not self evident what needed to be done. I upgraded the issue as blocked by #5462

**Pull request closed without merging**
