### PR TITLE
Exposequietmode

### LINKED ISSUE #1863: Quiet mode can't be specified - but sometimes needs to be
### Steps to reproduce
If you pass a configuration file at the command line using --rcfile, then the configuration file is output to stderr (since 1.8.0 - see #1519 and #1522).  If pylint is incorporated as part of a build system, this can be problematic since it now results in what looks like an error.  

The merged commit mentions logging in "non-quiet mode", but I can't find a way to enter "quiet mode" from the command line...  (but please let me know if I'm missing something obvious).

I don't understand the rationale behind using stderr rather than stdout to begin with; however if stderr must be used, please allow some way to actually enter "quiet mode".

### Current behavior
One diagnostic line is output to stderr, no matter what.

### Expected behavior
Nothing is output to stderr (at least if "quiet mode" is enabled).

### pylint --version output
pylint 1.8.2,
astroid 1.6.1

### PR DESCRIPTION
**Pull request by garytyler**
### Fixes / new features
- Expose quiet mode to command line options with --quiet flag
- closes #1863

The quiet option is parsed in Run.preprocess_options. This was necessary due to the call order in the Run class constructor. I also moved the quiet keyword argument from OptionsManagerMixIn.__init__() to OptionsManagerMixin.read_config_file() because it wasn't used anywhere else in the class. Currently, quiet mode only manipulates the display of the config file path ("Using config file <path>").

### CODE REVIEW

**Comment by PCManticore** [comment]
Hey @garytyler This looks pretty good! Would you be so kind to add a test as well? Also don't forget to mention this change in the Changelog.

**Comment by PCManticore** [comment]
Thank you Gary!

**Comment by garytyler** [comment]
@PCManticore I probably should have noted here that I plan to add the test when I got home from my trip. I am still traveling but getting home today and still plan on going through this tomorrow.

Also, @AWhetter and I discussed adding the linter score output to the items manipulated by quiet mode. So this is also on my to do list.

Thank you @PCManticore and @AWhetter for your help!

**Comment by PCManticore** [comment]
Thanks for the contribution, @garytyler ! Sure thing, there's no rush. Also you might not find the `quiet` parameter any longer, as I renamed it to `verbose` instead, since I want this to be disabled by default and `verbose` feels more natural for this. Regarding the linter score and output, these are already handled by `-sn` respectively `-rn`, I'm not sure if it's worth putting them under `verbose` as folks could not use them anyway from the configuration file.

**Comment by garytyler** [comment]
Alright. Makes sense! I made it quiet because I thought our reasoning for verbose was more related to the implementation we discussed which ended up having some other issues. Thanks for the explanation.

**Pull request merged**
