### PR TITLE
Remove references to `astroid.node_classes`

### PR DESCRIPTION
**Pull request by cdce8p**
## Description
Remove references to `astroid.node_classes` in preparation for astroid refactoring.
All symbols are available through import from `astroid` itself.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Related Issue
https://github.com/PyCQA/astroid/pull/1057

### CODE REVIEW

**Comment by cdce8p** [comment]
@Pierre-Sassoulas I'm not sure: Do we what to import the the nodes from `astroid` or from `nodes` itself? I know we wrote about this. My first instinct was to use `astroid` but now that somehow feels wrong.

**Comment by Pierre-Sassoulas** [comment]
Yes I'm wondering about that too. Both imports are possible right now (Or should be). Maybe we can do both as 'from astroid.nodes import Call' makes more sense than 'from astroid import Call' but 'import astroid' is shorter to use than 'import astroid.nodes'(astroid.Call vs astroid.nodes.Call). But the code is less explicit. Maybe we could do something similar to numpy : 'import astroid.nodes as an' so we have shortness and expliciteness too ?

Maybe we should break the import of nodes directly from astroid in astroid 3+ to have 'only one way to do it' ? This seems extreme but if the goal is to simplify the api and make the code more explicit maybe it's worth it ?

Import rules applied strictly in pylint would help, as I imagine pylint is often taken as an example.

**Comment by cdce8p** [comment]
Though about this a bit more. Here are some options
```py
# No. 1
import astroid
astroid.Call

# No. 2
import astroid.nodes
astroid.nodes.Call

# No. 3.1
from astroid import Call
# No 3.2
from astroid.nodes import Call

# No. 4
from astroid import nodes
nodes.Call

# No. 5
import astroid.nodes as an
an.Call
```

For `nodes` I think I would prefer something that says it is in fact a node but also not too long so it isn't annoying to write. Thus, No. 4 (`nodes.Call`) looks pretty good to me.

No. 1 and 3 (`astroid.Call` / `Call`) doesn't really tell you it's a node. No. 3 doesn't even make clear that it's from astroid. No. 2 is pretty long. As for No. 5 (`an.Call`): Should we really introduce an abbriviation for it. `np`, `pd`, ... are pretty special. `astroid` doesn't reach that. What to do about the astroid exceptions then? Use `ae`?

--
As for the other imports from `astroid`: Personally I would suggest importing them from their package and remove the option to use them just from `astroid`. Maybe create a new one for `utils`. In the end it might look something like this.
```py
from astroid import nodes
nodes.Call

import astroid.exceptions
astroid.exceptions.InferenceError

import astroid.bases
astroid.bases.Instance

import astroid.utils
astroid.utils.unpack_infer(...)
```

**Comment by Pierre-Sassoulas** [comment]
> np, pd, ... are pretty special. astroid doesn't reach that.

astroid reach that level of fame in pylint code or in code using astroid 😄 But the problem is that ``a`` is too short, ``as`` is a reserved word, ``ast`` is a builtin module, and ``astr`` is starting to be too lengthy 😄 I don't think we should use ``ae`` for exception, maybe just for nodes as it's used very often ? 

I like n°4 too.

**Comment by Pierre-Sassoulas** [comment]
I see you kept this one as draft, is there a reason ?

**Comment by cdce8p** [comment]
> I see you kept this one as draft, is there a reason ?

We didn't really reach a conclusion back then. That changed now with https://github.com/PyCQA/pylint/pull/4855#issuecomment-899753785. I'm probably going to close this once the move to `from astroid import nodes` is complete. Will take a few PRs.

**Comment by Pierre-Sassoulas** [comment]
Closing following #4855 #4863 #4866 #4869

**Pull request closed without merging**
