### PR TITLE
Upgrade astroid to 2.9.1

### LINKED ISSUE #1470: Cannot find module if source file is a symbolic link
Somewhere between versions 1.5.5 and 1.7.1 the behaviour concerning modules using symbolic links to install files in the module directory has changed. Running `pylint` on such a module gives the following error:

```
$ pylint pyMyTool
No config file found, using default configuration
Traceback (most recent call last):
  File "/XXX/.local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/XXX/.local/lib/python2.7/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/XXX/.local/lib/python2.7/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "/XXX/.local/lib/python2.7/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "/XXX/.local/lib/python2.7/site-packages/pylint/lint.py", line 837, in _do_check
    for descr in self.expand_files(files_or_modules):
  File "/XXX/.local/lib/python2.7/site-packages/pylint/lint.py", line 869, in expand_files
    self.config.black_list_re)
  File "/XXX/.local/lib/python2.7/site-packages/pylint/utils.py", line 894, in expand_modules
    modpath = _modpath_from_file(subfilepath, is_namespace)
  File "/XXX/.local/lib/python2.7/site-packages/pylint/utils.py", line 833, in _modpath_from_file
    return modutils.modpath_from_file_with_callback(filename, is_package_cb=_is_package_cb)
  File "/XXX/.local/lib/python2.7/site-packages/astroid/modutils.py", line 310, in modpath_from_file_with_callback
    filename, ', \n'.join(sys.path)))
ImportError: Unable to find module for /tmp/yyy/py/git/pyBinding/module/_func.py in /tmp/yyy/py,
.,
/XXX/.local/bin,
/tmp/yyy/py/install/pyLib,
/opt/rh/devtoolset-3/root/usr/lib64/python2.6/site-packages,
/opt/rh/devtoolset-3/root/usr/lib/python2.6/site-packages,
/opt/rh/python27/root/usr/lib64/python27.zip,
/opt/rh/python27/root/usr/lib64/python2.7,
/opt/rh/python27/root/usr/lib64/python2.7/plat-linux2,
/opt/rh/python27/root/usr/lib64/python2.7/lib-tk,
/opt/rh/python27/root/usr/lib64/python2.7/lib-old,
/opt/rh/python27/root/usr/lib64/python2.7/lib-dynload,
/XXX/.local/lib/python2.7/site-packages,
/opt/rh/python27/root/usr/lib64/python2.7/site-packages,
/opt/rh/python27/root/usr/lib/python2.7/site-packages,
/XXX/.local/lib/python2.7/site-packages/astroid/brain
```

### Steps to reproduce

Consider the following directory structure:
```
/tmp/yyy/py/install/pyLib/pyMyTool/
    __init__.py ->../../../git/pyBinding/module/__init__.py (symbolic link)
    _func.py -> ../../../git/pyBinding/module/_func.py (symbolic link)
/tmp/yyy/py/git/pyBinding/module/
    __init__.py
    _func.py
```
with `__init__.py` containing:
```
from _func import func
```
and `_func.py` containing:
```
def func():
    return 1
```

The directory `/tmp/yyy/py/install/pyLib` is included in the environment variable `PYTHONPATH`. Importing the module `pyMyTool` in Python works and has the expected result:

```
$ python
Python 2.7.5 (default, Jun  5 2014, 14:38:05)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyMyTool
>>> pyMyTool.func()
1
>>>
```

### Current behavior

Running `pylint pyMyTool` prints the aforementioned error message.

### Expected behavior

Running `pylint pyMyTool` should run its tests.

### pylint --version output

```
$ pylint --version
No config file found, using default configuration
pylint 1.7.1,
astroid 1.5.2
Python 2.7.5 (default, Jun  5 2014, 14:38:05)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
```

Please let me know in case you need additional information.

### LINKED ISSUE #3499: Contents of native modules not found when running in a virtualenv
### Steps to reproduce

Lint this code:

```py
from struct import Struct
```

### Current behavior

```
E0611: No name 'Struct' in module 'struct' (no-name-in-module)
```

### Expected behavior

No error is reported, since the class `struct.Struct` exists. This class is implemented in native code, which is probably why PyLint cannot discover it. However, since it is part of the standard library, I think it would be good to have dedicated support for it.

### pylint --version output

```
pylint 2.4.4
astroid 2.3.3
Python 3.8.2 (default, Mar 05 2020, 18:58:42) [GCC]
```

### LINKED ISSUE #4302: False positive on gethostname in socket module
### Steps to reproduce

Create a simple file (or use this zipped example [socket_test.zip](https://github.com/PyCQA/pylint/files/6264705/socket_test.zip)):

```python
"""Test module."""

import socket

print(socket.gethostname())

```

Install pylint (you can use the following requirements.txt file to get the latest, or install the pre-release version):

```
astroid==2.5.2
isort==5.8.0
lazy-object-proxy==1.6.0
mccabe==0.6.1
pylint==2.7.4
toml==0.10.2
wrapt==1.12.1
```

Run `pylint test.py` on it. 

### Current behavior

```
************* Module test
test.py:5:6: E1101: Module 'socket' has no 'gethostname' member (no-member)

----------------------------------------------------------------------
Your code has been rated at -15.00/10 (previous run: -15.00/10, +0.00)

```

### Expected behavior
No issues will be found

### pylint --version output

Result of `pylint --version` output:
```
pylint 3.0.0a1
astroid 2.5.2
Python 3.9.2 (default, Mar 26 2021, 23:22:38)
[Clang 12.0.0 (clang-1200.0.32.29)]
```

or

```
pylint 2.7.4
astroid 2.5.2
Python 3.9.2 (default, Mar 26 2021, 23:22:38)
[Clang 12.0.0 (clang-1200.0.32.29)]
```

Both repro. 

Note: Running this on macOS Big Sur

### LINKED ISSUE #4798: False positives in socket library
### Bug description

Pylint complains about non existent members in the socket library of Python, although they exist according to the [docu](https://docs.python.org/3.8/library/socket.html).

Sample code:
```python
#!/usr/bin/python3

"""
socket_test.py
Pylint test for the socket library
"""
import socket


HOSTNAME = "suse.com"
IPADDR = ""

try:
    IPADDR = socket.gethostbyname_ex(HOSTNAME)
except socket.gaierror:
    IPADDR = "10.0.0.1"
print(IPADDR)
```

### Configuration

_No response_

### Command used

```shell
pylint socket_test.py
```

### Pylint output

```shell
************* Module socket_test
socket_test.py:13:13: E1101: Module 'socket' has no 'gethostbyname_ex' member (no-member)
socket_test.py:14:7: E1101: Module 'socket' has no 'gaierror' member (no-member)

---------------------------------------------------------------------
Your code has been rated at -4.29/10 (previous run: -12.86/10, +8.57)
```

### Expected behavior

Pylint should pass without error.

### Pylint version

```shell
pylint 2.8.3
astroid 2.5.6
Python 3.8.10 (default, May 05 2021, 15:36:36) [GCC]
```

### OS / Environment

openSUSE Tumbleweed

### Additional dependencies

_No response_

### LINKED ISSUE #5081: Regression: False positive I1101(c-extension-no-member) for math.iclose
### Bug description

[`math.isclose`](https://docs.python.org/3/library/math.html#math.isclose) has been around since 3.5, but now I am getting `c-extension-no-member` for it (I did not see that before).

The same error for `ceil`, `log`, `sqrt` &c

The same for [`resource.getrusage`](https://docs.python.org/3/library/resource.html#resource.getrusage) and [`zlib.crc32`](https://docs.python.org/3/library/zlib.html#zlib.crc32) (and other functions in those modules)

Also, `no-member` for [`dbm.gnu.open`](https://docs.python.org/3/library/dbm.html#dbm.gnu.open) and [`socket.AF_INET`](https://docs.python.org/3/library/socket.html#socket.AF_INET).

File:

```python
"https://github.com/PyCQA/pylint/issues/5081"
import math
math.isclose(1,2)
```

### Configuration

_No response_

### Command used

```shell
pylint a.py
```

### Pylint output

```shell
************* Module a
a.py:3: [I1101(c-extension-no-member), ] Module 'math' has no 'isclose' member, but source is unavailable. Consider adding this module to extension-pkg-allow-list if you want to perform analysis based on run-time introspection of living objects.
```

### Expected behavior

no diagnostics, as before

### Pylint version

```shell
pylint 2.11.1
astroid 2.8.0
Python 3.9.7 (default, Sep  3 2021, 12:45:31) 
[Clang 12.0.0 (clang-1200.0.32.29)]
```

### OS / Environment

_No response_

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

Closes #1470
Closes #3499
Closes #4302
Closes #4798
Closes #5081

### CODE REVIEW

**Comment by DanielNoord** [comment]
Potentially also fixes #1470?
I didn't look into it too much, but there is something about symlinking in there.

**Comment by Pierre-Sassoulas** [comment]
https://github.com/PyCQA/pylint/issues/1470#issuecomment-345093616 seems to indicate you're right, I'm going to see if I can add a regression test.

**Comment by Pierre-Sassoulas** [comment]
Sadly my regression test do not fail with astroid 2.9.0. Did you manage to reproduce #1470 @DanielNoord ? I can't with pylint 2.12.2 and astroid 2.9.0 myself.

**Comment by DanielNoord** [comment]
I didn't look into it too much. The issue seems too have a fairly straightforward reproducible example, that doesn't crash any longer?

**Comment by Pierre-Sassoulas** [comment]
> that doesn't crash any longer?

Maybe... The issue is that my example / regression test does not crash with pylint 1.7.1 either. I guess having a symlink functional test isn't a bad thing though.

**Comment by DanielNoord** [comment]
Did we manage to make this regression test work? Or does it pass even with `2.9.0`?

**Comment by Pierre-Sassoulas** [comment]
It pass even with 2.9.0, the symlink issue was actually happenning when the python installation was symlinked and not the analyzed code. But I think it's still a regression test for #1470 (the example is taken from here).

**Comment by DanielNoord** [comment]
Ah okay, so #1470 was resolved on `2.9.0` already?

**Comment by Pierre-Sassoulas** [comment]
> Ah okay, so #1470 was resolved on 2.9.0 already?

I don't know if it's specifically in astroid 2.9.0 (or even in astroid, it could be pylint) but the issue was already fixed.

**Comment by DanielNoord** [comment]
Does `git` store symlinks? I think I used the unittest framework previously to create a symlink with `os`/`sys`. Other than that, this is good to go I think.

**Comment by Pierre-Sassoulas** [comment]
> Does git store symlinks?

I think so, it's stored as the link to another file (I used the relative link for this reason). Maybe you can confirm by checking out this branch and opening the symlinked files ?

**Comment by Pierre-Sassoulas** [comment]
Nvm I think that ``../module/symlinked_module.py`` would create a problem in github actions if it was not a symlink and a "normal" python file.

**Pull request merged**
