### PR TITLE
Fix iterating over whole remaining file for each comma token in _check_one_element_trailing_comma_tuple

### PR DESCRIPTION
**Pull request by rogalski**

### CODE REVIEW

**Comment by degustaf** [comment]
@rogalski Do we have any concrete evidence that this improves the performance?

**Comment by rogalski** [comment]
Not yet, I just want to have a possibility to run it on travis infrastructure.

**Comment by rogalski** [comment]
I'll add regression test suite later, I just need to clean it up a little bit.

**Comment by rogalski** [comment]
Given pessimistic file on input (a lot of lines and a lot of commas):

```
def generate_pessimistic_case_file(num_lines):
    with tempfile.NamedTemporaryFile('w', delete=False) as fh:
        fh.write('"""Generated perf case for N={}"""\n'.format(num_lines))
        for n in range(num_lines):
            fh.write("(1, 2, 3, 4, 5)\n")
    return fh.name
```

I see difference in performance:

New code: `{1024: 0.48037195205688477, 2048: 0.9564249515533447, 4096: 4.12202787399292}`
Old code: `{1024: 5.947703123092651, 2048: 23.882505893707275, 4096: 95.08256006240845}`

Where values in dicts are measured as following:
```
def run_pylint_tokenize_perf_test(filepath):
    start = time.time()
    try:
        pylint.lint.Run(['--disable=all', '--enable=trailing-comma-tuple', filepath])
    except SystemExit:
        pass
    stop = time.time()
    return stop-start
```

I'm not yet sure how final test should look like (or even if it needs tests at all).

**Comment by rogalski** [comment]
Closes #1447

**Comment by PCManticore** [comment]
I'm happy with this. Thank you so much @rogalski

**Pull request merged**
