### PR TITLE
Fix `unnecessary-lambda` false positive for lambdas using its parameters in their body

### LINKED ISSUE #8496: `unnecessary-lambda` false positive if parameter is used in lambda body
### Bug description

A `unnecessary-lambda` warning is created for lambda expressions which use one of its parameters in its body, for example:

```py
# pylint: disable=expression-not-assigned,missing-module-docstring,undefined-variable
lambda x: x(x)
```

My real code was something like

```py
lambda foo, bar: (function1 if bar == 1 else function2)(foo, bar)
```

### Configuration

_No response_

### Command used

```shell
pylint tmp.py
```

### Pylint output

```shell
************* Module tmp
tmp.py:2:0: W0108: Lambda may not be necessary (unnecessary-lambda)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Expected behavior

No warning

### Pylint version

```shell
pylint 2.17.0
astroid 2.15.0
Python 3.11.2 (main, Mar 17 2023, 12:30:14) [Clang 14.0.0 (clang-1400.0.29.202)]
```

### OS / Environment

_No response_

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by cherryblossom000**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #8496

### CODE REVIEW

**Comment by cherryblossom000** [comment]
I refactored the `unnecessary-lambda` code a little because of the lint warning

> pylint/checkers/base/basic_checker.py:522:4: R0911: Too many return statements (12/11) (too-many-return-statements)

**Comment by nickdrozd** [comment]
The `max-returns` limit is set in `pylintrc`. You can just bump that number instead of rewriting everything. The function could certainly use a refactor, but that can be done in a separate PR.

**Comment by Pierre-Sassoulas** [comment]
I'd rather disable this one message locally than change the setting for the whole code base.

**Comment by cherryblossom000** [comment]
I’ve disabled the warning for that line.

**Review by Pierre-Sassoulas — APPROVED** [review]
👌

**Comment by Pierre-Sassoulas** [comment]
Amazing first contribution @cherryblossom000 ! This is going into the next patch version (2.17.2)

**Pull request merged**
