### PR TITLE
Python 3.6 invalid escape sequence deprecation fixes

### PR DESCRIPTION
**Pull request by scop**
https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior

### CODE REVIEW

**Comment by rogalski** [comment]
If this PR is correct, it seems like [this checker](374b6c1de5b01f07e8ac7a1673b8a0dc5a3b7a43) either needs an update or has a bug.

**Comment by degustaf** [comment]
I can't follow the link you posted, but we have disabled the anomalous-backslash-in-string checker in our pylintrc file.

**Comment by rogalski** [comment]
I guess we should do it before shipping 1.7, just to avoid spurious warnings when running with all warnings enabled.

**Comment by rogalski** [comment]
Thank you!

**Pull request merged**
