### PR TITLE
Don't pin mccabe version

### LINKED ISSUE #932: Pinned mccabe dependency
In f34aac1b83889bdae058a447abbd2bd9a7c1996e, `mccabe ==  0.4.0` got added to `install_requires` of `setup.py` (via `__pkginfo__.py`).

This prevents me from using a newer mccabe (like 0.5.0) which works perfectly fine.

Why was this pinned? IMHO that shouldn't be done in a `setup.py`, see [setup.py vs requirements.txt](https://caremad.io/2013/07/setup-vs-requirement/).

cc @moylop260

### PR DESCRIPTION
**Pull request by The-Compiler**
Fixes #932

### CODE REVIEW

**Comment by moylop260** [comment]
@The-Compiler 

We could have errors by change of version from `mccabe` version and incompatibility in the future.
But I'm open for your proposal.
Then we can merge it and if we have a error in the future we could freeze the mccabe version again.

Note: The travis build has errors unrelated.


👍

**Comment by The-Compiler** [comment]
Agreed - but looking at the [version history](https://pypi.python.org/pypi/mccabe) I think that's quite unlikely, it sees a new minor release once all 6 months or so.

**Comment by moylop260** [comment]
You are right!
I confirme my 👍

**Comment by The-Compiler** [comment]
Merging it then!

**Comment by moylop260** [comment]
Thank you!

**Pull request merged**
