### PR TITLE
Remove base checker total ordering

### LINKED ISSUE #6045: Is `BaseChecker.__gt__` required
### Bug description

As noted by @DanielNoord [here](https://github.com/PyCQA/pylint/pull/5938#discussion_r837867526), [`BaseCheck.__gt__`](https://github.com/PyCQA/pylint/blob/742e60dc07077cdd3338dffc3bb809cd4c27085f/pylint/checkers/base_checker.py#L62-L64) is not currently covered. If this required then we should add a unit test, otherwise we can remove this method.

### Configuration

```ini
N/A
```

### Command used

```shell
N/A
```

### Pylint output

```shell
N/A
```

### Expected behavior

N/A

### Pylint version

```shell
N/A
```

### OS / Environment

_No response_

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by jpy-git**
Closes #6045.

### CODE REVIEW

**Review by Pierre-Sassoulas — DISMISSED** [review]

**Review by DanielNoord — COMMENTED** [review]
Let's add a changelog entry just to be sure. So plugin writers can pick up on this.

**Comment by jpy-git** [comment]
Added the changelog in now 👍

**Review by DanielNoord — APPROVED** [review]

**Comment by jpy-git** [comment]
Interesting, the docs build is failing because I've removed this. Maybe Sphinx is using it to order these classes in the docs?

**Review by Pierre-Sassoulas — COMMENTED** [review]
Hmm, I'm for closing, or adding tests, keeping the ordering does not cost us much and we could break things unexpectedly (on odwnstream lib too). The change is not worth it.

**Comment by jpy-git** [comment]
Agreed 👍

**Pull request closed without merging**
