### PR TITLE
Misc tasks

### PR DESCRIPTION
**Pull request by cdce8p**
## Description
* Move / rename tests for some extensions.
* Add note to `CodeStyleChecker` about what type of checker should be added there, see also: https://github.com/PyCQA/pylint/pull/4538#discussion_r649055922

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
I think any change to the way functional tests are stored need to make sense for all functional tests. Right now each file is in a directory with its first few letters with some exception for mutually-dependent one so it's understandable by looking at it. If we move only some it won't make sense anymore. Maybe we could sort them by checkers like in the code ?

**Comment by cdce8p** [comment]
> Maybe we could sort them by checkers like in the code?

I'm not sure that makes much sense in general. Personally, I'm fine with the current structure. My intention with that change was just to move the fixtures that belong to an extension. To separate them a bit from the other ones, therefor the `ext` subfolder.

> I think any change to the way functional tests are stored need to make sense for all functional tests.

I moved the remaining tests as well. So that it's now consistent again.

**Comment by Pierre-Sassoulas** [comment]
Fair enough, I'm finding my functional tests with a global search for the expected message in ``[]`` anyway.

**Comment by cdce8p** [comment]
I went ahead and added a note for the `consider-using-tuple` checker here. Similar to your comment https://github.com/PyCQA/pylint/pull/4560#discussion_r649482755.
If you're fine with it, this is ready.

**Review by Pierre-Sassoulas — APPROVED** [review]
👍

**Pull request merged**
