### PR TITLE
Fix deprecated methods from #4620

### PR DESCRIPTION
**Pull request by matusvalo**
## Steps

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description

Fixes several issues in #4620:

* Remove duplicates
* Remove SSLSocket methods - the methods cannot be inferred when created by factory SSLContext.wrap_socket
* `ssl.RAND_pseudo_bytes`  -> `_ssl.RAND_pseudo_bytes`

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
|     | :sparkles: New feature |
|     | :hammer: Refactoring   |
|     | :scroll: Docs          |

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
We basically released 2.9.0 just after merging #4620, I hope it's not too problematic, but we can release 2.9.1 fast if it is :)

**Comment by cdce8p** [comment]
@Pierre-Sassoulas We can merge this but lets's just wait and see if we get any bug reports about it before doing a hotfix release. As I understand it, those are only minor things so we might not even get one about it.

**Comment by matusvalo** [comment]
@Pierre-Sassoulas there is still one problem:
Pylint is having problem with `zipimport.zipimporter` not sure why:

```
(pylint38) matus@home:~/dev/pylint$ cat test.py
import zipimport
zipimport.zipimporter('/path/to/zip').load_module()

matus@home:~/dev/pylint$ python test.py                                     # It crashes because of dummy parameters
Traceback (most recent call last):
  File "<frozen zipimport>", line 75, in __init__
  File "<frozen importlib._bootstrap_external>", line 87, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 45, in <module>
    zipimport.zipimporter('/path/to/zip').load_module()
  File "<frozen zipimport>", line 81, in __init__
zipimport.ZipImportError: not a Zip file

(pylint38) matus@home:~/dev/pylint$ pylint test.py
************* Module test
test.py:45:0: E1101: Module 'zipimport' has no 'zipimporter' member (no-member)

----------------------------------------------------------------------
Your code has been rated at -15.00/10 (previous run: -15.00/10, +0.00)
```

pylint is saying that module has no member :-( and skips checking of deprecated method (checked with pdb)

**Comment by matusvalo** [comment]
Doublechecked now, deprecation is not checked due issues with inferrence error in line:
https://github.com/PyCQA/pylint/blob/0f6a38ee54362ae2e4f5f294f26942261d61485e/pylint/checkers/deprecated.py#L63

```
*** astroid.exceptions.InferenceError: Inference failed for <Attribute.zipimporter l.45 at 0x7fec302fe220>.
```

**Comment by Pierre-Sassoulas** [comment]
I think https://github.com/PyCQA/pylint/issues/4631 might be the same problem ?

**Pull request merged**
