### PR TITLE
False positive snake case waring

### PR DESCRIPTION
**Pull request by SergeyKosarchuk**
### Fixes / new features
- Fixed false positive check for invalid name "doesn't conform to snake_case naming style" for class methods and attributes. 

Removed max length in regex for class method and attribute. Tests and docs updated according to [this PR](https://github.com/PyCQA/pylint/pull/2149)

See [#2047](https://github.com/PyCQA/pylint/issues/2047)

### CODE REVIEW

**Comment by PCManticore** [comment]
Hi @SergeyKosarchuk Thank you for submitting a patch!

Would you be so kind in adding a new ChangeLog entry for your change? It should go under a new section as in:
```
What's New in Pylint 2.1?
=========================

Release date: |TBA|

   * Your changelog entry here.
```

Other than that, this PR looks great!

**Comment by SergeyKosarchuk** [comment]
Hi @PCManticore Thank you for help! I have updated ChangeLog.

**Comment by PCManticore** [comment]
Thank you @SergeyKosarchuk for your patch! 🎉

**Comment by Troto** [comment]
Hi, 
Sorry if this is stupid @PCManticore , I'm not that familiar with your branching and releasing.

Is this fix in 2.0.1?

I'm still seeing this issue while using pylint-django and I'm not sure whether to post an issue or it will be in an upcoming version.

Cheers

**Comment by PCManticore** [comment]
This will be available in 2.1, it's not yet released.

**Pull request merged**
