### PR TITLE
Add documentation examples for `redefined-outer-name`

### PR DESCRIPTION
**Pull request by julthep**
Co-authored-by: Vladyslav Krylasov <vladyslav.krylasov@gmail.com>

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description
Add documentation examples for `redefined-outer-name`

Refs #5953

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
I think we need to talk about pytest's fixture in the details.rst, this is a false positive that is really annoying and the message need to be disabled alongside pytest because not using fixtures in pytest makes the code a lot worst. There's probably a related issue too.

**Comment by julthep** [comment]
> I think we need to talk about pytest's fixture in the details.rst, this is a false positive that is really annoying and the message need to be disabled alongside pytest because not using fixtures in pytest makes the code a lot worst. There's probably a related issue too.

I will revert `details.rst` file, where is the information should it refer to?

**Comment by Pierre-Sassoulas** [comment]
> I will revert details.rst file, where is the information should it refer to?

I don't have anything particular in mind but a google search for ``pytest  redefined-outer-name pylint`` will probably return relevant discussions about it

**Comment by Pierre-Sassoulas** [comment]
Closing as inactive and the conflict means it's been done in another MR.

**Pull request closed without merging**
