### PR TITLE
Add regression test for #4982

### LINKED ISSUE #4982: Crash ``maximum recursion depth exceeded`` - something to do with decorators
### Bug description

When parsing the following file:

```python
import verif.sim
```

and `verif/sim.py` is

```python
class foo:
    @classmethod
    def foo(cls):
        return cls.__subclasses__()

bar = foo.foo()

class sim(bar):
    pass
```

pylint crashed with a ``RecursionError`` and with the following stacktrace:

```
Traceback (most recent call last):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1024, in _check_files
    self._check_file(
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1063, in _check_file
    check_astroid_module(ast_node)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1200, in check_astroid_module
    retval = self._check_astroid_module(
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1245, in _check_astroid_module
    walker.walk(ast_node)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 78, in walk
    self.walk(child)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 75, in walk
    callback(astroid)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/pylint/checkers/imports.py", line 510, in visit_import
    imported_module = self._get_imported_module(node, name)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/pylint/checkers/imports.py", line 784, in _get_imported_module
    return importnode.do_import_module(modname)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/mixins.py", line 101, in do_import_module
    return mymodule.import_module(
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 699, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/manager.py", line 206, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/manager.py", line 119, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/builder.py", line 139, in file_build
    return self._post_build(module, encoding)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/builder.py", line 167, in _post_build
    module = self._manager.visit_transforms(module)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/manager.py", line 96, in visit_transforms
    return self._transform.visit(node)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/transforms.py", line 96, in visit
    return self._visit(module)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/transforms.py", line 61, in _visit
    visited = self._visit_generic(value)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/transforms.py", line 68, in _visit_generic
    return [self._visit_generic(child) for child in node]
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/transforms.py", line 68, in <listcomp>
    return [self._visit_generic(child) for child in node]
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/transforms.py", line 74, in _visit_generic
    return self._visit(node)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/transforms.py", line 64, in _visit
    return self._transform(node)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/transforms.py", line 45, in _transform
    if predicate is None or predicate(node):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/brain/brain_namedtuple_enum.py", line 554, in _is_enum_subclass
    for klass in cls.mro()
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 3030, in mro
    return self._compute_mro(context=context)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 2999, in _compute_mro
    inferred_bases = list(self._inferred_bases(context=context))
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 2982, in _inferred_bases
    baseobj = next(
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 2982, in <genexpr>
    baseobj = next(
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/bases.py", line 154, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/bases.py", line 154, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/inference.py", line 244, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 1806, in infer_call_result
    yield from returnnode.value.infer(context)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/inference.py", line 235, in infer_call
    for callee in self.func.infer(context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/inference.py", line 318, in infer_attribute
    yield from owner.igetattr(self.attrname, context)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 2606, in igetattr
    attributes = self.getattr(name, context, class_context=class_context)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 2523, in getattr
    result = [self.special_attributes.lookup(name)]
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/interpreter/objectmodel.py", line 126, in lookup
    return getattr(self, IMPL_PREFIX + name)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/interpreter/objectmodel.py", line 485, in attr___subclasses__
    classes = [
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/interpreter/objectmodel.py", line 488, in <listcomp>
    if cls != self._instance and cls.is_subtype_of(qname)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 2203, in is_subtype_of
    for anc in self.ancestors(context=context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 2362, in ancestors
    for baseobj in stmt.infer(context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/bases.py", line 154, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/bases.py", line 154, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/inference.py", line 244, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 1806, in infer_call_result
    yield from returnnode.value.infer(context)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/inference.py", line 235, in infer_call
    for callee in self.func.infer(context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/inference.py", line 318, in infer_attribute
    yield from owner.igetattr(self.attrname, context)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 2606, in igetattr
    attributes = self.getattr(name, context, class_context=class_context)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 2523, in getattr
    result = [self.special_attributes.lookup(name)]
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/interpreter/objectmodel.py", line 126, in lookup
    return getattr(self, IMPL_PREFIX + name)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/interpreter/objectmodel.py", line 485, in attr___subclasses__
    classes = [
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/interpreter/objectmodel.py", line 488, in <listcomp>
    if cls != self._instance and cls.is_subtype_of(qname)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 2203, in is_subtype_of
    for anc in self.ancestors(context=context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/scoped_nodes.py", line 2362, in ancestors
    for baseobj in stmt.infer(context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/bases.py", line 154, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 129, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/decorators.py", line 98, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/bases.py", line 154, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/home/ap/python/site/3.8.7/20210903/lib/python3.8/site-packages/astroid/nodes/node_ng.py", line 113, in infer
    for i, result in enumerate(generator):
...
```

### Command used

```shell
pylint test.py
```

### Pylint output

```shell
See above.
```

### Expected behavior

It shouldn't crash.

### Pylint version

```shell
pylint 2.10.2
astroid 2.7.3
Python 3.8.7 (default, Jan  9 2021, 01:55:12) 
[Clang 9.0.0 (tags/RELEASE_900/final)]
```

### OS / Environment

CentOS Linux release 7.9.2009 (Core)

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Adds a test for #4982, fixed in https://github.com/PyCQA/astroid/pull/1257.
Therefore, closes #4982

@Pierre-Sassoulas Do you want to wait with this for `2.13`? I haven't added a changelog entry because I wanted to know which release you want to put this in. We could also potentially do `2.12.x`, we just need the fix to be available in a released `astroid` version.

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
> @Pierre-Sassoulas Do you want to wait with this for 2.13? 

Seems like PyCQA/astroid#1257. is scheduled for astroid 2.8.6 so we should have it for pylint 2.12

**Comment by DanielNoord** [comment]
Yeah, because it is a minor change and fixes a crash I thought `2.8.6` would fit well. We could obviously postpone!

**Comment by cdce8p** [comment]
@DanielNoord Could you update this one? I got a `permission denied` error when I tried to push to your branch. (Did you unselect `Allow edits and access to secrets by maintainers`?)

**Comment by DanielNoord** [comment]
You should have access. I have not unchecked it. I'll update the branch!

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by cdce8p** [comment]
> You should have access. I have not unchecked it. I'll update the branch!

I might need to check my setup then 🤷🏻‍♂️ Thanks for updating it.

**Pull request merged**
