### PR TITLE
Add regression tests for Enum.name and .value inference

### LINKED ISSUE #1932: pylint has issues with IntEnum.name type detection
```py
# test.py
from enum import IntEnum


class MyEnum(IntEnum):
    FOO = 1

    def whats_my_name(self):
        return self.name.lower()


print(MyEnum.FOO.whats_my_name())
```

### Steps to reproduce
1.  `pylint -dC test.py` with the file above

Output:
```
E:  8,15: Method 'name' has no 'lower' member (no-member)
```

### pylint --version output
pylint 1.8.2, 
astroid 1.6.1
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224]

### LINKED ISSUE #2062: Enum: Method 'name' has no 'lower' member (no-member)
### Steps to reproduce
```py
#! python3

from enum import Enum

class MyEnum(Enum):
    FOO = 1
    BAR = 2

    def __str__(self):
        return self.name.lower()

```

Run `pylint` on the file above.

### Current behavior
`E: 10,15: Method 'name' has no 'lower' member (no-member)`

### Expected behavior
No error. Enums have `name` propery which contains a string.

### pylint --version output
```
$ pylint --version
No config file found, using default configuration
pylint 1.8.4, 
astroid 1.6.3
Python 3.4.6 (default, Mar 22 2017, 12:26:13) [GCC]
```

### PR DESCRIPTION
**Pull request by nelfin**
## Steps

- [ ] ~Add yourself to CONTRIBUTORS if you are a new contributor.~
- [X] Add a ChangeLog entry describing what your PR does.
- [ ] ~If it's a new feature or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.~
- [X] Write a good description on what the PR does.

## Description

Captures the regression tests specified in #1932 and #2062 and fixed by PyCQA/astroid#1020.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Related Issue

Closes #1932. Closes #2062. Depends on PyCQA/astroid#1020.

### CODE REVIEW

**Comment by cdce8p** [comment]
@nelfin Feel free to add `Closes #...` to the PR description. Otherwise the issues will stay open, probably forever.
Could you add a small note to the ChangeLog? I imagine not many will read the one for `astroid`.

Lastly, I saw by accident that #2306 appears to be fixed as well, at least for Python < 3.10. Something changed of for **3.10** though.

**Comment by nelfin** [comment]
> @nelfin Feel free to add `Closes #...` to the PR description. Otherwise the issues will stay open, probably forever.

This PR doesn't actually fix those issues though?

> Could you add a small note to the ChangeLog? I imagine not many will read the one for `astroid`.

Sure.

> Lastly, I saw by accident that #2306 appears to be fixed as well, at least for Python < 3.10. Something changed of for **3.10** though.

The implementation of 'enum.Enum' changed in 3.10 away from just a plain `DynamicClassAttribute`. I guess I can take a look at what it takes to get that test to pass.

**Comment by cdce8p** [comment]
> > @nelfin Feel free to add `Closes #...` to the PR description. Otherwise the issues will stay open, probably forever.
> 
> This PR doesn't actually fix those issues though?

I thought it did. If you meant that https://github.com/PyCQA/astroid/pull/1020 actually fixed it, that is no problem. I frequently use `Closes ...` only for the last PR in pylint. As long as they are related.

> > Could you add a small note to the ChangeLog? I imagine not many will read the one for `astroid`.
> 
> Sure.
> 
> > Lastly, I saw by accident that #2306 appears to be fixed as well, at least for Python < 3.10. Something changed of for **3.10** though.
> 
> The implementation of `enum.Enum` changed in 3.10 away from just a plain `DynamicClassAttribute`. I guess I can take a look at what it takes to get that test to pass.

Thanks 👍🏻

**Comment by nelfin** [comment]
> I thought it did. If you meant that [PyCQA/astroid#1020](https://github.com/PyCQA/astroid/pull/1020) actually fixed it, that is no problem.

That is what I meant. I've updated the description.

**Review by Pierre-Sassoulas — APPROVED** [review]
👍

**Comment by cdce8p** [comment]
@nelfin Thanks for fixing the issue with 3.10! Would you mind adding the regression test for it here? Just so we don't lose it

**Comment by nelfin** [comment]
@cdce8p, do you mean this regression test: #4570? I opened that one when I pushed up the fix, but I can squash that PR into this one if that's your preference.

**Comment by cdce8p** [comment]
> @cdce8p, do you mean this regression test: #4570? I opened that one when I pushed up the fix, but I can squash that PR into this one if that's your preference.

That works as well! Didn't saw it before.

**Pull request merged**
