### PR TITLE
Add new checks ``use-set-literal`` and ``use-tuple-literal`` and improve ``use-list-literal`` and ``use-dict-literal``

### LINKED ISSUE #6542: New checks: Use literals instead of calling the constructor
### Current problem

Literals should be prioritized over calling their respective constructors because it is clearer. 
Demonstrations of new checks:
```py
"""Incorrect Code"""
mylist = list((1, 2, 3, 4, 5))  # [use-list-literal]
mytuple = tuple()  # [use-tuple-literal]
mytuple2 = tuple(['foo', 'bar'])  # [use-tuple-literal]
mydict = dict((('a', 1), ('b', 2)))  # [use-dict-literal]
myset = set(['py', 'lint'])  # [use-set-literal]
```
Should be (Correct code):
```py
"""Correct Code"""
mylist = [1, 2, 3, 4, 5] 
mytuple = ()
mytuple2 = ('foo', 'bar')
mydict = {'a': 1, 'b': 2}
myset = {'py', 'lint'}
```
For both of the above pylint gives a rating of 10.0/10.0.

### Desired solution

I propose a couple new checks, or they could all be merged into a `use-literal` instead.
The list example and dict example should be part of [`use-list-literal`](https://pylint.pycqa.org/en/latest/messages/refactor/use-list-literal.html) and [`use-dict-literal`](https://pylint.pycqa.org/en/latest/messages/refactor/use-dict-literal.html), and the set and tuple examples could be `use-set-literal` and `use-tuple-literal`. I can see some argument against the tuple literal, as it could be confusing in some parentheses-dense situations, but the other checks would almost always (if not always) make things clearer.

### Additional context

Similar to issue [#4365](https://github.com/PyCQA/pylint/issues/4365) but for `set`, `tuple`, and more complicated expressions.

### PR DESCRIPTION
**Pull request by Sawbez**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|       | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
|       | :hammer: Refactoring   |
|       | :scroll: Docs          |

## Description

Adds ``use-tuple-literal`` and ``use-set-literal`` checkers, reference: https://github.com/PyCQA/pylint/issues/6542.

This adds two new checks for creating tuples and (non-empty) sets from constants using the constructor instead of
using their respective literals.

Updates ``use-list-literal`` and ``use-dict-literal`` checkers

These two checks have been updated to work with constant arguments passed to them, with ``use-dict-literal``
also now supporting constant ``kwargs``

Closes #6542

### CODE REVIEW

**Comment by Sawbez** [comment]
I'll try and fix the ``pytest`` checks later, but I don't have time right now.

**Comment by Sawbez** [comment]
Alright, the functional tests are fixed, but ``pylint`` is still going to give errors.

**Comment by Sawbez** [comment]
Perhaps there should be another check for the length of the sequence/mapping if it was a literal, because lengths that are too large become annoying to maintain.

**Comment by Sawbez** [comment]
Still working on this -- busy with school

**Comment by DanielNoord** [comment]
> Still working on this -- busy with school

Let us know if we can help with anything!

That said, if it isn't too much trouble it would be very helpful if you could split some of the changes into different PRs. Perhaps by doing a PR for each new check? Limiting the size of a PR helps a lot with the review process and makes it much easier to merge stuff!

**Comment by Pierre-Sassoulas** [comment]
Closing as the branch we were based upon was deleted entirely.

**Pull request closed without merging**
