### PR TITLE
Add `--color-palette` option to `pyreverse`

### LINKED ISSUE #6738: Custom colour palettes for `pyreverse`
### Current problem

See [this SO question](https://stackoverflow.com/questions/72294217/pyreverse-uml-diagram-with-customized-color): 
The `--colorized` option uses a fixed colour palette. 
If one wants to use other colours, (s)he has to use a text-based output format and do a search-and-replace.

### Desired solution

As the colour palette is just a simple list of strings inside `pylint.pyreverse.writer.DiagramWriter` it should be possible to make this configurable.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DudeNr33**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |

## Description

* Add support for user-defined color palettes
* Use a new default color palette, that is (hopefully) more visually pleasing and more accessible for color blind people. This palette is pretty close to what `seaborn` uses in their colorblind palette (see [here](https://seaborn.pydata.org/tutorial/color_palettes.html#qualitative-color-palettes))

The new default colors look like this:
image

Closes #6738

### CODE REVIEW

**Review by nickdrozd — DISMISSED** [review]
Defaults looks great. Tested input color flag; works. :art:

**Review by Pierre-Sassoulas — COMMENTED** [review]
Maybe we should keep what we had because it's a kind of breaking change. I'm so not the person to tell you if the default color palette looks good or not... But now that it can be user defined then it's fine, user can change it *to taste* :)

**Comment by nickdrozd** [comment]
> Maybe we should keep what we had because it's a kind of breaking change. I'm so not the person to tell you if the default color palette looks good or not... But now that it can be user defined then it's fine, user can change it _to taste_ :)

By that same logic, anyone who just has to have _alice blue_ and _antique white_ is also free to specify them! But somehow I have the feeling that few will actually choose those colors :laughing:

**Comment by Pierre-Sassoulas** [comment]
You'd be surprised, people get accustomed to thing and if it changes there's always someone complaining.  https://imgs.xkcd.com/comics/workflow.png

**Comment by DudeNr33** [comment]
I don't have a strong opinion on changing the default colors.
We can leave them as they are, and change them in 3.0.

**Review by Pierre-Sassoulas — DISMISSED** [review]
I'd prefer to minimize churn but I'm also ok if @nickdrozd feels strongly about changing the default :)

**Comment by DudeNr33** [comment]
I will leave it as it is currently (i.e. stick with the previous default colors and leave the TODO to switch for 3.0) and will take care of the spelling errors this evening.
Trying to install `enchant` yesterday resulted in a downwards spiral that made me update macOS. Sometimes you gotta love being a developer... 😅

**Comment by Pierre-Sassoulas** [comment]
> Trying to install enchant yesterday resulted in a downwards spiral that made me update macOS. Sometimes you gotta love being a developer... 

https://www.youtube.com/watch?v=AbSehcT19u0

**Comment by nickdrozd** [comment]
Sure, the default colors could be changed later, as part of the wider push for sane defaults. But they really should be changed. It's not just my opinion that default colors are bad; the [SO post](https://stackoverflow.com/questions/72294217/pyreverse-uml-diagram-with-customized-color) that prompted the color issue specifically mentions wanting to change the "faint blue color" to a darker one.

And it's not just about opinions. The new proposed colors are objectively better in terms of accessibility than the current defaults. Actually, the ugliness and the inaccessibility have the same root cause, which is that *alice blue* and *antique white* are both difficult to distinguish from each other and difficult to distinguish from a white background.

As an example, here is a package diagram generated by Pyreverse with the current colors:

packages

**Review by Pierre-Sassoulas — APPROVED** [review]

**Pull request merged**
