### PR TITLE
Document a better release process

### LINKED ISSUE #4701: Document a better release process than the current one
See #4651

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Follow-up to #5877. This document the new git flow, based on review for https://github.com/PyCQA/astroid/pull/1438

Closes #4701

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
> We should probably split the Copyright change into its own PR and commit, that's not really part of the release process

Yes there is 3 different things here, I've been lazy :) I'm going to open other PR.

**Comment by Pierre-Sassoulas** [comment]
Blocked because we're going to merge the PR in astroid first and do the same change here after that.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas To make this a little easier, shall we just copy the one from `astroid`? I don't think there is that much that is specific to `astroid` right?

**Comment by Pierre-Sassoulas** [comment]
Yes, I'm going to do that :) I'm doing #5877 first and catching up with other MR

**Comment by Pierre-Sassoulas** [comment]
@DanielNoord this is the same process than in astroid with the following modification : [aa51220](https://github.com/PyCQA/pylint/pull/5858/commits/aa5122090270108d2906b2f5cfe4a82744ef8f71)

**Review by DanielNoord — APPROVED** [review]

**Pull request merged**
