### PR TITLE
Add generic alias test cases

### PR DESCRIPTION
**Pull request by cdce8p**
## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description
Add new test cases for `generic_alias` to make validating any updates a bit easier.
At the moment, some errors are still undetected that should be recognized.

**Related**
#4206
https://github.com/PyCQA/astroid/pull/921

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
| ✓  | :sparkles: New feature |

### CODE REVIEW

**Comment by cdce8p** [comment]
These are the current `non-detected` errors, no false positives.

```
pytest tests/test_functional.py -k generic_alias
```

**Python 3.8**
```
test_functional[generic_alias_typing]
E       Expected in testdata:
E         66: unsubscriptable-object  # typing.ByteString[int]
E         67: unsubscriptable-object  # typing.Hashable[int]
E         68: unsubscriptable-object  # typing.Sized[int]
E        122: unsubscriptable-object  # var_bytestring2: typing.ByteString[int]
E        123: unsubscriptable-object  # var_hashable2: typing.Hashable[int]
E        124: unsubscriptable-object  # var_sized2: typing.Sized[int]

test_functional[generic_alias_postponed_evaluation_py37]
E       Expected in testdata:
E         67: unsubscriptable-object  # re.Pattern[str]
E         68: unsubscriptable-object  # re.Match[str]
E         85: abstract-method  # Derived -> Iterable
E         88: abstract-method  # Derived -> Collection
E        109: abstract-method  # Derived -> Sized, Iterable
E        111: abstract-method  # Derived -> Multiple

test_functional[generic_alias_collections_py37]
E       Expected in testdata:
E         62: unsubscriptable-object  # re.Pattern[str]
E         63: unsubscriptable-object  # re.Match[str]
E         80: abstract-method  # Derived -> Iterable
E         83: abstract-method  # Derived -> Collection
E        104: abstract-method  # Derived -> Sized, Iterable
E        106: abstract-method  # Derived -> Multiple
E        119: unsubscriptable-object  # var_pattern: re.Pattern[int]
```

**Python 3.9**
```
test_functional[generic_alias_typing]
E       Expected in testdata:
E         66: unsubscriptable-object  # typing.ByteString[int]
E         67: unsubscriptable-object  # typing.Hashable[int]
E         68: unsubscriptable-object  # typing.Sized[int]
E        122: unsubscriptable-object  # var_bytestring2: typing.ByteString[int]
E        123: unsubscriptable-object  # var_hashable2: typing.Hashable[int]
E        124: unsubscriptable-object  # var_sized2: typing.Sized[int]

test_functional[generic_alias_collections]
E       Expected in testdata:
E         77: abstract-method  # Derived -> Iterable
E         80: abstract-method  # Derived -> Collection
E        101: abstract-method  # Derived -> Sized, Iterable
E        103: abstract-method  # Derived -> Multiple
```

**Comment by Pierre-Sassoulas** [comment]
Very nice ! We clearly lacked tests for python 3.9.

**Comment by cdce8p** [comment]
It isn't as bad as it might seem! TBH it's a small miracle that there aren't more.

I frequently get confused what works in which version and in what setting (assignment, type annotation, with or without postponed evaluation). These tests should help with that and make it at least a bit easier. Always assuming that there isn't a bug in there as well 😅 

This was one of the reasons I started working on the pylint support. If pylint is able to detect the errors, it should help a lot of devs who use typing, especially until **3.10** is the default.

**Comment by hippo91** [comment]
@cdce8p very nice job! It is a great help for setting up astroid's typing and collection brain!

**Comment by cdce8p** [comment]
All tests pass, finally!
`pytest -m acceptance -k "test_libmodule[typing.py]"` works as well.

**Review by Pierre-Sassoulas — APPROVED** [review]
This is VERY satisfying. Wow 😄

**Comment by cdce8p** [comment]
🎉 🥳

**Comment by hippo91** [comment]
Very nice job @cdce8p ! Congrats!

**Pull request merged**
