### PR TITLE
Added message doc for assigning-non-slot

### PR DESCRIPTION
**Pull request by matusvalo**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|     | :bug: Bug fix          |
|     | :sparkles: New feature |
|     | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Closes partially  #5953

### CODE REVIEW

**Comment by matusvalo** [comment]
Not sure if I need to add also record to changelog.

**Review by DanielNoord — APPROVED** [review]

**Comment by DanielNoord** [comment]
A changelog entry is not necessary, I'll update the guide in the issue.

Thanks @matusvalo! That's the first contribution to this process from anybody other than myself 😄

**Comment by matusvalo** [comment]
> That's the first contribution to this process from anybody other than myself 😄

I plan to allocate some time to this effort and migrate  more docs.

**Comment by DanielNoord** [comment]
That's wonderful! Let me know if I can help out with anything!

**Review by Pierre-Sassoulas — APPROVED** [review]
Great to see that this is getting some traction ❤️ (and the example is nice and understandable)

**Comment by Pierre-Sassoulas** [comment]
I'm putting this in 2.14 for easier managment pupuse as cherry-picking in the maintenance branch take time, but this is going to be available in our documentation as soon as it's merged on main.

**Pull request merged**
