### PR TITLE
Use 3.10 for Github actions

### PR DESCRIPTION
**Pull request by cdce8p**
## Description

Replace `3.10-dev` with `3.10` in Github actions.

Astroid PR: https://github.com/PyCQA/astroid/pull/1198

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
I was going to do that for astroid but my clone is broken locally, this is hard to fix. Anyway, I was going to try using ``3.11-dev`` to see if it's possible yet. Maybe you read the documentation and know it's not ?

**Comment by cdce8p** [comment]
> I was going to do that for astroid but my clone is broken locally, this is hard to fix. Anyway, I was going to try using `3.11-dev` to see if it's possible yet. Maybe you read the documentation and know it's not ?

There haven't been any releases for `3.11` yet. We will need to wait for the first alpha for that.
The tags are for releases in this repo here: https://github.com/actions/python-versions/releases
(You can select to watch only the releases if you like. Quite helpful to know when a new Python version is available.)

**Comment by cdce8p** [comment]
@Pierre-Sassoulas Could you update the required status checks. The names will change a bit. You can also merge this PR, it's ready.

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
> (You can select to watch only the releases if you like. Quite helpful to know when a new Python version is available.)

This is great ! Thanks !

**Pull request merged**
