### PR TITLE
Fix issue #5969 for `modified_iterating-list`

### LINKED ISSUE #5969: 2.13 crashed with AttributeError: 'Call' object has no attribute 'name'
### Bug description

I got the following traceback from [the project CI](https://github.com/diofant/diofant/runs/5686472054?check_suite_focus=true):
```

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 73, in walk
    callback(astroid)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 61, in visit_for
    self._modified_iterating_check_on_node_and_children(body_node, iter_obj)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 69, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check_on_node_and_children(child, iter_obj)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 69, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check_on_node_and_children(child, iter_obj)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 67, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check(body_node, iter_obj)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 75, in _modified_iterating_check
    if self._modified_iterating_list_cond(node, iter_obj):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 124, in _modified_iterating_list_cond
    self._common_cond_list_set(node, iter_obj, infer_val)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 105, in _common_cond_list_set
    node.value.func.expr.name == iter_obj.name
AttributeError: 'Call' object has no attribute 'name'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/lint/parallel.py", line 80, in _worker_check_single_file
    _worker_linter.check_single_file_item(file_item)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1100, in check_single_file_item
    self._check_file(self.get_ast, check_astroid_module, file)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1146, in _check_file
    check_astroid_module(ast_node)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1298, in check_astroid_module
    retval = self._check_astroid_module(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1345, in _check_astroid_module
    walker.walk(node)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 76, in walk
    self.walk(child)
  [Previous line repeated 1 more time]
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 73, in walk
    callback(astroid)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 61, in visit_for
    self._modified_iterating_check_on_node_and_children(body_node, iter_obj)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 69, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check_on_node_and_children(child, iter_obj)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 69, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check_on_node_and_children(child, iter_obj)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 67, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check(body_node, iter_obj)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 75, in _modified_iterating_check
    if self._modified_iterating_list_cond(node, iter_obj):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 124, in _modified_iterating_list_cond
    self._common_cond_list_set(node, iter_obj, infer_val)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/checkers/modified_iterating_checker.py", line 105, in _common_cond_list_set
    node.value.func.expr.name == iter_obj.name
AttributeError: 'Call' object has no attribute 'name'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/lint/run.py", line 358, in __init__
    linter.check(args)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 1077, in check
    check_parallel(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/pylint/lint/parallel.py", line 157, in check_parallel
    for (
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/multiprocessing/pool.py", line 870, in next
    raise value
AttributeError: 'Call' object has no attribute 'name'
```

### Configuration

```ini
See pyproject.toml in the Diofant repo
```

### Command used

```shell
pylint diofant
```

### Pylint output

```shell
Traceback (see above)
```

### Expected behavior

No crash

### Pylint version

```shell
pylint 2.13.0
astroid 2.11.1
CPython 3.10.2
```

### OS / Environment

_No response_

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by orSolocate**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
|   | :sparkles: New feature |
|   | :hammer: Refactoring   |
|   | :scroll: Docs          |

## Description
Fix program crash for `modified_iterating-list` when the list being iterated through is a function call.
The bug was fixed so that it will not occur with dictionaries and sets as well.
A regression test was added too.

Closes #5969

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
Thank you for the quick fix @orSolocate, we're going to release 2.13.1 shortly :)

**Comment by Pierre-Sassoulas** [comment]
What do you think of the line that lost coverage as ``infer_val != utils.safe_infer(iter_obj):`` seems to be always false ? Can we remove this check following your change ?

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  thanks for noticing that letting me know what the line was,
It shouldn't be removed. I added a new test case where this line is covered :D

**Comment by Pierre-Sassoulas** [comment]
This is released in 2.13.1 :) btw if you want to check the coverage details on coverall you need to login with your GitHub account: coveralls use it to not get rate limited for api calls.

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  - thanks for merging man! and for for the coveralls tip, now I could see coverage details of my next uploads :)

**Comment by DanielNoord** [comment]
Just want to check in and say thanks @orSolocate for the quick turnaround here :)

**Comment by orSolocate** [comment]
Thanks mate!

**Pull request merged**
