### PR TITLE
``redefined-slots-in-subclass`` crash when slot type is neither a string or constant node

### LINKED ISSUE #6100: "AttributeError: 'ClassDef' object has no attribute 'value'" in _check_redefined_slots
### Bug description

I'm seeing this exception when a `__slot__` is set to a list of enum values, but was able to reproduce minimally with just using a type as the list:
```python
class MyClass:
    __slots__ = [str]
```

### Configuration

_No response_

### Command used

```shell
pylint test.py
```

### Pylint output

```shell
Exception on node <ClassDef.MyClass l.1 at 0x7fe9152603d0> in file 'test.py'
Traceback (most recent call last):
  File "/Users/me/.virtualenvs/myvirtualenv/lib/python3.8/site-packages/pylint/utils/ast_walker.py", line 73, in walk
    callback(astroid)
  File "/Users/me/.virtualenvs/myvirtualenv/lib/python3.8/site-packages/pylint/checkers/classes/class_checker.py", line 804, in visit_classdef
    self._check_slots(node)
  File "/Users/me/.virtualenvs/myvirtualenv/lib/python3.8/site-packages/pylint/checkers/classes/class_checker.py", line 1369, in _check_slots
    self._check_redefined_slots(node, slots, values)
  File "/Users/me/.virtualenvs/myvirtualenv/lib/python3.8/site-packages/pylint/checkers/classes/class_checker.py", line 1385, in _check_redefined_slots
    slots_names.append(inferred_slot.value)
AttributeError: 'ClassDef' object has no attribute 'value'
************* Module box.sync.core.test
F0001(fatal):  1,0: : Fatal error while checking 'test.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/Users/me/Library/Caches/pylint/pylint-crash-2022-04-01-11.txt'.
```

### Expected behavior

pylint not crash.

### Pylint version

```shell
pylint 2.13.4
astroid 2.11.2
```

### OS / Environment

Python 3.8.8
macOS 11.6.4

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by mbyrnepr2**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
|    | :scroll: Docs          |

## Description

Closes #6100

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
LGTM, thank you @mbyrnepr2 Just waiting for the tests to run

**Review by DanielNoord — APPROVED** [review]

**Comment by mbyrnepr2** [comment]
Thanks @Pierre-Sassoulas the suppression of the other message in the tests needs a tweak.

**Comment by Pierre-Sassoulas** [comment]
Is it merge-able @mbyrnepr2, I saw it was still a draft ?

**Comment by mbyrnepr2** [comment]
> Is it merge-able @mbyrnepr2, I saw it was still a draft ?

Sorry should have pinged you; it is mergeable @Pierre-Sassoulas!

**Comment by Pierre-Sassoulas** [comment]
Thank you for yet another fix !

**Pull request merged**
