### PR TITLE
Add unimport to pre commit configuration

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Description

Add unimport to pre-commit in order to fix unused import automatically.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature |

### CODE REVIEW

**Comment by graingert** [comment]
any reason for not using `autoflake --remove-all-unused-imports` ?

**Comment by Pierre-Sassoulas** [comment]
@graingert I did not know about it :)  Are you using it yourself ?  Apparently it also removes unused variables so  guess it would be a bonus.

**Comment by graingert** [comment]
I use it, only because it's the first search result hit for "Python unused imports"

I've only used it once per codebase when adding lint tools, as from then on I rely on flake8 W402

**Comment by Pierre-Sassoulas** [comment]
Closed because autoflake seems more mature, will be added in #3851

**Pull request closed without merging**
