### PR TITLE
Remove all placeholder files

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to ``CONTRIBUTORS.txt`` if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

### CODE REVIEW

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas I should have tested this but the assertion you added doesn't actually work. The placeholder text isn't in the string that is being asserted anyway.

Let's remove all those files just to be sure they don't stay around.

**Comment by Pierre-Sassoulas** [comment]
It's very efficient to know what still need to be done (I'm so sick of updating #5953 all the time.) and thanks to it contributor do not need to create the directory and good.py which prevent errors and is nice. How about fixing the assert ? I also thougth about creating a script to generate #5953's updated description.

**Comment by DanielNoord** [comment]
> It's very efficient to know what still need to be done (I'm so sick of updating #5953 all the time.) and thanks to it contributor do not need to create the directory and good.py which prevent errors and is nice. How about fixing the assert ? I also thougth about creating a script to generate #5953's updated description.

I was just going to update #5953. I'll do that once a month or something.

Fixing the assert is a bit annoying as the strings we return have the `literalinclude` directive instead of the actual text.

I'd prefer to remove these files as they can only be forgotten. I'll make sure to update #5953 a little more often.

**Comment by Pierre-Sassoulas** [comment]
There's also the fact that it's advertisement in our documentation for the issue when someone search for it. What's wrong with having to check that they don't stay around in 6 months when most of the messages are done and there's very few of those file anyway ?

**Comment by DanielNoord** [comment]
> There's also the fact that it's advertisement in our documentation for the issue when someone search for it. What's wrong with having to check that they don't stay around in 6 months when most of the messages are done and there's very few of those file anyway ?

Okay but then the assertion should be fixed. Could you look into that? As of now it doesn't do much.

**Comment by Pierre-Sassoulas** [comment]
Let me check the assertion. (One reason to keep it is also to have something telling someone reading the doc that not having an explanation is not "normal" and that we're going to get better maybe with their help. Otherwise we just have an empty page, which feel "not helpful" and "the only thing I'm supposed to get").

**Comment by Pierre-Sassoulas** [comment]
Did some investigation, the assert was broken yesterday in https://github.com/PyCQA/pylint/commit/beb8b6f921057aeea0631d9440bb7acd7f8603bc#diff-c451abc3b7961e84318d215e0b2f2e12860a4f416ff70df520674bbf83b28927R109

**Pull request closed without merging**
