### PR TITLE
add uplint.bat script to easily reinstall package

### PR DESCRIPTION
**Pull request by orSolocate**
## Steps

- [X] Add yourself to CONTRIBUTORS if you are a new contributor.
- [X] Add a ChangeLog entry describing what your PR does.
- [X] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [X] Write a good description on what the PR does.

## Description
A simple but smart script that will help Pylint developers to reinstall Pylint package after adding changes to the repository and testing it. The script reinstalls Pylint on current location, this is why I put the script under the root dir. When you have many repositories cloned and you want to update Pylint to one of them, just `cd` to its root dir and run `uplint`. simple as that.

## Type of Changes

|   | Type |
| ------------- | ------------- |
|  | :bug: Bug fix  |
| ✓  | :sparkles: New feature |
|  | :hammer: Refactoring  |
| ✓  | :scroll: Docs |

## Related Issue
N\A

### CODE REVIEW

**Comment by orSolocate** [comment]
@hippo91  Would you be interested in such script in Astroid too?

**Comment by orSolocate** [comment]
P.S I added documentation for it on the contribution page so that people would be actually aware of the script and will start use it and save developing time.

**Comment by Pierre-Sassoulas** [comment]
Isn't it possible to use pip3 editable installation instead ? `pip3 install -e ../..../pylint/`

**Comment by orSolocate** [comment]
@Pierre-Sassoulas  this command is right too. but its purpose is different. the -e flag as far as I understood is used for implicit update of your installed repo on every change you make. 
I know that -e can be a hassle when you want to uninstall the package when it is in editable mode  [S.O.](https://stackoverflow.com/questions/35064426/when-would-the-e-editable-option-be-useful-with-pip-install).


My script becomes convenient when you have 2 cloned repos. 
for example:
1 -  for pylint checked out to master branch
2 - pylint checked out to your local branch (say with a new checker)

You want to check that pylint does not find the new error in the master branch, but with your new checker it does. so you want to  move between versions quickly.
with my script you just:
1. `cd` to repo with master branch
2.  `uplint` 
3.  run pylint
4. `cd` to other repo
5. `uplint`
6. run pylint

if you want to save more time people can themselves edit my script with  batch input "flags" where each flag points to the version they want to install.

**Comment by Pierre-Sassoulas** [comment]
The way I see it if you have multiple cloned repositories, you should use only one repository and git branch instead. You install pylint from the pylint's git repository with `pip install -e ../pylint/` and then just use `git switch`  to change between branches. This works cross platforms, and you only have one repository to manage which imho is easier than multiple clone especially because in your IDE you don't have to switch either.

**Comment by Pierre-Sassoulas** [comment]
Sorry I'm going to close as it's OS specific for Windows and it seems that using git branches would be sufficient, so it's not going to be used a lot.

**Comment by orSolocate** [comment]
@Pierre-Sassoulas Okay no worries! Thanks for the discussion.

**Pull request closed without merging**
