### PR TITLE
[FIX] deprecated-module: Detected with -d all -e deprecated-module

### PR DESCRIPTION
**Pull request by moylop260**
### Fixes / new features
- Fix https://github.com/PyCQA/pylint/issues/953

### CODE REVIEW

**Comment by moylop260** [comment]
This pr os ready to merge/feedback

The red of travis is unrelated

**Comment by PCManticore** [comment]
I know it is ready, I just don't look too closely in the weekend. If it is a fresh one ( <7 days), there is no reason to ping it repeatedly, unless it is a fix that should land fast.

**Comment by moylop260** [comment]
I don't understood your last comment.
Where I ping repeatedly?

1. I make the first PR but with real error.
2. After that I created my last commit fixing it.
3. Now is seudo-green and I added a message of a false red.

The other messages are from coveralls.
(This message are annoying for me too)

You can disable with the following option:
leave comments

Otherwise you can add your [contribute](https://github.com/PyCQA/pylint/blob/master/doc/contribute.rst) rule in order to avoid discuss by each PR by each contributor.

Thanks for your great work!

**Comment by PCManticore** [comment]
I'm talking about https://github.com/PyCQA/pylint/pull/954#issuecomment-228609603 and other similar comments made in the past PRs (https://github.com/PyCQA/pylint/pull/879#issuecomment-213240894 and https://github.com/PyCQA/pylint/pull/879#issuecomment-214474314 for example). If it takes more time for me to come with a feedback, then it makes sense to ping me, but a couple of days difference is not that big. I'll add some notes about it in the contribute section.

I like the messages from coveralls, they are a nice way to notice if coverage goes down or not.

**Pull request merged**
