### PR TITLE
Add new extension for detecting integer comparisons against zero

### PR DESCRIPTION
**Pull request by atodorov**
Similar to #1183 but for comparisons to zero. Again made it as an extension because this may not be what you need. I've used this to refactor a great deal of projects I've been working on though where such comparisons are not needed and expand the size of mutation test matrix in the order of 1000s of additional cases.

Please review and comment, thanks.

### CODE REVIEW

**Comment by PCManticore** [comment]
Thank you, looks nice and clean.

By the way, we are using pytest since some recent changes. Can you modify your code so that it won't complain about ``WC1 /home/travis/build/PyCQA/pylint/.tox/py35/lib/python3.5/site-packages/pylint/test/extensions/test_comparetozero.py cannot collect test class 'TestReporter' because it has a __init__ constructor``? Thank you.

**Comment by atodorov** [comment]
PR updated for the pytest error listed above but Travis fails, I believe due to unrelated issues.

**Comment by degustaf** [comment]
@atodorov Yeah, a change made to astroid is making that test fail. The PR to fix it has already been made.

**Comment by PCManticore** [comment]
Thank you @atodorov

**Pull request merged**
