### PR TITLE
Do not use deprecated methods in ``PyLinter``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
The decrease in coverage makes me think that PyLinter might be used by Plugin lib and that it would be safer to remove that only after the deprecation period.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas I have fixed the coverage be re-enabling another test (in a hacky way).

The coverage decrease is now due to some inner `if` statements of some functions not being reached or some validators not being used. This is expected as we decrease the number of calls to `optparse` functions. Note that we do cover all `DeprecationWarnings`.

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by cdce8p** [comment]
This change seems to cause a major regression. At least for Home Assistant the `disable` config values aren't loaded anymore. _HA uses `pyproject.toml` for the pylint config if that helps._

To reproduce, it's enough to install the basic HA requirements and run
```
pylint homeassistant/core.py
```

**Comment by DanielNoord** [comment]
Investigating!

**Comment by DanielNoord** [comment]
> This change seems to cause a major regression. At least for Home Assistant the `disable` config values aren't loaded anymore. _HA uses `pyproject.toml` for the pylint config if that helps._
> 
> To reproduce, it's enough to install the basic HA requirements and run
> 
> ```
> pylint homeassistant/core.py
> ```

Did you bisect to this commit? I'm trying to replicate but I'm seeing difference in behaviour in `pyenv` and `virtualenv`. Seems like configuration discovery might be broken. Don't immediately see why this commit would cause that, but I'll keep looking.

**Comment by cdce8p** [comment]
> Did you bisect to this commit?

Yes.

> I'm trying to replicate but I'm seeing difference in behaviour in `pyenv` and `virtualenv`. Seems like configuration discovery might be broken. Don't immediately see why this commit would cause that, but I'll keep looking.

I'm using the stdlib `venv` module. I also did a `pip install -e <path>/pylint` beforehand.

**Comment by DanielNoord** [comment]
Error found! PR incoming 😄

**Comment by Pierre-Sassoulas** [comment]
The fact we merged without detecting the problem is worrying, maybe #5364 would have helped ?

**Comment by DanielNoord** [comment]
> The fact we merged without detecting the problem is worrying, maybe #5364 would have helped ?

We actually had a test for this specific bug but our test was wrong 😅

**Pull request merged**
