### PR TITLE
Fix test issues with master branch

### PR DESCRIPTION
**Pull request by cdce8p**
## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description
Fix test issues with master branch.

**`__hash__`**
Return `none` is implied if `__eq__` is overwritten but not `__hash__`.

**Drop Python 3.5**
#4074 introduced variable annotations to fix some mypy issues. However those require at least **Python 3.6** (PEP 526).
We could either revert the PR or just move to 3.6.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
|   | :sparkles: New feature |
|   | :hammer: Refactoring  |
|   | :scroll: Docs |

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
I'm merging before #4088  as it fixes the tests and will permit to work on the backlog of MR.

**Comment by cdce8p** [comment]
@Pierre-Sassoulas Should I rebase my MR or do you want to wait until #4088 is done?

**Comment by Pierre-Sassoulas** [comment]
Let's rebase (one by one in the order that make the most sense), PcManticore is often busy we can't bet on github actions working this week :) Feel free to ping me on the MR that are ready to merge.

**Comment by cdce8p** [comment]
> Let's rebase (one by one in the order that make the most sense), PcManticore is often busy we can't bet on github actions working this week :) Feel free to ping me on the MR that are ready to merge.

Sounds good

**Pull request merged**
