### PR TITLE
Fix spelling checker

### PR DESCRIPTION
**Pull request by s0undt3ch**
### Fixes / new features
* Remove dead code
* Do not lowercase words prior to spell checking them, "unicode" is a spelling mistake, "Unicode" is not.
* Add a "camelCaseWord" filter because some projects use those as parameter names and we should throw a spelling mistake on those if commented out for example.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
* Skip Sphinx directives

**Comment by PCManticore** [comment]
@s0undt3ch This looks great! I don't have anything to comment on this PR, but let's make the CI pass before merging this one. Thanks!

**Comment by PCManticore** [comment]
Merged manually.

**Comment by s0undt3ch** [comment]
Thanks, and sorry I didn't had a chance to make it pass.

**Pull request closed without merging**
