### PR TITLE
add new check redundant-else

### PR DESCRIPTION
**Pull request by sushobhit27**
add test cases for redundant_else check

add entry in ChangeLog
fix test cases

### Fixes / new features
- #2327

### CODE REVIEW

**Comment by sushobhit27** [comment]
This is incomplete, don't review it.

**Comment by PCManticore** [comment]
Let me know when you need a review here @sushobhit27

**Comment by sushobhit27** [comment]
> Let me know when you need a review here @sushobhit27
Actually my fix was giving false positive for below case:

```
if i < j:
    print i
elif i == j:
    print j
    continue
else:
    print 'boom'
```
I could not find a way to identify whether the current else is part of  "if " or elif.

Morever instead of emitting error at else as suggested originally in issue, I would say it is more descriptive to emit "redundant-continue-break" as in this case, user has to remove only one statement.
e.g taking original example:
```
for i in range(10):
        if i < 3:
            print('blah blah')
            continue  # or break
        else:  # Unnecessary else after "continue" or "break"
            print(i)
```
To correct above code, one would tend to do
```
for i in range(10):
        if i < 3:
            print('blah blah')
            continue  # or break
        print(i)
```
However I would prefer to have:
```
for i in range(10):
        if i < 3:
            print('blah blah')
       else:
           print(i)
```
Whats your take on this?

**Comment by PCManticore** [comment]
@sushobhit27 Do you still plan to tackle this?

**Pull request closed without merging**
