### PR TITLE
Hot-fix master following release of python 3.10-rc's new version

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

This is a hot fix, the real fix escape me right now.

### CODE REVIEW

**Comment by DanielNoord** [comment]
I wanted to fix this, but not quite sure what the original test is trying to test for.
In 3.10 you can assign types to create your own types, which is why the test is no longer emitting the warning.

**Comment by Pierre-Sassoulas** [comment]
Yes the part that look like a type assignment in 3.10 was invalid before 3.10 and crashed in astroid <=2.6.4, see #4439

**Comment by DanielNoord** [comment]
So no need to change the tests to be able to also run on 3.10?

**Comment by Pierre-Sassoulas** [comment]
Yes I think the change is ok as it is, if there was multiple use case in the functional test we'd have to separate them but there is just this one.

**Pull request merged**
