### PR TITLE
Json reporter improvment

### PR DESCRIPTION
**Pull request by deusyss**
## Steps

- [ ✓] Add yourself to CONTRIBUTORS if you are a new contributor.
- [✓ ] Add a ChangeLog entry describing what your PR does.
- [✓ ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [✓ ] Write a good description on what the PR does.

## Description
Hi,

The aim of this PR is to allow to get reports and score outputs in JSON, by limiting code impact. Impacted files are:
  * lint.py (one more line)
  * reporters.\_\_init\_\_.py (one more line)
  * reporters.json.py (only update existing methods)

In json.py, i used `display_reports` to display score & reports in JSON.

To get a valid JSON, i also modified `display_messages` and add a `self.cfg` variable in `BaseReporter` class to get the possibility to know, in reporter object, what user asked in command line. To pass this information, a line was added in `lint.py`.

## Type of Changes

|   | Type |
| ------------- | ------------- |
| x  | :bug: Bug fix  |
| ✓  | :sparkles: New feature |
| x  | :hammer: Refactoring  |
| x  | :scroll: Docs |

### CODE REVIEW

**Comment by deusyss** [comment]
Hi,
Pre check is failing, but this PR is modifying output JSON, and precheck failed on it.

**Comment by deusyss** [comment]
Can i help to make the test pass with success?

**Comment by PCManticore** [comment]
Thanks for the PR @deusyss but I'm not sure we want this. If you need more metadata like this, use the text reporter.

**Comment by deusyss** [comment]
Hi,

Thanks for your return, but i would appreciate you search to discuss before simply directly close my PR. I only search to improve this great tool. 

Text output is very verbose. Parsed it, if it's not complicated, allows to get all informations, but JSON is more universal and easier to share information. The actual JSON reporter only export analyze data, but not result, which is a real miss. 

This PR would allows to choose to add this output result in JSON, without impact basic operation.

**Pull request closed without merging**
