### PR TITLE
Use ``python-typing-update`` on ``pylint/testutils`` directory

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

Ref #4683.

### CODE REVIEW

**Review by cdce8p — APPROVED** [review]

**Comment by DanielNoord** [comment]
@cdce8p Want me to keep doing this in batches or do you trust the tool enough to do one big PR?

**Comment by cdce8p** [comment]
> @cdce8p Want me to keep doing this in batches or do you trust the tool enough to do one big PR?

If it's not too much effort, I would recommend batches. Although I do trust my tool, smaller chunks are much easier too review.

**Comment by DanielNoord** [comment]
> If it's not too much effort, I would recommend batches. Although I do trust my tool, smaller chunks are much easier too review.

Batches is easy enough! Just wanting the way that's easiest for all 😄

**Comment by cdce8p** [comment]
You can tag me for reviews if you want. Just to make sure I see the PRs 😃

**Comment by DanielNoord** [comment]
👍 

I was hesitant as I know you're often busy and there is still quite some PRs to go. Didn't want to be too pushy. But I'll tag you 😄

**Pull request merged**
