### PR TITLE
Use ``node.position`` in ``add_message`` if available

### LINKED ISSUE #5466: Better error ranges for classes and functions
The error ranges for `Class` and `Function` nodes should be improved. At the moment they span the whole length of the corresponding block which isn't ideal, especially once error range support in VSCode is added.

Ideally, those should only highlight the actual class or function name.

```py
def func2():
    return

class SomeCls:
    def __init__(self):
        """"""
        pass


def some_decorator_function():
    """some docstring"""

class invalid_class_name:
    pass

@some_decorator_function()
def invalidFunctionName():
    pass
```

Screen Shot 2021-12-03 at 19 14 28

Screen Shot 2021-12-03 at 19 17 01

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Description

Closes #5466.

I'd like to get approval on the code before I do the automatic updating of the tests. So please review this already even if tests fail 😄

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
The current change LGTM :)

**Review by cdce8p — APPROVED** [review]
> The current change LGTM :)

👍🏻

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Let's merge this first before we add all the regression test PRs. Otherwise we need to keep rebasing this.

**Review by cdce8p — COMMENTED** [review]
Missed that earlier, do we have an option for error messages to either opt out of or opt into using the `position` attribute? Say for example one message should be emitted for the whole function and not just the `def <name>`. Maybe a new parameter for `add_message`?

**Comment by DanielNoord** [comment]
> Missed that earlier, do we have an option for error messages to either opt out of or opt into using the `position` attribute? Say for example one message should be emitted for the whole function and not just the `def <name>`. Maybe a new parameter for `add_message`?

If you supply `line` etc. when you add the message nothing will be overwritten. Is that enough?

Note: apparently 3.8 is broken... I'll merge the other test PRs first while working on this.

**Review by Pierre-Sassoulas — APPROVED** [review]
Thank you @DanielNoord !

**Comment by cdce8p** [comment]
> > Missed that earlier, do we have an option for error messages to either opt out of or opt into using the `position` attribute? Say for example one message should be emitted for the whole function and not just the `def <name>`. Maybe a new parameter for `add_message`?
> 
> If you supply `line` etc. when you add the message nothing will be overwritten. Is that enough?

My initial idea was a parameter to toggle between both options. Not passing each value individually. However, after comparing the changes here, I think it might no longer be necessary. So far I haven't found a case were it would be noticeable better to mark the whole code block. Let's leave it as it is for now.

**Pull request merged**
