### PR TITLE
Fix AttributeError in checkers/refactoring.py

### PR DESCRIPTION
**Pull request by montyly**
## Steps

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [X] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [X] Write a good description on what the PR does.

## Description
This PR fixes an access to a field element that can happen on a None object.

Minimal testcase:
```python
def bug(cls, self):
    iter(super(cls, self).__iter__())
```

Without the PR:
```
  File "pylint/utils/ast_walker.py", line 72, in walk
    callback(astroid)
  File "pylint/checkers/refactoring.py", line 753, in visit_call
    self._check_super_with_arguments(node)
  File "pylint/checkers/refactoring.py", line 787, in _check_super_with_arguments
    or node.args[0].name != node_frame_class(node).name
AttributeError: 'NoneType' object has no attribute 'name'
```

The issue was introduced in `2.6.0` (`2.5.3` is not affected).

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Hello, thank you for the fix. Could you rebase this code on the latest master ? (refactoring.py just got moved to checker/refactoring/refactoring.py this morning). Also, could you add your minimal test case into `tests/functional/s/super_with_arguments.py` and adapt the .txt in order to not break the tests after that?

**Comment by hippo91** [comment]
@Pierre-Sassoulas as you began to look at this i assigned you to this PR. Hope you are ok with that.

**Comment by DavidCain** [comment]
I noticed this issue independently, and wrote up a small test case along with the equivalent fix. (Found this PR after doing so)

@montyly, please feel free to take the apply the changes as-is; no attribution required. (I can open a PR if needed, but didn't want to duplicate this issue).

Commit is here: https://github.com/DavidCain/pylint/commit/d387fcdd3423b50f707a363e69abf6140bab1c1f

**Comment by montyly** [comment]
Thanks @DavidCain for writing the test. 

@Pierre-Sassoulas, @hippo91, I rebased to master so there is no more conflict. Let me know if you need anything else

**Comment by Pierre-Sassoulas** [comment]
Thank you @montyly, I think there is still a problem with the rebasing, did you rebase on https://github.com/PyCQA/pylint.git's master ? Also I'm nitpicking, but you could cherry-pick @DavidCain's commit instead so we keep the original message and the code attribution for him ;)

**Comment by Pierre-Sassoulas** [comment]
Closing because I rebased myself and I'm going to merge in #3858. 

Thank you for the fix @DavidCain and @montyly :)

**Comment by DavidCain** [comment]
Thanks so much for fixing, Pierre! This is blocking a pylint upgrade in a few projects, so very excited to see this merged. Really appreciate your help.

**Pull request closed without merging**
