### PR TITLE
Use short copyright notice in ``doc`` and ``pylint`` directories

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

The least controversial changes from #5877. This makes #5877 a blocker for next release, but at least now my laptop doesn't go in overdrive mode immediately when opening that PR.

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
I want to make sure the ``contributors.txt`` contains everyone before removing the individual contributions from file. I have a lot on my plate right now and there's a lot of corner case but I'll get to it :)

**Comment by Pierre-Sassoulas** [comment]
Closing in favor of #5877

**Comment by DanielNoord** [comment]
> I want to make sure the `contributors.txt` contains everyone before removing the individual contributions from file. I have a lot on my plate right now and there's a lot of corner case but I'll get to it :)

👍 

Let me know if I can help with anything!

**Comment by Pierre-Sassoulas** [comment]
Actually, there's quite a bit of work finding committers using multiple emails and/or multiple names from the ``git shortlog --names`` and updating the configuration. Let me push the MR that was going to separate those two concerns.

**Comment by Pierre-Sassoulas** [comment]
Opened https://github.com/PyCQA/pylint/pull/5927 if you feel inspired.

**Pull request closed without merging**
