### PR TITLE
Pyreverse: PlantUML support + coloring (from PR #4521)

### LINKED ISSUE #4488: Proposal: automatically color modules in package diagram
### Is your feature request related to a problem? Please describe

I really like the possibility to generate package diagrams using ``pyreverse``. However, a complete diagram can become very big and complex. 
The currently just "black and white" output makes it hard to spot modules of the same package.
This is for example the package diagram for pylint itself:
image

### Describe the solution you'd like

By coloring modules of the same package with the same color, it is much easier to spot what parts belong together:
image

### Additional context

I also experimented with grouping modules of the same package together, but the result is not as clear:
image

To discuss is the best way to implement this. The image above was generated by automatically picking colors from a list based on the first two parts of the module name. 
Possible alternatives/extensions would be:
* Let the user define the colors to use in the configuration file, instead of picking colors automatically 
* Let the user define up to what depth he wants to distinguish subpackages

### LINKED ISSUE #4498: Permit to generate plantuml diagram with pyreverse
### Describe the solution you'd like

Permit to generate plantuml code in output of pyreverse

### Additional context

https://github.com/PyCQA/pylint/issues/4488

### PR DESCRIPTION
**Pull request by DudeNr33**
## Steps

- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description

This is a rather large PR, so I try my best to summarize the changes.
It solves both #4488 and #4498. 
The requested changes from PR #4521 are already included, and PR #4521 can be deleted (the introduction of ``NamedTuple`` for better typing was easier to do with the changes already made for the PlantUML support).

So here is an overview what this PR includes:

1. New Features:
    * Optional parameters ``--colorized`` and ``--max-color-depth`` to automatically color classes/modules of the same package (merged from PR #4521)
    * Implement a ``PlantUmlPrinter`` to support output to .puml files.  
    Note that automatic conversion to .png or other image formats is not supported yet; specifying "png" as output format will still rely on the Dot backend.
    * Positive side effect of refactoring: The various import-graphs provided by the ``ImportsChecker`` can now be produced in .vcg and .puml format, not only .dot.

2. Refactoring:
    * Defined a common ``Printer`` interface in ``pylint.pyreverse.printer`` for the possible backends (Dot, VCG, PlantUML).  
    Moved ``DotBackend`` and ``VCGPrinter`` to ``printer`` module.  
    * YAGNI: remove optional parameters from various methods in the ``Printer`` subclasses that were never used by the callers in the codebase, to find a minimal superset of parameters for each method signature.
    * Introduce factory function for picking the corresponding ``Printer`` or ``DiagramWriter`` subclass for the desired output format.
    * Remove module ``pylint.graph`` as it is no longer needed (``DotBackend`` is replaced by ``pylint.pyreverse.printer.DotPrinter``). Same for ``pylint.pyreverse.vcgutils``.
    Move orphaned ``get_cycles()`` function to ``pylint.checkers.imports``, which is (in my opinion) the better place for it anyway.
    * Refactor tests:
        * move to own subdirectory
        * split into functional tests and unit tests
        * extract for ``pyreverse.utils`` into own test module
    * Improve typing by adding type hints and use NamedTuples etc. where appropriate.
    * Use a consistent style for defining the dictionaries of the configuration options
    * Improve ``exclude`` rules in the ``pre-commit-config.yaml`` so it does not need to be expanded every time a new ``data`` subdirectory or a new ``conftest.py`` is added to the tests.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |

## Related Issue

Closes #4488
Closes #4498

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Hey, sorry for the delay before reviewing. There's a lot to review here and I never got a long enough period to do it properly. Could you rebase on the latest main, fix the conflicts, and put the changelog in 2.10 instead of 2.9 first, please ? If there are little changes that could be reviewed as a standalone MR, we could merge them first and that would help with the review time.

**Comment by DudeNr33** [comment]
Splitting this MR into smaller parts would certainly be possible.
That would probably be:

1. Refactoring towards the common ``Printer`` base class, as prerequisite for the following changes
2. Introduction of type annotations
3. Refactoring of tests
4. Introduction of ``PlantUMLPrinter`` and ``PlantUMLWriter``
5. Introduction of the ``ColorMixin`` class

1 & 2 might fit together well into one MR.
In this case I would not rebase this MR, as it would no longer be needed. I don't know if merging the "preparation" MRs into this one would go cleanly.

**Comment by Pierre-Sassoulas** [comment]
Sound great, I don't mind if we open a dozen of new MR and close this one :)

**Comment by Pierre-Sassoulas** [comment]
Closing in favor of #4850

**Pull request closed without merging**
