### PR TITLE
Add typing to checker and plugin attributes of ``PyLinter``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

Seems like we made an error in https://github.com/PyCQA/pylint/pull/5004 that I didn't catch in my review.

Checkers ``__implements__`` `Ichecker`, but this isn't picked up on by `mypy`. The typing should thus be `BaseChecker`.

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
I think I've already done that in #5558 :smile: ? (Well I used an union of both sometime)

**Comment by DanielNoord** [comment]
I didn't check that, but if you did we should remove `IChecker`. `mypy` has no way to interact with it so it doesn't really provide us with much..

**Comment by Pierre-Sassoulas** [comment]
See https://github.com/PyCQA/pylint/pull/5558/files#diff-f7184ace78676137bed7c4c7efec25dca1aa06ed21166e31396ac450f78400c0R25 (the whole file) and https://github.com/PyCQA/pylint/pull/5558/files#diff-3a681c16a79ae9818f939e08df8b9bb92ef9ce6d5fc65c360d7c9b526c3c3410R724

I think it makes sense to first merge this MR, as IChecker does not do much, then rebase #5558 on it ?

**Comment by DanielNoord** [comment]
Sounds good!

**Review by Pierre-Sassoulas — APPROVED** [review]

**Pull request merged**
