### PR TITLE
Add typing to ``basic_checker``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Is the primer broken because we're on bleeding edge astroid ? I feel like it should be said somewhere if that's the case. Also we probably want to provide the crash template file instead of the pylint message ?

**Comment by DanielNoord** [comment]
> Is the primer broken because we're on bleeding edge astroid ? 

@jacobtylerwalls Another `importlib` issue.. Do you recognise it?

> I feel like it should be said somewhere if that's the case. Also we probably want to provide the crash template file instead of the pylint message ?

I don't think we can easily extract the crash template from the environment. Perhaps we can redirect `stderr` to a file and print it so you at least get the stacktrace.

**Comment by jacobtylerwalls** [comment]
It was fixed in the Astroid PR we merged this morning. The job did not fail, just extraneous comments. I'm a little surprised that it appeared in the content of the message. I would have thought that 5 Astroid errors == 5 Astroid errors leads to no message.

**Comment by jacobtylerwalls** [comment]
> Also we probably want to provide the crash template file instead of the pylint message ?
All of it in the log, including a GitHub Actions warning to point folks directly to it. We did a lot of work around this :D

I agree it could still surprise a contributor. I'm realizing it's not just `astroid` -- we've solved the failing jobs issue from using bleeding edge. It could be any of the open source projects in the primer that push a new commit, we then have a drift in messages emitted between main and PR, no? I'll post on the other thread.

**Comment by Pierre-Sassoulas** [comment]
> It could be any of the open source projects in the primer that push a new commit, we then have a drift in messages emitted between main and PR, no? I'll post on the other thread.

I think we discussed this with @DanielNoord when we added the original primer, there's a system in place for caching based on a concatenation of all repo hashes.

**Comment by Pierre-Sassoulas** [comment]
>  I found the issue. It's a funny one (for us developers that is...)

That is some back-of-the-labtop-worthy quote. (Also, great analysis 👍 )

**Comment by jacobtylerwalls** [comment]
> Because I'm dumb and ignore any changes to doc/data/messages/** in

I was the one that asked for this, sorry! 🧐

**Pull request merged**
