### PR TITLE
add example for `reimported` message documentation

### PR DESCRIPTION
**Pull request by gunungpw**
- [x] Write a good description on what the PR does.
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description
- add code example for `reimported`
- exclude bad.py at `isort` hook `.pre-commit-config.yaml`

Related #5953

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
isort and/or autoflake needs to be disabled in the pre-commit configuration

**Review by Pierre-Sassoulas — APPROVED** [review]
👍

**Comment by matusvalo** [comment]
@Pierre-Sassoulas  please mark this in the table of the bug - it is missed.

**Comment by Pierre-Sassoulas** [comment]
Nice catch !

**Pull request merged**
