### PR TITLE
Add documentation for too-many-lines

### PR DESCRIPTION
**Pull request by ollie-iterators**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Add documentation for too-many-lines

Refs #5953 

Closes #XXXX

### CODE REVIEW

**Comment by ollie-iterators** [comment]
@Pierre-Sassoulas If you have an issue with the code. Please provide an example of how you think the code should be written.

**Comment by ollie-iterators** [comment]
@Pierre-Sassoulas I took the review comments of @clavedeluna  when I made this pull request. So what is the issue now?

**Comment by Pierre-Sassoulas** [comment]
I reviewed in https://github.com/PyCQA/pylint/pull/8219#pullrequestreview-1287863516 and closed the first MR with an explanation that I won't repeat here. I already told you that you should read reviews and be more considerate of our time as maintainer and of the runners used by the organization in https://github.com/PyCQA/pylint/pull/8219#discussion_r1099112937. You then opened https://github.com/PyCQA/pylint/pull/8235 and wasted @clavedeluna's time on something already rejected by deceiptively not linking to the discussion in the first MR. I closed this second MR in https://github.com/PyCQA/pylint/pull/8235#issuecomment-1422733706 which I think was straightforward. Now you open yet another merge requests, push 6 commits and you need me to "please provide an example" ?

**Comment by ollie-iterators** [comment]
Ok, I'll move on to other things.

**Comment by ollie-iterators** [comment]
> I reviewed in [#8219 (review)](https://github.com/PyCQA/pylint/pull/8219#pullrequestreview-1287863516) and closed the first MR with an explanation that I won't repeat here. I already told you that you should read reviews and be more considerate of our time as maintainer and of the runners used by the organization in [#8219 (comment)](https://github.com/PyCQA/pylint/pull/8219#discussion_r1099112937). You then opened #8235 and wasted @clavedeluna's time on something already rejected by **deceiptively not linking to the discussion in the first MR.** I closed this second MR in [#8235 (comment)](https://github.com/PyCQA/pylint/pull/8235#issuecomment-1422733706) which I think was straightforward. Now you open yet another merge requests, push 6 commits and you need me to "please provide an example" ?

"Never attribute to malice that which is adequately explained by stupidity." Hanlon's razor

**Pull request closed without merging**
