### PR TITLE
Require astroid 2.5.7

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Description

Upgrade astroid so we get the latest fixes.

## Related Issue

https://github.com/PyCQA/pylint/pull/4471
https://github.com/PyCQA/pylint/pull/4473
https://github.com/PyCQA/pylint/pull/4428
https://github.com/PyCQA/pylint/pull/4348
https://github.com/PyCQA/pylint/pull/4325

### CODE REVIEW

**Comment by cdce8p** [comment]
The tests require #4325 and #4428 to be merged. I would suggest merging this one and the two mention even with test not passing initially.

**Comment by Pierre-Sassoulas** [comment]
Ha, I saw your message too late. Well better late than never.

**Comment by cdce8p** [comment]
FYI: I've updated all related MRs and merged them after the tests passed.

**Comment by Pierre-Sassoulas** [comment]
Thank you, great job ! Look like pylint got slower though, I feel we need to check #4524 before releasing 2.9.0.

**Pull request merged**
