### PR TITLE
Update tox.ini - Add `isolated_build = True`.

### LINKED ISSUE #7188: ``tox -e docs`` not working since the migration to ``pyproject.toml``
### Bug description

tox does not understand the packaging and create ``/home/pierre/pylint/.tox/.tmp/package/1/UNKNOWN-0.0.0.zip``. We could fix it or we could drop tox in favor of the makefile in ``doc/`` (it's working)

### Configuration

_No response_

### Command used

```shell
tox -e docs
```

### Pylint output

```shell
GLOB sdist-make: /home/pierre/pylint/setup.py

docs inst-nodeps: /home/pierre/pylint/.tox/.tmp/package/1/UNKNOWN-0.0.0.zip

ERROR: invocation failed (exit code 1), logfile: /home/pierre/pylint/.tox/docs/log/docs-5.log

================================================================================================ log start ================================================================================================

Processing ./.tox/.tmp/package/1/UNKNOWN-0.0.0.zip

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error

  

  × Getting requirements to build wheel did not run successfully.

  │ exit code: 1

  ╰─> [48 lines of output]

      /tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:104: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.

        warnings.warn(msg, _BetaConfiguration)

      Traceback (most recent call last):

        File "/home/pierre/pylint/.tox/docs/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>

          main()

        File "/home/pierre/pylint/.tox/docs/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main

          json_out['return_val'] = hook(**hook_input['kwargs'])

        File "/home/pierre/pylint/.tox/docs/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel

          return hook(config_settings)

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel

          return self._get_build_requires(

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires

          self.run_setup()

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup

          exec(compile(code, __file__, 'exec'), locals())

        File "setup.py", line 6, in <module>

          setup()

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup

          return distutils.core.setup(**attrs)

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 151, in setup

          dist.parse_config_files()

        File "/home/pierre/pylint/.tox/docs/lib/python3.10/site-packages/_virtualenv.py", line 21, in parse_config_files

          result = old_parse_config_files(self, *args, **kwargs)

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 869, in parse_config_files

          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 58, in apply_configuration

          config = read_configuration(filepath, True, ignore_option_errors, dist)

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 136, in read_configuration

          return expand_configuration(asdict, root_dir, ignore_option_errors, dist)

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 191, in expand_configuration

          return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 238, in expand

          self._expand_all_dynamic(dist, package_dir)

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 282, in _expand_all_dynamic

          version=self._obtain_version(dist, package_dir),

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 328, in _obtain_version

          return _expand.version(self._obtain(dist, "version", package_dir))

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 317, in _obtain

          return self._expand_directive(

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 311, in _expand_directive

          return _expand.read_attr(directive["attr"], package_dir, root_dir)

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/config/expand.py", line 186, in read_attr

          spec = _find_spec(module_name, path)

        File "/tmp/pip-build-env-z2isbtw3/overlay/lib/python3.10/site-packages/setuptools/config/expand.py", line 198, in _find_spec

          spec = spec or importlib.util.find_spec(module_name)

        File "/usr/lib/python3.10/importlib/util.py", line 94, in find_spec

          parent = __import__(parent_name, fromlist=['__path__'])

      ModuleNotFoundError: No module named 'pylint'

      [end of output]

  

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: subprocess-exited-with-error



× Getting requirements to build wheel did not run successfully.

│ exit code: 1

╰─> See above for output.



note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Expected behavior

Regenerate the docs instead.

### Pylint version

```shell
2.15.0-dev0
```

### OS / Environment

_No response_

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by mbyrnepr2**
Closes #7188

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
|    | :scroll: Docs          |

## Description

Further info: 
https://tox.wiki/en/latest/config.html#conf-isolated_build 
https://tox.wiki/en/latest/example/package.html#packaging

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
Thank you @mbyrnepr2  ! Maybe we could switch a github action to using tox so we detect this kind of problem in the future ?

**Comment by mbyrnepr2** [comment]
> Thank you @mbyrnepr2 ! Maybe we could switch a github action to using tox so we detect this kind of problem in the future ?

I can't work on it right this moment but perhaps later tonight I can poke around.

**Comment by Pierre-Sassoulas** [comment]
No rush, I don't think any pylint contributors used tox in 15 days, or I would not have opened this myself :)

**Comment by mbyrnepr2** [comment]
@Pierre-Sassoulas I'm thinking of updating [this](https://github.com/PyCQA/pylint/blob/40c9e66e4756e76318469f1484602ca92d505d3f/.github/workflows/checks.yaml#L191) `documentation` job to use tox to call the command instead (Just to take the original command reported by your issue as a case).
I also thought it would be nice to add a step below this to run the documentation-examples test; which would require an addition to tox.ini. Does that sound reasonable?

**Comment by Pierre-Sassoulas** [comment]
I like that running the doc test via tox would be possible, actually you have to know the command for test doc because pytest do not launch them by default so it would be pretty nice to have a "test doc" command.  Maybe we can only move that one to tox  and not the doc generation ?

**Review by Pierre-Sassoulas — APPROVED** [review]
Great, "two in one" pull request !!

**Comment by mbyrnepr2** [comment]
> Great, "two in one" pull request !!

Thanks to you for great suggestions @Pierre-Sassoulas!
I came here for a quick one-liner and unexpectedly had my first github actions experience

**Pull request merged**
