### PR TITLE
Clear `sys.argv` before calling out to the isort lib

### PR DESCRIPTION
**Pull request by s0undt3ch**
## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description
See title.
Before fix:
```
pylint --rcfile=.pylintrc --disable=I salt/fileserver/s3fs.py
Usage: pylint [options]

------------------------------------
Your code has been rated at 10.00/10
```

After fix:
```
pylint --rcfile=.pylintrc --disable=I salt/fileserver/s3fs.py

------------------------------------
Your code has been rated at 10.00/10
```

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

### CODE REVIEW

**Comment by PCManticore** [comment]
I'm not entirely sure how this happens, is it caused by `isort` itself? We should probably investigate why it behaves like this rather than clearing `sys.argv` ourselves.

**Comment by s0undt3ch** [comment]
It took a while to see where in pylint's code I got pylint's usage printed out. Didn't investigate further into it.

**Comment by s0undt3ch** [comment]
I mean, I know patching `sys.argv` even if momentarily isn't ideal, but right now I don't have the time to chase the proper fix, sorry. It was just annoying me too much.

**Comment by PCManticore** [comment]
Hey @s0undt3ch Going to close this one, I'm not able to reproduce it. We might need some reproduction examples before merging this as is, but haven't seen any other reports about the issue so far.

**Pull request closed without merging**
