### PR TITLE
Upgrade astroid to 2.14.2

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
Also add regression test for #8109

### CODE REVIEW

**Review by DanielNoord — APPROVED** [review]
Not sure we need the regression test as it completely duplicates the test in `astroid`, but I'm fine either way

**Comment by Pierre-Sassoulas** [comment]
The merge queue seems to not permit to choose between squash/rebase/merge, this is going to be a problem for messy MR we're going to be forced to ask for cleanup. Did you activate it ?

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas That's annoying. Disabling it again.

**Comment by Pierre-Sassoulas** [comment]
It seem it's possible to bypass with admin rights, the intention is good though but we're not forcing to be on the latest main and to run the test on the latest main or we would not be merging anything. So it's also going to increase massively the runner used if we put it back because right now we don't. Like for this MR the test were running again when they weren't before. Or maybe it's the equivalent of running the test on main and then merging but not running the test on main ? Right now we're dropping the current the primer on main when there is a new commit merged so it's also going to take longer with merge queue (the primer is going to run fully for each commit on main?).

**Comment by Pierre-Sassoulas** [comment]
OK, probably just a case of github needing to permit rebase/squash/merge in their interface too, then it's a very good thing. It's still in beta it seems, I don't know if we can provide feedback somewhere.

**Pull request merged**
