### PR TITLE
Add `compare-to-empty-string` example

### PR DESCRIPTION
**Pull request by harupy**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

Refs #5953

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
I did not remember we had this check. This is very, very similar to ``use-implicit-booleaness-not-x`` type check, it kinda make me want to rename this or move them all in their own checker to make it coherent. Do you have an opinion on this @harupy ?

**Comment by harupy** [comment]
> move them all in their own checker to make it coherent.

Sounds good me :)

**Comment by Pierre-Sassoulas** [comment]
Ok, I took a closer look. ``compare-to-zero`` and ``compare-to-empty-string``are quite more opinionated than  ``use-implicit-booleaness-not-len`` and  ``use-implicit-booleaness-not-copmparison`` which is probably why they are in their own optional checker. 

Doing ``x != 0`` or feel a lot safer and easier to understand than ``bool(x)`` for int (you need a background in C to understand that). Renaming them could be an option, I'm going to open an issue to discuss it but in the meantime I think we could merge this.

**Review by Pierre-Sassoulas — APPROVED** [review]
Created https://github.com/PyCQA/pylint/issues/6871 if you want to chime in :)

**Pull request merged**
