### PR TITLE
Add a functional regression test.

### PR DESCRIPTION
**Pull request by mbyrnepr2**
## Description

Refs #3941

### CODE REVIEW

**Comment by DanielNoord** [comment]
I recently changed opinion about these regressions tests: imo they unnecessarily prolong the `pytest` test suite. As long as there is a regression test in `astroid` the only thing this is testing is whether we are using `astroid` above a certain version number. I don't think we need tests for that as I can't see a reason where that would regress unexpectedly.

I'm obviously open to counter arguments as to why we should add such tests!

**Comment by Pierre-Sassoulas** [comment]
Maybe we should think about it on a case by case basis. I think that depending on the complexity of the pylint code that surround the astroid parsing it can make sense or not to add a test. For example if we were previously patching astroid's deficiency or if the checker is very complex we need the regression tests to be sure that we can remove the patching or refactor a checker without regression. If the check is very simple and is only based on astroid's result that is faulty then yes the regression tests is only a waste of time.

**Comment by mbyrnepr2** [comment]
So perhaps the solution would be to move this test to where existing Enum tests live in the Pylint test suite instead of excluding the case entirely. Maybe someday a change in Astroid will reintroduce this issue to Pylint.

**Comment by DanielNoord** [comment]
The test in https://github.com/PyCQA/astroid/pull/1820/ specifically checks for the name in `locals`. Imo, that's good enough for this particular example.

**Comment by mbyrnepr2** [comment]
> The test in [PyCQA/astroid#1820](https://github.com/PyCQA/astroid/pull/1820) specifically checks for the name in `locals`. Imo, that's good enough for this particular example.

OK I'm happy with that!

**Pull request closed without merging**
