### PR TITLE
Fix disabling of ``ungrouped-imports``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Needed for a PR that stops using the deprecated ``cachedproperty`` decorator from `astroid`.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
👍

**Comment by jacobtylerwalls** [comment]
Cool. So it looks like #2366 wasn't truly fixed, as the regression test added in #5063 didn't repro -- it just lacked the final line from the original report! Is it worth referencing the original issue in the changelog or not?

**Comment by DanielNoord** [comment]
@jacobtylerwalls I totally forgot I added that method. Anyway, I think that this solution is better (instead of using the method added in #5063). I think I did not fully look into `ungrouped-imports` when I did that issue and only focused on the message in the OP.

I could add the issue, but since it was "fixed" in 2.12 might be a bit weird. @Pierre-Sassoulas You decide 😄

**Comment by jacobtylerwalls** [comment]
> I could add the issue, but since it was "fixed" in 2.12 might be a bit weird.

There are several cases where we just say "refers to" or "refs #..." right? best of both worlds.

**Comment by Pierre-Sassoulas** [comment]
I think we don't need to create issue when the problem is fixed (We can ``Refs #The PR`` so those wanting detail can find them).

**Review by jacobtylerwalls — APPROVED** [review]

**Pull request merged**
