### PR TITLE
Bump CI cache version

### PR DESCRIPTION
**Pull request by cdce8p**
## Description
Bump the cache version. Will fix the CI issues seen in #5600 where it could create the venv.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
You're lucky, no issue with github actions 😄

**Comment by cdce8p** [comment]
> You're lucky, no issue with github actions 😄

Define lucky 😅
Took me a while to figure out that this was enough to fix it. Had the same issue on one of my personal repos.

**Comment by DanielNoord** [comment]
@cdce8p For future reference, we also store `CACHE_VERSION` in the `primer` workflow. I'm adding a commit + comments that they should be changed in both places.

**Comment by cdce8p** [comment]
Found a Python bug report that looks like the root cause for our issues: https://bugs.python.org/issue46197

**Comment by DanielNoord** [comment]
@cdce8p Good catch! That indeed seems to eb the culprit.

**Pull request merged**
