### PR TITLE
Add experimental ``pylint-config`` command

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.
- [x] If you used multiple emails or multiple names when contributing, add your mails
   and preferred name in ``script/.contributors_aliases.json``

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Description

Ref. https://github.com/PyCQA/pylint/issues/971

Let's put this in `2.15`. But would this be the way to do this?

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
I think it would make sense to create a subcommand ``pylint generate-config``. The original issue implicitly want to do a lot more than simply generating the configuration, a simple way to do more would be to have templates like "django-web", "ML-tensorflow", "legacy-project" (everything disabled at first ?), "new-project (everything enabled), and to simply propose to choose one of the template.

**Comment by Pierre-Sassoulas** [comment]
>  We would then also need to do pylint run

Hurgh. That could be a cleanup for 3.0 but there isn't any other command that make sense to create right now. I was thinking of "suggest" as in ``pylint suggest`` (#5604), maybe ``baseline`` ? It's probably never going to justify breaking all the script in the world.

**Comment by DanielNoord** [comment]
> > We would then also need to do pylint run
> 
> Hurgh. That could be a cleanup for 3.0 but there isn't any other command that make sense to create right now. I was thinking of "suggest" as in `pylint suggest` (#5604), maybe `baseline` ? It's probably never going to justify breaking all the script in the world.

My idea was to do a ``pylint --generate-config`` and ``pylint --generate-config-dont-ask-me-questions-just-fix-everything-for-me``. With the latter being essentially the first with all questions taking the default value.
That seems to have the good bits of both?

_I also don't want to do ``pylint --generate-config --outputfile=CONFIG`` as then ``--outputfile`` would end up in the general options... So it's probably best to handle everything interactively._

**Comment by DanielNoord** [comment]
Going to close this as I am now using a different approach compared to the original attempt and would like a clean PR.

**Pull request closed without merging**
