### PR TITLE
Add ``needs_two_cores`` mark

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

This feels like the 10th time I have used this PR title. But let's try this 😄

### CODE REVIEW

**Comment by DanielNoord** [comment]
I can't get the CI to fail 😅 

Tests are passing on Linux without any issues in 5 attempts...

**Comment by Pierre-Sassoulas** [comment]
> Tests are passing on Linux without any issues in 5 attempts...

Is it a ... bad thing ?

**Comment by DanielNoord** [comment]
Yeah haha

I want to see if the flaky tests get skipped if the available cores dip down to one. Having them pass shows doesn't show if this mitigation works.

**Comment by DanielNoord** [comment]
8 runs later and still no skip... @Pierre-Sassoulas can you try and re-run this when you merge a couple of PRs? I feel like the tests fail more often if there are more runners in queue or perhaps when USA wakes up.

As I said, the goal is for the `jobs` tests to get `SKIPPED` instead of `PASSED` on any of the Windows or Linux test runs. That would indicate that this works.

**Comment by DanielNoord** [comment]
Finally got a hang, but turned out another test was causing issues as well. Let's hope this fixes something 😄

**Review by Pierre-Sassoulas — APPROVED** [review]
Very nice !

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas I'm wondering if there are any bad side-effects of merging this and seeing if this fixes it. I'm getting a bit tired of trying to get a failed test 😄

**Comment by DanielNoord** [comment]
Sadly, this does not seem to work and we still got a hang. Back to the drawing board.

**Pull request closed without merging**
