### PR TITLE
Post pylint 3.0.3

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
@Pierre-Sassoulas let me know how this looks, I'm eager to learn the blessed way of doing this. Do you generally fixup the second commit removing the fragments into the merge commit? When I attempted doing that, I was presented with a long list of rebase merge conflicts for all the caboose commits before the patch release commit.

Or, will we squash merge this anyway?

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
Or should I push to maintenance/3.0.x instead of pushing to a fresh branch?

**Comment by jacobtylerwalls** [comment]
I guess we can't squash merge because then we'd lose the commit we need for `pre-commit autoupdate`, which was the whole point of doing it this way instead of #9297.

Anyway, long story short, I'd very much appreciate as a precise a recipe to follow as we can muster! 💜

**Comment by Pierre-Sassoulas** [comment]
😄 So the way I'm doing it is as follow:
```
git fetch -ap
git switch maintenance/3.0.x
git branch merge-maintenance-into-main
git merge origin/main
# fix obvious conflicts (at least the 3 places where there's conflicting versions)
git merge --continue
# while not(the only changes are the changelog, possibly changes in Contributors.txt with)
    # Check the while condition with
    git diff origin/main
    # Fix things then fixup the merge commit
    git commit -a --amend
git push pierre
# Open a merge request from pierre/merge-maintenance-into-main to origin/main
# Select "Create a merge commit" enable auto-merge (so no one squash it after approving review by mistake)
# Wait for review
```

**Comment by Pierre-Sassoulas** [comment]
Having to remove manually the fragments so they don't end up on main would be more work. (Which is why I was not very argumentative with Daniel even if I think that we should not duplicate the changelog between patch and minor). Should probably be done with tbump or a script, or we won't release as often.

**Review by Pierre-Sassoulas — APPROVED** [review]
LGTM; you did something similar, and we simply need to use merge not squash or rebase, right ?

**Pull request merged**
