### PR TITLE
Finish typing of ``pylint/testutils``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
👌

**Comment by Pierre-Sassoulas** [comment]
The pre-commit mypy error is a real one though.

**Comment by DanielNoord** [comment]
> The pre-commit mypy error is a real one though.

hmm, didn't get that locally. Let me check!

**Comment by DanielNoord** [comment]
Ah, that's quite annoying (and might become problematic for non test code as well).
Because `CheckerTestCase.CHECKER_CLASS` is now correctly typed as `BaseChecker` and not as `None` we now get warnings about certain methods not being defined. `BaseChecker` does not have all `visit_...` methods.

**Comment by Pierre-Sassoulas** [comment]
I think the base problem is hard to solve as we need to find a way to make the visitor pattern understood by type checker. I found this (mostly unrelated) issue when searching or clue on how to do that:  https://github.com/gvanrossum/patma/issues/137 (It warms my heart to see that G Van Rossum himself  and python core devs miss pylint and flake8 when implementing new syntaxes ❤️)

**Pull request merged**
