### PR TITLE
Add ``potential-index-error`` checker

### LINKED ISSUE #578: Understand IndexError
Originally reported by: **Claudiu Popa (BitBucket: [PCManticore](http://bitbucket.org/PCManticore), GitHub: @PCManticore)**

---

In certain situations, we could understand IndexErrors:

```
#!python

from astroid.test_utils import extract_node
n = extract_node('''
[1, 2, 3][10] #Index out of range
''')
print(n.infered())
```

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/578

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature, or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Description

I've tried to keep this very conservative as we risk throwing false positives for this very easily.

I would like some input on additional test cases and add those before we merge this, to make this a little more robust.

Closes #578

### CODE REVIEW

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Are you planning on releasing `2.13` soon? I think there might be some room in `2.13` for additional features/fixes. There aren't that many actual user-impacting changes in the changelog right now.

**Comment by Pierre-Sassoulas** [comment]
> Are you planning on releasing 2.13 soon?

I'm trying to release astroid 2.9.1 soon. I won't move issue to 2.14 unless there's a good reason so checking the milestone should be a good indicator of the plan. There's 40+ issues that still need to be addressed in 2.13, but there's already 100 closed items so I'm starting to think about releasing and it starts with astroid :)

**Comment by Pierre-Sassoulas** [comment]
Moving to 2.14 as we have a lot of user impacting change in 2.13 now.

**Comment by DanielNoord** [comment]
Need to add documentation a la https://github.com/PyCQA/pylint/issues/5953.

**Review by Pierre-Sassoulas — APPROVED** [review]
LGTM. I like that we're being careful about it. 

>  there's already 100 closed items

We started trying to release 2.13.0 at 100 issues and managed to actually do it after 250+ issues 😄

**Comment by DanielNoord** [comment]
> LGTM. I like that we're being careful about it.
> 
> > there's already 100 closed items
> 
> We started trying to release 2.13.0 at 100 issues and managed to actually do it after 250+ issues 😄

😄

**Pull request merged**
