### PR TITLE
Add documentation examples for `invalid-envvar-default`

### PR DESCRIPTION
**Pull request by julthep**
Co-authored-by: Vladyslav Krylasov <vladyslav.krylasov@gmail.com>

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description
Add documentation examples for `invalid-envvar-default`

Refs #5953

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
I'm wondering if we're not doing mypy's job here (on a very very limited scope, by hardocding the expected type). Maybe something to remove entirely, what do you think @DanielNoord ?

**Comment by DanielNoord** [comment]
> I'm wondering if we're not doing mypy's job here (on a very very limited scope, by hardocding the expected type). Maybe something to remove entirely, what do you think @DanielNoord ?

I think this is valid, see: https://docs.python.org/3/library/os.html#os.getenv.

The default should simply be a string as that is what `getenv` is supposed to return. It makes no sense to return anything else: `var = os.getenv("VAR",1)` would still requires `var = int(var)` in case the default isn't used.

**Comment by Pierre-Sassoulas** [comment]
> The default should simply be a string as that is what getenv is supposed to return. It makes no sense to return anything else: var = os.getenv("VAR",1) would still requires var = int(var) in case the default isn't used.

Sure, but my point is that mypy does that generically for all functions (builtins or otherwise), why do we have a message for this particular argument of this particular function ? If we extend this reasoning we would create a new message for each argument of each builtin function.

**Comment by DanielNoord** [comment]
> > The default should simply be a string as that is what getenv is supposed to return. It makes no sense to return anything else: var = os.getenv("VAR",1) would still requires var = int(var) in case the default isn't used.
> 
> Sure, but my point is that mypy does that generically for all functions (builtins or otherwise), why do we have a message for this particular argument of this particular function ? If we extend this reasoning we would create a new message for each argument of each builtin function.

Perhaps we should? 😄 In this case I don't think it is such a problem. There are no open issue about it and https://github.com/PyCQA/pylint/issues/3512 also indicates that there are no older complaints about it. It's an useful check which could warn people who are no using `mypy` about a potential "mistake".

**Review by Pierre-Sassoulas — APPROVED** [review]

**Pull request merged**
