### PR TITLE
Suppress ``OSError`` in config file discovery

### LINKED ISSUE #7169: Default rcfile locations are scanned even when --rcfile option is specified
### Bug description

With the latest version `2.14.4`, pylint scans the default rcfile locations even when `--rcfile` option with valid rcfile path is specified. It is problematic because it caused a permission error when an user doesn't have an access permissions to the pre-determined default path of default `rcfile` files.

### Configuration

_No response_

### Command used

```shell
$ pylint --rcfile /config/pyproject.toml
```

### Pylint output

```shell
Traceback (most recent call last):
  File "/home/myhome/.pyenv/versions/3.10.5/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/__init__.py", line 22, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/lint/__init__.py", line 19, in <module>
    from pylint.config.exceptions import ArgumentPreprocessingError
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/config/__init__.py", line 27, in <module>
    from pylint.config.environment_variable import PYLINTRC
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/config/environment_variable.py", line 11, in <module>
    PYLINTRC = find_pylintrc()
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/config/find_default_config_files.py", line 94, in find_pylintrc
    for config_file in find_default_config_files():
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/config/find_default_config_files.py", line 76, in find_default_config_files
    if home_rc.is_file():
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/pathlib.py", line 1322, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/home/myhome/.config/pylintrc'
```

### Expected behavior

With the prior version at least `2.13.5`, the problem didn't happen. `2.13.5` don't seem to scan default rcfile locations when `--rcfile` option with valid rcfile path is specified.  Similar to `2.13.5`, I think the latest version `2.14.4` and later version are also expected to skip scanning the default paths when `--rcfile` option with valid path is specified.

### Pylint version

```shell
Used 2.14.4.

`$ pylint --version` didn't work because of the issue.

$ pylint --version
Traceback (most recent call last):
  File "/home/myhome/.pyenv/versions/3.10.5/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/__init__.py", line 22, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/lint/__init__.py", line 19, in <module>
    from pylint.config.exceptions import ArgumentPreprocessingError
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/config/__init__.py", line 27, in <module>
    from pylint.config.environment_variable import PYLINTRC
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/config/environment_variable.py", line 11, in <module>
    PYLINTRC = find_pylintrc()
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/config/find_default_config_files.py", line 94, in find_pylintrc
    for config_file in find_default_config_files():
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/site-packages/pylint/config/find_default_config_files.py", line 76, in find_default_config_files
    if home_rc.is_file():
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/pathlib.py", line 1322, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/home/myhome/.pyenv/versions/3.10.5/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/home/myhome/.config/pylintrc'
```

### OS / Environment

Ubuntu focal by using the docker image via `FROM ubuntu:focal-20220531`

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Write a good description on what the PR does.
- [x] Create a news fragment with `towncrier create <IssueNumber>.<type>` which will be
  included in the changelog. `<type>` can be one of: new_check, removed_check, extension,
  false_positive, false_negative, bugfix, other, internal. If necessary you can write
  details or offer examples on how the new change is supposed to work.
- [x] If you used multiple emails or multiple names when contributing, add your mails
      and preferred name in ``script/.contributors_aliases.json``

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #7169

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
Did'nt you say that t contextlib performance were worst than try/except ?

**Comment by DanielNoord** [comment]
> Did'nt you say that t contextlib performance were worst than try/except ?

It is (marginally) I think.

But since this only called once and the code became really unreadable with all the `try ... except` everywhere I opted for this solution.

Want me to change?

**Comment by Pierre-Sassoulas** [comment]
> Want me to change?

Not at all, just wanted to know your opinion :)

**Review by Pierre-Sassoulas — COMMENTED** [review]
I have a feeling this is getting really complicated. Also we're not handling errors. Failing to yield a configuration file because of a permission error will make pylint not take a file into account for non obvious reasons so it seems like we need to do something on top of suppression the error outright.

How about we create some function with explicit name like "get all ini config file" or "search for configuration file in parent directories". That way we can launch a single function in the contextlib.suppresserror or use try/except and maybe decide later what to do easily in case of error.

**Comment by Pierre-Sassoulas** [comment]
> I can also print something to stdout when we are in verbose mode? 

Sounds good !

**Comment by DanielNoord** [comment]
> > I can also print something to stdout when we are in verbose mode?
> 
> Sounds good !

😅 

Bit of a chicken and egg. How can we know if we are in verbose mode if we are still looking for a configuration to load...

I would be okay with not doing anything. I think the annoyance of warning about this if you already know about the issue outweighs the issue of silently ignoring.

**Pull request merged**
