### PR TITLE
Add some flags showing information to the CI pytest runs

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

This should help narrow down issues with the CI if they keep popping up.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
👌

**Comment by Pierre-Sassoulas** [comment]
Look like the verbose option is not displayed when the timeout happens : https://github.com/PyCQA/pylint/runs/5344145948?check_suite_focus=true as the operation is canceled. We have strange spike on the coverage job sometime, might be due to coveralls and not github actions ? Should we separate 3.8 and increase the timeout ? Just increase the timeout ?

**Comment by DanielNoord** [comment]
It is showing, see L19 of the action. We're just failing on the second test.
I have done some testing again myself and there seem to be issue with all test that use 2 or more cores on Linux. I'm really starting to wonder if something is up with the runners or if Python jobs can only use 1 core.. The support for GitHub Actions is a bit dispersed though, so I haven't found the right place to ask questions/support about this..

**Comment by Pierre-Sassoulas** [comment]
> It is showing, see L19 of the action.

Ho wow, you're right, it's stuck very early !

**Pull request merged**
