### PR TITLE
Fix following "Bump astroid from 2.12.4 to 2.12.5"

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
Reverts PyCQA/pylint#7377

### CODE REVIEW

**Comment by DanielNoord** [comment]
Why don't we simply fix the issue instead of reverting it? We only need to bump the upper bound in `requirements`, there is no need to bump anything else.

**Comment by Pierre-Sassoulas** [comment]
> there is no need to bump anything else.

I think we still need to bump de cache, right ? It's not really a revert I've opened the issue with a revert (for speed), but I'm intending to keep the astroid upgrade, and fix the issue with the documentation that was highlighted by the MR that broke main (ie. implement this comment: https://github.com/PyCQA/pylint/pull/7377#issuecomment-1230332382).

**Comment by DanielNoord** [comment]
> > there is no need to bump anything else.
> 
> I think we still need to bump de cache, right ?

Don't think so. If the venv creation failed it will auto create a new venv.

> It's not really a revert I've opened the issue with a revert (for speed), but I'm intending to keep the astroid upgrade

The `astroid` upgrade is not correct though. It doesn't download the correct version.

> and fix the issue with the documentation that was highlighted by the MR that broke main (ie. implement this comment: [#7377 (comment)](https://github.com/PyCQA/pylint/pull/7377#issuecomment-1230332382)).

👍

**Comment by Pierre-Sassoulas** [comment]
Don't we want this version: https://pypi.org/project/astroid/2.12.5/ ? I suppose the primer are expected to fail, right ? 
The error we get on main is:
```
pip._vendor.pkg_resources.ContextualVersionConflict: (astroid 2.12.4 (/home/runner/work/pylint
/pylint/venv/lib/python3.10/site-packages), Requirement.parse('astroid<=2.14.0-dev0,>=2.12.5'), {'pylint'})
```
Which makes me think that astroid 2.12.4 is pre-installed in the cache instead ?

**Review by DanielNoord — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
Yeah sorry I don't have a lot of time right now, still planning on fixing the issue.

**Comment by DanielNoord** [comment]
No worries, just thought I would unblock this.

Oh and sorry, I completely missed the `blocked` label. Should have pinged you before merging.

**Comment by Pierre-Sassoulas** [comment]
No worries simply fixing main makes a lot more sense !

**Pull request merged**
