### PR TITLE
Use MsgDef dataclass

### PR DESCRIPTION
**Pull request by cdce8p**
## Description
Followup to https://github.com/PyCQA/pylint/pull/4517#discussion_r641971927
This MR adds the `MsgDef` dataclass: https://github.com/PyCQA/pylint/commit/88965c2cb657183729d89dba47d36e086e86795e. The main advantage are that error validation will happen at class instantiation and that keyword arguments make reading message definitions a bit easier. The current change is minor and fully backwards compatible.

We could also think about a bigger refactoring possibly with a breaking change. The best example would be the `MSGS` dict. That could change to a `Tuple[MsgDef, ...]` if we add the `msgid` to `MsgDef`.

/CC: @Pierre-Sassoulas 

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
I think we should not create a new message class without removing at least one between `_MsgBase` or `Message` (https://github.com/PyCQA/pylint/blob/master/pylint/message/message.py#L9). As it is a breaking change for plugins, we should aim to make the existing classes coherent and optimize them if possible. the `msg_id` attribute for example is `msgid` almost everywhere else. We should'nt break plugins without at least a significant simplification of the `pylint.messages` package (I know this part well, I refactored a big part of it in order to permit to have multiple message with the same old name.).

**Comment by cdce8p** [comment]
> We shouldn't break plugins without at least a significant simplification of the pylint.messages package

Just to clarify, in its current form the change is fully optional and thus backwards compatible.

> I know this part well, I refactored a big part of it in order to permit to have multiple message with the same old name.

If you like, you can take the lead on that one. As you said, you probably know that part way better than I do. I could help refactoring the existing messages. Or we could also defer it for now..?

**Comment by Pierre-Sassoulas** [comment]
I did not understand that it was backward compatible. Maybe we should keep one of the checker with the old dict so we have a regression check ?

> Or we could also defer it

Yeap, probably a nice refactor to do after the performance issue is sorted out and 2.9 is released. What is to gain if we merge this now without refactoring ?

**Comment by cdce8p** [comment]
> > Or we could also defer it
> 
> Yeap, probably a nice refactor to do after the performance issue is sorted out and 2.9 is released. What is to gain if we merge this now without refactoring ?

Not much. We would get rid of the `pylint: disable` comments but that's basically it.

**Pull request closed without merging**
