### PR TITLE
Can choose decorators that mutate a function's signature

### LINKED ISSUE #259: Decorators confuse E1120 analysis
Originally reported by: **the mulhern (BitBucket: [the_mulhern](http://bitbucket.org/the_mulhern))**

---

Here's the example:

```
#!python


def decorator(f):

    def new_func(junk=None):
        f(2, junk=junk)

    return new_func

@decorator
def junk1(param, junk=None):
    print("%s" % junk)

def main():
    junk1(junk=2)
```

The analysis reports
"No value passed for parameter 'param' in function call (no-value-for-parameter)"
This is incorrect, since the actual function being called is the new_func manufactured
by the decorator, and that function does not require the parameter 'param'.

You can work around this by giving param a default value, (which will never be used).

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/259

### PR DESCRIPTION
**Pull request by AWhetter**
## Description
This adds a new option `function_mutators` that allows `too-many-function-args`, `unexpected-keyword-arg`, and `no-value-for-parameter` to not get raised for functions that are decorated with a decorator mentioned in `function_mutators`.

I figured it would be too difficult to try and infer what a decorator was doing so this seemed like the best solution, even though it means that there will be cases where a function is called with incorrect arguments will be missed by pylint when the function is decorated with a mutator decorator.

## Type of Changes
|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
| ✓  | :sparkles: New feature |
|    | :hammer: Refactoring  |
|    | :scroll: Docs |

## Related Issue

Close #259

### CODE REVIEW

**Comment by PCManticore** [comment]
Not yet @schrockn but the new release would happen very soon.

**Comment by iddan** [comment]
Any update regarding the release?

**Comment by muneebabbas93** [comment]
@PCManticore This very simple change would allow us to remove a bunch of `# pylint: disable=no-value-for-parameter`. Any chance of this getting a release in the 1.9 branch?  :)

Serves us right for still using python 2 though :(

**Comment by beasteers** [comment]
this is great! Is there a way to define `function_mutators` using inline comments (e.g. `# pylint: function_mutator`)? It would be nice if we could avoid having to maintain a separate list that I'm inevitably going to forget to update.

**Comment by hippo91** [comment]
@beasteers it don't seem so. The only way seems to use the rcfile.

**Pull request merged**
