### PR TITLE
Move ``HUMAN_READABLE_TYPES`` to ``constants``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

I'm going to go through the effort of picking some of the changes for #5311 into separate PRs.
I don't see myself being able to keep my focus for 2000+ lines 😄 

I'm co-authoring @CarliJoy in all of them as they have done all the work here!

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
There will be a lot to rebase, but this will surely help. I don't know if it's a reasonable use of our time though. The main issue with the other MR is also that a lot of new lines of code were added un two new checkers are once.

**Comment by DanielNoord** [comment]
I'm working on splitting out the move of `non-ascii-name` next, that can definetly be done in a separate PR. I'll see what I can do afterwards. Doing this PRs also helps with actually checking the changes.

**Comment by Pierre-Sassoulas** [comment]
Yes we can definitely do a MR for each new checker.

**Comment by DanielNoord** [comment]
Little bit more annoying than I thought since you can't change the "owner" of a PR. So I can't easily ask questions about things to @CarliJoy. Guess I'll keep working in that PR then.

**Comment by Pierre-Sassoulas** [comment]
If I were you I would let it go and review one Checker after the other now that the two files are separated. It sure is a pain to review but so is splitting it up then still have to review 😄

**Pull request merged**
