### PR TITLE
Per dir config

### PR DESCRIPTION
**Pull request by hippo91**
Partial work on reintegrating man page generation. #1887.

@AWhetter the work is not finish, but i wanted to have your opinion before finishing it.
I can't reproduce exactly the historical man page because i'm unable to retrieve sections``MASTER``,  ``EXCEPTIONS``, ``LOGGING`` ... Instead most of the options are now under OPTIONAL ARGUMENTS section. Are you ok with this?
Moreover i think there are problems with some options like ``--lists-msgs`` which is now waiting for an argument. 
The CI is failing but i don't suppose it's due to this work.

### CODE REVIEW

**Comment by AWhetter** [comment]
Sorry it's taken me so long to look at this.
The branch is already failing the tests so don't worry about those for now. There's a task open to get them fixed.
I'm not sure why so many arguments are under OPTIONAL ARGUMENTS. We should fix that, but I'm happy for us to do it in another pull request.
I didn't know about the `--list-msgs` problem. I've created a task for this: https://github.com/PyCQA/pylint/projects/1#card-9018104

**Comment by PCManticore** [comment]
Hey @hippo91 and @AWhetter what's the status of this PR?

**Comment by hippo91** [comment]
@PCManticore i'm really sorry but i had not enough time to work on this since i made this PR. 
There is still a lot of work to do but i'm unable to handle this at this moment.

**Comment by PCManticore** [comment]
No worries @hippo91 I was just being curious where things were at! Don't worry, feel free to pick this up whenever you have time!

**Comment by pinealan** [comment]
Apologies in advance to hijack this PR for a second. I was working on a branch to integrate `pyproject.toml` and possibly `setup.cfg` #617. As I went down the rabbit hole it became obvious that the whole config system had to be refactored to enable that. I had a bit of work done on that but luckily I just caught this thread since it would definitely be duplicate work.

Now the question is the status of this PR. If @AWhetter and @hippo91 are still busy at the moment I don't mind helping out and try to first finish up this PR before working on a new PR for those new config files.

**Comment by AWhetter** [comment]
Hi @pinealan. If you want to take over this PR, please do! Unfortunately I have not found much time to finish it myself this past few months. 
This PR alone doesn't refactor the configuration system. It's part of a bigger project (https://github.com/PyCQA/pylint/projects/1) for #618. That project page lists what work is left to do. It's also been a while since the branch has been worked on. It needs rebasing on top of master and formatting with black also, but feel free to work off of the branch in it's current state if you prefer.

**Comment by hippo91** [comment]
@pinealan thank you for your message.
I'm in the same situation as @AWhetter . If you want to work on this PR you'are welcome and i'll be pleased to help you as much as i can!

**Comment by AWhetter** [comment]
@pinealan If you still wanted to continue the work on this, the branch is now rebased on top of master.

@hippo91 I'm going to close this PR because it's very out of date with the current branch. But feel free to pick this up again if you want to.

**Pull request closed without merging**
