### PR TITLE
Fix false-negative of unused-variable on catched exceptions

### LINKED ISSUE #4391: False negative ``unused-variable`` for catched exception when used in the inner context
### Steps to reproduce

Given a file `a.py`:
```python
#pylint: disable=missing-docstring

def function():
    unused = 1  # [unused-variable]
    try:
        1 / 0
    except ZeroDivisionError as error:  # [unused-variable]
        try:
            1 / 0
        except ZeroDivisionError as error:
            raise Exception("") from error

```

### Current behavior

```
************* Module a
a.py:4:4: W0612: Unused variable 'unused' (unused-variable)

------------------------------------------------------------------
Your code has been rated at 8.89/10 (previous run: 8.89/10, +0.00)
```

### Expected behavior

```
************* Module a
a.py:4:4: W0612: Unused variable 'unused' (unused-variable)
a.py:8:30: W0612: Unused variable 'error' (unused-variable)
```

### pylint --version output

```
pylint 2.7.4
astroid 2.5.3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
```

### PR DESCRIPTION
**Pull request by ksaketou**
## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description
This pull request fixes a false-negative of the `unused-variable` error message caused in case of catched exception inside another `except` block. It adds a new function for checking the content of the except block for `raise` and `print` statements and also other try/except blocks.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
## Related Issue

Closes #4391

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Hi @ksaketou, thank you for the merge request. I had a look and the tests are very nice. I feel that the fix although it works, is too specific to the problem and I feel the performance and clarity of the code would be impacted. I don't know what would be the best way to fix this (It's possible to check how flake8 does it because it detect this error), but probably by doing something more generic like checking that the variable was not redefined before being used in all contexts, and not only when there is two imbricated try except. We could merge the test alone and add a TODO where pylint do not work properly yet so we can reuse them later if you want.

**Comment by ksaketou** [comment]
I agree that the code is more specific than it should be, but I think that this case is pretty specific as well so I don't know how I could implement it in a more general way. I thought that since the bug only existed in the try/except cases, that that's what I had to work on. I will check flake8 and try to fix the bug. So, I shouldn't focus only on the try/except cases? Any suggestions are welcome :smile:

Of course we can merge just the tests for now until I figure this out :)

**Comment by ksaketou** [comment]
I'm working on a new branch for the addition of the tests but when I run `python -m pytest`, I see tests for other error messages like `logging-not-lazy`, `invalid-length-returned` etc failing. Maybe some changes happened on these messages?

**Comment by Pierre-Sassoulas** [comment]
Can you try to upgrade your dependencies in the virtualenv ? I think you need to have astroid 2.5.7 now.

**Comment by Pierre-Sassoulas** [comment]
Hey @ksaketou there was a nice comment on this topic [here](https://github.com/PyCQA/pylint/pull/4791#discussion_r681929788). I seriously underestimated the difficulty of the task at hand, this is clearly not a friendly issue for new contributor, so I apologize for that. Knowing that do you think we should close this merge request ?

**Comment by ksaketou** [comment]
Hello @Pierre-Sassoulas , it's okay, indeed I had difficulty finding a solution that works and is also elegant. I think we can close this PR.

**Comment by Pierre-Sassoulas** [comment]
Understood. Sorry again for the bad experience.

**Pull request closed without merging**
