### PR TITLE
Some formatting of docstrings with ``pydocstringformatter``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

@Pierre-Sassoulas This is only a partial run, but should make updating to a future release much easier with a smaller diff 😄

### CODE REVIEW

**Comment by DanielNoord** [comment]
> Look like it's cutting line a little too short, we have 88 char lines with black, docstring should be the same length imo.

Which lines are too short?

**Comment by Pierre-Sassoulas** [comment]
In
```
    """The LinesChunk object computes and stores the hash of some consecutive
    stripped lines of a lineset.
    """
```    
the first line is 78 char but if you had `` stripped`` it would be 87 chars

**Comment by DanielNoord** [comment]
Remove the wrapping commit. I'll investigate in `pydocstringformatter`. Probably something to do with taking `len()` and zero-indexing or something... 😓

**Comment by DanielNoord** [comment]
Found the issue: I subtract the quotes from the line-length whenever we have single line docstring, so
```python
def func():
    """A multi-line summary that can be on one line. Something that is just too longgg."""
```
Becomes
```python
# Since the ending quotes will be appended on the same line this
# exceeds the max length.
def func():
    """A multi-line summary that can be on one line. Something that is just too
    longgg.
    """
```

However, in the case you mentioned it should be re-added as the quotes will no longer be on the first line anyway.

**Review by Pierre-Sassoulas — APPROVED** [review]
👍

**Pull request merged**
