### PR TITLE
Add python 3.10 dev in the CI

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Description

In order to be ready when python 3.10 goes out. For python 3.9 we were a little late and we had to do everything almost at the time when it became the default python in the new debian. See #3959 

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |
| ✓  | :sparkles: New feature |

### CODE REVIEW

**Comment by cdce8p** [comment]
I looked at the errors today. Most of them are the result of postponed evaluation still being enabled in `3.10a7`. As this has been reverted, most issue should resolve itself with the release of `3.10b1` later today. See also: #4385

One issue that will require a fix is https://github.com/PyCQA/pylint/blob/ce55bce53d3a17390d3fb69afe5a3de55ebb83c8/tests/functional/m/member/member_checks_py37.py#L5
This should probably be changed to `collections.abc.Iterable`

**Comment by cdce8p** [comment]
FYI: The current Pytest version (`6.2.3`) doesn't work for `3.10.0b1`. See: https://github.com/pytest-dev/pytest/issues/8539
The issue is already fixed but not yet released.

**Comment by cdce8p** [comment]
@Pierre-Sassoulas Would you mind taking a look? I've pushed some changes directly to your branch. However, just because the tests pass now, doesn't mean that `pylint` supports `310`. Especially parsing a `match` statement doesn't work currently, see https://github.com/PyCQA/astroid/pull/986. I would therefore suggest **not** to add the classifier just yet.

**Comment by cdce8p** [comment]
Just noticed, should we add a changelog entry for it?

**Comment by cdce8p** [comment]
> Yes we definitely need more tests on python 3.10 code before advertising that we're 3.10 ready 😄 Maybe we could take it from here : https://docs.python.org/3.10/whatsnew/3.10.html ?

I agree. It might be more beneficial though to add them later and merge this one as it. Especially since they wouldn't work currently.

**Comment by Pierre-Sassoulas** [comment]
Just saw that there is no changes to the changelog, or classifiers, let's merge !

**Pull request merged**
