### PR TITLE
Revert "Do not append namespace packages to sys.path (#6405)"

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

This reverts commit 603be8408a5d2d98283f41cfd9a94998fd7cfd3c. See https://github.com/PyCQA/pylint/issues/6538#issuecomment-1120373164

Should we reopen https://github.com/PyCQA/pylint/issues/5226, and https://github.com/PyCQA/pylint/issues/2648 ?

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
I hope to write a regression test case. Maybe we should merge that before reverting this. I think in trying to distill a minimal example I simplified it too much 😓

**Comment by jacobtylerwalls** [comment]
> I think in trying to distill a minimal example I simplified it too much 😓

Turned out it was just that generic names like "test", "a", and "b" were ambiguous on my system. Using unique names helps to reproduce. I'll try to get a PR going with a test.

**Comment by jacobtylerwalls** [comment]
Er.... it was actually that the parent of the namespace directory needed to be on `sys.path`! See #6553 for the test.

**Comment by jacobtylerwalls** [comment]
> Should we reopen https://github.com/PyCQA/pylint/issues/5226, and https://github.com/PyCQA/pylint/issues/2648 ?

👍🏻 And add them to 2.15

**Review by jacobtylerwalls — APPROVED** [review]

**Review by DanielNoord — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
@DanielNoord should we merge #5235 then ? Permitting user to disable sys.path patching when it make sense could be a temporary solution ?

**Comment by DanielNoord** [comment]
> @DanielNoord should we merge #5235 then ? Permitting user to disable sys.path patching when it make sense could be a temporary solution ?

Like I said previously, I don't think so until we have fully investigated the issue. We would only end up having to support an option that does not mimic actual `Python` behaviour. Until we are sure we can't fix our handling of namespace packages we shouldn't do so I think.

**Pull request merged**
