### PR TITLE
Add a regression tests for https://github.com/PyCQA/astroid/pull/1207

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
| ✓   | :scroll: Docs          |

## Description

This should fail before we upgrade astroid following the merge of https://github.com/PyCQA/astroid/pull/1207

### CODE REVIEW

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas I would be okay with letting this go. If anything this should probably be tested in `astroid`. This seems to be such a niche case that we can add tests cases when somebody reports problems with this (we will then probably also get more input on what to actually test).

**Comment by Pierre-Sassoulas** [comment]
I'm reluctant to close as we merged in astroid with the implicit assumption that we were going to test in pylint as it would be easier to test in pylint. I totally lost the context of the original change at this point though.

**Comment by jacobtylerwalls** [comment]
I opened an alternative regression test that does fail before the astroid PR (and hopefully is meaningful!) in https://github.com/PyCQA/astroid/pull/1397.

> This does not fail like it should.

I think this was expected, here the author said "when you run the test build within such a no-filesystem environment."

**Comment by DanielNoord** [comment]
Superseded by https://github.com/PyCQA/astroid/pull/1397. Thanks a lot @jacobtylerwalls, this has been a very long open issue.

**Pull request closed without merging**
