### PR TITLE
Added various deprecated functions/methods for python 3.10, 3.7, 3.6 and 3.3

### PR DESCRIPTION
**Pull request by matusvalo**
## Steps

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description

Added various deprecated functions/methods for python 3.10, 3.7, 3.6 and 3.3.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|     | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
|     | :hammer: Refactoring   |
|     | :scroll: Docs          |

## Related Issue

Requires merging #4619.

### CODE REVIEW

**Review by cdce8p — APPROVED** [review]
Looks good overall. I couldn't find some of those, but I guess they are fine. If not we  will  probably know soon after the release ;)

**Review by Pierre-Sassoulas — APPROVED** [review]
I checked ``sqlite3.OptimizedUnicode`` (it's really deprecated), the other functions are merged based on trust 😄 Thank you @matusvalo 👍

**Comment by matusvalo** [comment]
All deprecations are collected based on What's new documentation of Python releases.

**Comment by matusvalo** [comment]
I did second review of PR and found several issues - they are handled in PR #4628.

In general the issues are not major and there is no need in quick releasing new pylint version - it can wait for next minor release of pylint.

**Pull request merged**
