### PR TITLE
Fix homepage link

### PR DESCRIPTION
**Pull request by hugovk**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

The "Homepage" link at https://pypi.org/project/pylint/ points to https://www.pylint.org/ which is down:

image

Instead, link to the docs page at https://pylint.pycqa.org/.

### CODE REVIEW

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Do you know something about this? I never asked but do you have any affiliation with `logilab`? I think the site was still maintained by them. Their own site seems to be up and running: https://www.logilab.fr.

**Review by Pierre-Sassoulas — APPROVED** [review]
> Do you know something about this?

No, I don't control this domain, I don't know who does.

> I never asked but do you have any affiliation with logilab?

No 😄 Apart from the fact that hippo91 and I are french like Logilab. PcManticore didn't either as far as I know.

> I think the site was still maintained by them. Their own site seems to be up and running.

I think we should rely on common open-source resources for everything at this point (Changing the link to readthedoc ✔️).

**Review by Pierre-Sassoulas — COMMENTED** [review]
Some cleanup of existing links

**Comment by Pierre-Sassoulas** [comment]
Thank you for your contribution @hugovk, and congratulation for becoming a pylint contributor :)

**Pull request merged**
