### PR TITLE
Fix line counting for missing-docstring check in combination with docstring-min-length

### PR DESCRIPTION
**Pull request by ttenhoeve-aa**
1) Add a function to get the last line number of node 
2) fix the line counting in the _check_docstring method

Perhaps it would be nicer to integrate the `get_node_last_lineno` function into astroid. Seems to me this should be the functionality of the `block_range` function of astroid, but that doesn't work in the same way and modifying it now may affect all code relying on the current behaviour.

### CODE REVIEW

**Comment by ttenhoeve-aa** [comment]
Thanks @rogalski. 
I am unaware of the workflow and etiquette here. Should I invite somebody for review? or can I just wait and will somebody take a look when they have time?

**Comment by PCManticore** [comment]
I don't understand what this patch is trying to achieve. What is the exact false positive you are encountering?

**Comment by ttenhoeve-aa** [comment]
@PCManticore It is about false negatives. Currently in a lot of cases pylint will not complain about functions that do not have any docstring, even if they are longer than docstring-min-length and pylint should complain.

For example the following function, which is clearly more than 3 lines long and does not have any docstring will trigger any error from pylint about missing docstring, if docstring-min-length is set to 3. 
```python
def func(tion):
    try:
        pass
    except:
        pass
```

Problem is that with the current code pylint only considers this function to be one statement long (the `try` statement), and  it considers the line-number of the start of the try as the last line in the function. This patch tries to fix this; although even with this change there might be some edge cases that are not detected correctly, since we only consider the line-number of the line that a statement starts at.

**Comment by ttenhoeve-aa** [comment]
@PCManticore please let me know if I need to provide more information or justification for this proposed change.

**Comment by PCManticore** [comment]
@ttenhoeve-aa Thank you for the explanations! It makes sense, although I would have hoped for something like this in astroid itself. But nonetheless, the patch looks good as is and thank you for it!

**Pull request merged**
