### PR TITLE
Update black to 21.4b0

### PR DESCRIPTION
**Pull request by cdce8p**
## Steps

- [ ] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [ ] If it's a new feature or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [ ] Write a good description on what the PR does.

## Description
Changelog: https://github.com/psf/black/blob/master/CHANGES.md#214b0

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
Right I was wondering about #4409 passing without changing anything but in fact this is not used anywhere in the CI !

**Comment by cdce8p** [comment]
> Right I was wondering about #4409 passing without changing anything but in fact this is not used anywhere in the CI !

Sorry, I'm not following here either. What is not used anywhere in the CI tests?

**Comment by Pierre-Sassoulas** [comment]
The value changed by the dependabot in `test_requirement_pre_commit.txt` (The CI's pre-commit test use the value in the pre-commit configuration)

**Comment by cdce8p** [comment]
> The value changed by the dependabot in `test_requirement_pre_commit.txt` (The CI's pre-commit test use the value in the pre-commit configuration)

You meant #4406 and not #4409, I understand now. Yeah unfortunately `dependabot` doesn't update the `pre-commit-config`

**Pull request merged**
