### PR TITLE
Remove bad continuation from the codebase

### LINKED ISSUE #289: False positive for "bad-continuation"
Originally reported by: **Steven Myint (BitBucket: [myint](http://bitbucket.org/myint), GitHub: @myint?)**

---

This valid style is incorrectly labeled as `bad-continuation`.

``` python
def test():
    if (
        True or
        False
    ):
        pass
```

```
C:  3, 0: Wrong hanging indentation before block.
        True or
        ^   | (bad-continuation)
C:  4, 0: Wrong hanging indentation before block.
        False
        ^   | (bad-continuation)
```

As described in #232, there are more false positives demonstrated in [`E12not.py`](https://github.com/jcrocholl/pep8/blob/master/testsuite/E12not.py).

---
- Bitbucket: https://bitbucket.org/logilab/pylint/issue/289

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Description

As discussed in #3512 other tools exist, and a lot of open issues are not getting fixed because those who want it are not taking the time to fix it (The first issue about it is old enough to enter primary school to learn to read).

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :hammer: Refactoring  |
| ✓  | :scroll: Docs |

## Related Issue

Close #289, #638, #747, #1148, #1179, #1943, #2301, #2304, #2944, #3565

### CODE REVIEW

**Comment by AWhetter** [comment]
If we're going down this road (and I've been leaning towards thinking we should) then I think we should consider all of the style checks together and I think we should consider whether this deserves a major version bump.

If we're saying that other tools are better at this then I think we can say the same for most of the style checks. Doing it this way would mean that we can be more clear that pylint's purpose is now as a "functional" linter as opposed to a style checker. At the very least, because we're now publicly saying that flake8/black should be run alongside pylint, I think we should get the documentation about running these tools together written up and included in the same release.

The reason I say that it maybe deserves a major version bump is because we're starting to think differently about what pylint does (style linter vs functional linter). Some people might still rely on pylint's style checking for whatever reason and doing a major version bump would mean that we can continue to provide backported updates to those users for a short time.

How do we feel about this?

**Comment by Pierre-Sassoulas** [comment]
What I understood from the discussion was that we removed only the very high effort one, which had a lot of false-positive and a lot of maintaining work to do. If a format check is low effort and have been working for years we don't remove it (even if other tools are doing formatting too).

**Comment by revolutionisme** [comment]
Which version of pylint is this merged to? Is it already released? I am on 2.5.3 and still getting bad-continuation error with black formatting!

**Comment by Pierre-Sassoulas** [comment]
@revolutionisme it was merged before 2.5.1 (2 may). Could you create an issue with an example of code that trigger it?

**Comment by silpheel** [comment]
@Pierre-Sassoulas 
```
> pylint --version
pylint 2.5.3
astroid 2.4.2
Python 3.6.11 (default, Jul 17 2020, 14:57:20)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.29)]
```

```
> cat badcont.py
def test(
    a, b
):
    print(a, b)
```

```
> pylint badcont.py
************* Module badcont
badcont.py:2:0: C0330: Wrong hanging indentation before block (add 4 spaces).
    a, b
    ^   | (bad-continuation)
badcont.py:1:0: C0114: Missing module docstring (missing-module-docstring)
badcont.py:1:0: C0116: Missing function or method docstring (missing-function-docstring)

---------------------------------------------------------------------
Your code has been rated at -5.00/10 
```

**Comment by john-bodley** [comment]
@Pierre-Sassoulas and @PCManticore somewhat related to `bad-continuation`, I was wondering whether the `line-too-long` check was also possibly redundant since other tools—like Black—handle formatting. There's also https://github.com/PyCQA/pylint/issues/4212 which means one needs to statements of the form, 

```python
...  # pylint: disable=line-too-long,useless-suppression
```

**Comment by Pierre-Sassoulas** [comment]
Hey, I don't think we're going to remove line-too-long any time soon as there isn't a lot of complexity to maintain it (as far as I know). Some people want to use only pylint so we'll remove only really hard to maintain check that are fixed by other linters so they can still do this. We do have to fix the issue you linked though.

**Pull request merged**
