### PR TITLE
Add documentation examples

### PR DESCRIPTION
**Pull request by DanielNoord**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

Refs https://github.com/PyCQA/pylint/issues/5953

Supersedes https://github.com/PyCQA/pylint/pull/8182

Let's not let this work go to waste, but also let's not keep reviewing a PR with 140 commits for 6 doc examples.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
Thank you for the cleanup @DanielNoord.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Are the examples good enough for you? It feels a bit `foo ... bar`

**Comment by ollie-iterators** [comment]
Why does the message about the error happening for the docstring errors like "docstring-first-line-empty" not go on the docstring, and instead go on the line above it?

**Comment by DanielNoord** [comment]
> Why does the message about the error happening for the docstring errors like "docstring-first-line-empty" not go on the docstring, and instead go on the line above it?

The message gets raised on the function definition, as that is the object with the incorrect docstring. This is a bit of a side effect of `pylint` relying heavily on the Abstract Syntax Tree in which a `FunctionDef` node is much easier to access than a docstring which doesn't really have its own node.

**Comment by Pierre-Sassoulas** [comment]
Yeah, well in a "normal" merge request I would have asked about it, but this one was already exhausting as is. I think we can deal with this later on (it's easy to grep foo and bar in the doc). Or we could change it but this would be almost redoing everything from zero...

**Comment by ollie-iterators** [comment]
> > Why does the message about the error happening for the docstring errors like "docstring-first-line-empty" not go on the docstring, and instead go on the line above it?
> 
> The message gets raised on the function definition, as that is the object with the incorrect docstring. This is a bit of a side effect of `pylint` relying heavily on the Abstract Syntax Tree in which a `FunctionDef` node is much easier to access than a docstring which doesn't really have its own node.

Ok, thanks for the explanation

**Pull request merged**
