### PR TITLE
Ignore path doc: double escape to add escape character in rst

### PR DESCRIPTION
**Pull request by tbennett0**
Adding another escape to small doc PR submitted in #7103, looks like the autoupgrade removed the escape.

CC @Pierre-Sassoulas

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
Thank you ! It took my waaaay longer than I'd like to admit to find the result in read the doc.

This fix the issue in the online documentation but it's very likely  that the test is also used on the help text of the command line tool. Could we add a test to check that the command line tool's help still make sense ?

**Comment by tbennett0** [comment]
Sure, I'll look into it 👍

**Review by DanielNoord — APPROVED** [review]
Let's just merge, seems like a good improvement. If somebody wants to fix the CLI they can provide a fix afterwards, online documentation is probably used way more often.
Even I forget we have a CLI tool for help messages sometimes.. 😅

**Review by Pierre-Sassoulas — APPROVED** [review]
Fair enough.

**Comment by tbennett0** [comment]
Ah. I apologize, I didn't get the chance to take this up. I'll take a deeper look soon.

**Comment by Pierre-Sassoulas** [comment]
Don't worry @tbennett0, Daniel is right I was nitpicking. Don't worry there's a lot of pylint issues to handle if you feel like it 😉

**Pull request merged**
