### PR TITLE
Run primer on ``3.7`` and ``3.10``

### PR DESCRIPTION
**Pull request by DanielNoord**
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description

I think it makes most sense to run the primer on the last and least supported versions. Running it on any other doesn't really add much I think.

Besides, running on `3.7` has the additional benefit of testing the old parser (<3.8).

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
The comment will just be for 3.10, though?

**Comment by DanielNoord** [comment]
> The comment will just be for 3.10, though?

Yeah. I didn't think the rare case where there is a difference between `3.7` and `3.10` in messages emitted would be worth the effort to try and merge output of different versions.
But by running on multiple versions we can (eventually) deprecate/remove the old primer as we now have almost feature-parity.

**Review by jacobtylerwalls — APPROVED** [review]
Super. I'd still like to let the current job on `main` finish first to see if the keras warning goes away. Then we should remove the old primer.

**Comment by DanielNoord** [comment]
> Super. I'd still like to let the current job on `main` finish first to see if the keras warning goes away. Then we should remove the old primer.

Well, the old primer has the benefit of splitting up in different batches. `home-assistant` has caught multiple fatal errors previously so it's a real shame that we can't add it here.
Unless we find a clean way to have multiple batches in the new primer I think it make sense to leave the `batch_one` workflow of `old primer` running.

**Comment by jacobtylerwalls** [comment]
A `--packages` argument to the run command?

**Comment by DanielNoord** [comment]
> A `--packages` argument to the run command?

Probably should do ``--packages-json=``? And then make `Primer.packages` be based on that or something.

Haven't looked at it yet. Might be tricky to download and compare artefacts from different jobs in the same workflow.

**Comment by DanielNoord** [comment]
Note that merging this will likely break all PRs until we get a new successful run as we need a `3.10` output for the commenter to work (and not the `3.8`).

**Pull request merged**
