### PR TITLE
Add continuous integration with read the doc

### LINKED ISSUE #3850: move doc build checks from travis to readthedocs PR checks
Currently builds are checked with tox/travis, but the readthedocs environment is different/more restrictive than travis.

It would be better to have readthedocs build and check the docs for PRs rather than travis: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

It's probably worth leaving the docs test in tox for local development

github readthedocs build status report animation

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature |
| ✓  | :scroll: Docs |

## Related Issue
Closes #3850

### CODE REVIEW

**Review by cdce8p — APPROVED** [review]
If CI is done by `readthedocs.org` now, this seems like a reasonable change 👍🏻

**Comment by cdce8p** [comment]
@Pierre-Sassoulas Btw, if you have admin rights for `pylint` now, you could remove `appveyor`.

**Comment by Pierre-Sassoulas** [comment]
Appveyor has another set of of right unfortunately :( ..

**Comment by cdce8p** [comment]
@Pierre-Sassoulas The readthedocs CI integration doesn't seems to run on push to the `master` branch.

**Pull request merged**
