### PR TITLE
Refactor of MessageStore for multiple old message

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
Work in progress of the refactor for #2036 

In order to see what still need to be done.

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Sorry this is super messy but starting by really changing MessageStore was not a reasonable way to do it (way too complex).  So I just changed line 888 in python/utils.py in order to return a list and now I'm trying to pass existing tests. I'm afraid there will be a lot of changes to do. For exemple somewhere we use get_message_definition to return a symbol. But we now need to return a list of symbol, so the refactor will spread elsewhere... Also for some strange reason I can't test in my setup, I get "AttributeError: 'Assign' object has no attribute 'type_annotation'" everywhere.

**Comment by Pierre-Sassoulas** [comment]
@PCManticore this is not ready for review yet, I'm using the travis to circumvent my local bug with the tests :)

**Comment by Pierre-Sassoulas** [comment]
@PCManticore, I have the following error locally but the same code does not have the problem on the Pylint Travis... It prevent me from using pbd to debug. Pushing to Travis everytime is not very efficient. Any idea of the reason I get that ?

```
  File "m:\pylint\.tox\pylint\lib\site-packages\pylint\checkers\variables.py", line 1380, in _store_type_annotation_names
    type_annotation = node.type_annotation
AttributeError: 'Assign' object has no attribute 'type_annotation'
```
I saw [this](https://github.com/PyCQA/pylint/issues/2142) post, is it a known current problem with cygwin/mingw ?

**Comment by PCManticore** [comment]
@Pierre-Sassoulas You need the latest astroid for getting read of that error, I'd suggest rebuilding the tox environment with `tox --recreate`, this should bring the latest astroid.

**Comment by PCManticore** [comment]
@Pierre-Sassoulas Going to review this once the dust settles for the 2.0 release, so most likely next week. Sorry for the delay!

**Comment by Pierre-Sassoulas** [comment]
Hi @PCManticore. 

Thanks to the national holidays the tests for this are now passing... I modified some tests, and I'm surprised there is so little changes. If I were you I would check with care what was changed before merging. At least what was changed in the tests. 

This is a first step towards being able to have multiple values for a message in MessageStore. Before we returned a message Definition. In this PR we always have a list of only one value, next step will be to actually change the MessageStore to have a list of multiple MessageDefinition for an old name. As I said this a big refactor and it's easier done with small incremental steps.

Slightly related my astroid was deprecated again. It's hard to see, especially when you're working on something that is supposed to break the tests.  It took me some time to think of testing that the master branch tests were still passing. Maybe you should add the "tox --recreate" advice in the doc ?

Good job on adding black and a pre-commit hook !

Regards,

**Comment by PCManticore** [comment]
Hey @Pierre-Sassoulas Great stuff, thank you coming back at this! I'll do a final review and merge this weekend so that could unblock you for your other PR.

**Comment by PCManticore** [comment]
@Pierre-Sassoulas There's something wrong with this PR, it has quite a lot of changes. :) I'd like to merge it this week, so if you have some time to revert the inadvertent changes, that would be amazing.

**Comment by Pierre-Sassoulas** [comment]
@PCManticore sorry, I pushed by mistakes the change I did for the next step, should be ok now.

**Comment by PCManticore** [comment]
@Pierre-Sassoulas Thank you for waiting! This is merged now, let me know if you need anything for #2036

**Comment by Pierre-Sassoulas** [comment]
@PCManticore thank you for merging this first step. As you said earlier there is a lot of change in my current branch. Should I try to make multiple PR or should I put everything in #2036 ? There is a break up of utils.py into a package for example, and a renaming of 'MessageDefinition' to 'Message'.

**Comment by PCManticore** [comment]
@Pierre-Sassoulas Separate PRs could be better, since we can merge those faster than a big chunk.

**Comment by Pierre-Sassoulas** [comment]
Sorry for the delay, I had a hard time separating the changes. Here's the first one, the refactor of utils.py : #2654

**Pull request merged**
