### PR TITLE
Upgrade astroid to 2.13.2

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
@nelfin look at the primer result, there's a bunch of false positives that were fixed by your implementation support for is None :)

**Review by DanielNoord — CHANGES_REQUESTED** [review]
See https://github.com/PyCQA/astroid/issues/1942

**Comment by jacobtylerwalls** [comment]
I tried to reproduce the psycopg error outside the primer and couldn't (but I was in a rush). I'm not certain the way the primer packages are packaged all together under a single directory is realistic--I remember opening an astroid issue about primer packages polluting each other. I'm still interested to try for a reproducer, but I don't know that I'll have time this weekend.

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Let's merge then and get some real world examples (if there are any) from the beta.

**Comment by Pierre-Sassoulas** [comment]
Let's release the beta in the wild and see how it fare then :D

**Review by DanielNoord — APPROVED** [review]

**Pull request merged**
