### PR TITLE
Print helpful error when toml decode fails

### PR DESCRIPTION
**Pull request by qlyoung**
## Steps

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [ ] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature or an important bug fix, add a What's New entry in `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

*No ChangeLog entry as I don't see anyone else in there, looks like it's just for features?*

## Description

If loading a TOML config file fails, print the issue with the TOML file rather than dumping stack.

Turns this:
```
qlyoung@nicobar ~> pylint ./frrbot.py
Traceback (most recent call last):
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/toml/decoder.py", line 910, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/pylint/__init__.py", line 19, in run_pylint
    from pylint.lint import Run as PylintRun
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/pylint/lint/__init__.py", line 76, in <module>
    from pylint.lint.pylinter import PyLinter
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 19, in <module>
    from pylint import checkers, config, exceptions, interfaces, reporters
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/pylint/checkers/__init__.py", line 48, in <module>
    from pylint.checkers.base_checker import BaseChecker, BaseTokenChecker
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/pylint/checkers/base_checker.py", line 21, in <module>
    from pylint.config import OptionsProviderMixIn
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/pylint/config/__init__.py", line 105, in <module>
    PYLINTRC = find_pylintrc()
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/pylint/config/__init__.py", line 98, in find_pylintrc
    for config_file in find_default_config_files():
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/pylint/config/find_default_config_files.py", line 33, in find_default_config_files
    if config_name.endswith(".toml") and not _toml_has_config(config_name):
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/pylint/config/find_default_config_files.py", line 12, in _toml_has_config
    content = toml.load(toml_handle)
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/toml/decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "/home/qlyoung/.cache/pypoetry/virtualenvs/frrbot-dxHzjlU3-py3.8/lib/python3.8/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 28 column 1 char 585)
```

Into this:
```
qlyoung@nicobar ~> pylint ./frrbot.py
Failed to load 'pyproject.toml': This float doesn't have a leading digit (line 28 column 1 char 585)
Failed to load 'pyproject.toml': This float doesn't have a leading digit (line 28 column 1 char 585)
************* Module frrbot

[ ... pylint continues as normal falling back on other configs ... ]
```

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :bug: Bug fix  |

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Nice MR, thank you for contributing to pylint !

I think the expected output is a FATAL message with an exit output 1. It should be done by adding a FATAL error message in the Pylinter class, maybe F0003 `pyproject-toml-parse-error`. It could be raised when calling `config.find_default_config_files()` in the constructor. Also having an automated test with a corrupted `pyproject.toml` would be nice :)

**Comment by qlyoung** [comment]
Roger that

**Comment by qlyoung** [comment]
> It should be done by adding a FATAL error message in the Pylinter class, maybe F0003 `pyproject-toml-parse-error`. It could be raised when calling `config.find_default_config_files()` in the constructor.

Looking at the code now I'm not sure I agree with this, if you look at the stack this crash is hit prior to constructing PyLinter. It's hit while importing the `config` module.

pylinter.py:

```python
from pylint import checkers, config, exceptions, interfaces, reporters
```

In the `__init__.py` for module `config`, global init for `PYLINTRC = find_pylintrc()` calls `find_default_config_files()`.

If you prefer I can catch the TOML exception generated during import, or if there's a preferred way to log a warning during program startup I'll do that. Or some other idea.

**Comment by Pierre-Sassoulas** [comment]
Yes this is a little awkward, the error happens before we enter the pylinter. The configuration might require a refactor to be done inside the Pylinter object instead of outside. Maybe we can also not refactor and delay the error to when we call `ind_default_config_files().` and exit "the right way" for pylint (this do feels wrong). I did not reverse engineer a lot of it, but know this part of the code is a mess. Let me know what you think :)

**Review by Pierre-Sassoulas — APPROVED** [review]
I opened an issue to make this better (#4204), but it could take a long time to do and I want to fix this crash in 2.7.3 so I'm going to merge as it is. Thanks a lot for becoming a pylint contributer :)

**Comment by qlyoung** [comment]
Makes sense, appreciate it

**Pull request merged**
