### PR TITLE
Add regression tests of instance attribute inference on builtins.object

### LINKED ISSUE #3595: Regression with not-callable
### Steps to reproduce
1. Run pylint 2.5.2 on https://github.com/dseomn/pepper-music-player/blob/d1920ec3b941b65fad630e8b067d35bde228be49/pepper_music_player/player/player_test.py.

### Current behavior
```
pepper_music_player/player/player_test.py:283:8: E1102: self._player.next is not callable (not-callable)
pepper_music_player/player/player_test.py:292:8: E1102: self._player.next is not callable (not-callable)
pepper_music_player/player/player_test.py:301:8: E1102: self._player.next is not callable (not-callable)
```

### Expected behavior
I don't see why those lines are not-callable. `self._player.next()` is [defined](https://github.com/dseomn/pepper-music-player/blob/d1920ec3b941b65fad630e8b067d35bde228be49/pepper_music_player/player/player.py#L470) as a regular method.

### pylint --version output
```
pylint 2.5.2
astroid 2.4.1
Python 3.8.3rc1 (default, Apr 30 2020, 07:33:30) 
[GCC 9.3.0]
```

### LINKED ISSUE #3970: not-callable: false positive due to conflit between "next" user-function and "collections.abc"
### Steps to reproduce

```
from collections.abc import Callable


class Class:
    def next(self):
        pass

    def __init__(self):
        self.next()
```

### Current behavior

```
self.next is not callable
```

These is no warning if I remove the line ``from collections.abc import Callable``

### Expected behavior
No warning message.

### pylint --version output

```
pylint 2.6.0
astroid 2.4.2
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
```

### LINKED ISSUE #4221: False positive E1102 when adding a non-callable attribute to object
### Steps to reproduce

```python
'test'.startswith('t')
o = object()
x = 42
if o is x:
    o.startswith = None
```

### Current behavior

```
$ pylint -E file.py
************* Module file
file.py:1:0: E1102: 'test'.startswith is not callable (not-callable)
```

### Expected behavior
No errors.

### pylint --version output

```
pylint 2.7.2
astroid 2.5.1
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]
```

Pylint probably reasons like this: `str` is a subclass of `object`; `object`'s attribute is assigned to non-callable; thus, `str`'s attribute by the same name should be non-callable. I can see the logic here, but the error is reported on the very first line, before the attribute has the chance to get re-assigned. 

By itself, the above example code is not very meaningful. I'm reporting it because this seems to be the underlying cause of https://github.com/PyCQA/pylint/issues/3970#issuecomment-794286592. Also, it might manifest itself in other, more practical scenarios than the example above.

### LINKED ISSUE #4232: False positive on E1102 (not-callable) for methods called prev or next
### Steps to reproduce

([failing CI job on non-minimal code](https://lab.louiz.org/mathieui/poezio/-/jobs/31905#L2400))
It took me a while to isolate a minimal use case, from my repeated testing:

* There is a special case, in *any object*, for ``prev()`` and ``next()``
* It is only the case if the ``typing`` module is imported

Given a file `test.py`:
```python
import typing

class MyClass:
    def __init__(self):
        pass

    def next(self):
        pass

    def prev(self):
        pass

    def toto(self):
        pass

    def placeholder(self):
        self.prev()
        self.next()
        self.toto()
```

### Current behavior

Result of `pylint -E test.py`:
```
************* Module test
test.py:17:8: E1102: self.prev is not callable (not-callable)
test.py:18:8: E1102: self.next is not callable (not-callable)

```

### Expected behavior

No error.

### pylint --version output

Result of `pylint --version` output:
```
pylint 2.8.0-dev1
astroid 2.6.0-dev1
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0]
```

(installed both pylint and astroid from git to check)

### PR DESCRIPTION
**Pull request by nelfin**
## Steps

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a ChangeLog entry describing what your PR does.
- [x] If it's a new feature or an important bug fix, add a What's New entry in
      `doc/whatsnew/<current release.rst>`.
- [x] Write a good description on what the PR does.

## Description

Regression tests for various behaviours fixed by PyCQA/astroid#946.

Ref #3595, #4221, #3970. Depends PyCQA/astroid#946.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Related Issue

Closes #3595
Closes #4221
Closes #3970
Closes #4232

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
👍

**Comment by nelfin** [comment]
(Now that PyCQA/astroid#946 has landed, these tests should pass on re-run)

**Comment by Pierre-Sassoulas** [comment]
It's possible that we need a new release of astroid first.

**Comment by cdce8p** [comment]
> It's possible that we need a new release of astroid first.

Yeah, although I would still wait a bit with that. For sure before the next `pylint` release.

**Comment by Pierre-Sassoulas** [comment]
This can be rebased on master to get astroid ``2.5.7``.

**Pull request merged**
