### PR TITLE
[crash] Fix crashes on python interpreter < 3.9

### LINKED ISSUE #8161: pylint 2.16 fails on python 3.8.16
### Bug description

pytlint fails itself on python 3.8.     
3.9 and above seem OK

packages/pylint/checkers/imports.py", line 179, in _make_tree_defs
    node[1] += files
TypeError: 'tuple' object does not support item assignment

### Configuration

```ini
github actions (or elsewhere)
python 3.8.16

Collecting pylint
  Downloading pylint-2.16.0-py3-none-any.whl (530 kB)
```

### Command used

```shell
pylint
```

### Pylint output

```shell
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/__init__.py", line 36, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/lint/run.py", line 214, in __init__
    score_value = linter.generate_reports()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 1149, in generate_reports
    sect = self.make_reports(self.stats, previous_stats)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/reporters/reports_handler_mix_in.py", line 76, in make_reports
    r_cb(report_sect, stats, old_stats)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/checkers/imports.py", line 981, in _report_external_dependencies
    dep_info = _make_tree_defs(self._external_dependencies_info().items())
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pylint/checkers/imports.py", line 179, in _make_tree_defs
    node[1] += files
TypeError: 'tuple' object does not support item assignment
```

### Expected behavior

Not to fail ...

### Pylint version

```shell
pylint 2.16.0
```

### OS / Environment

ubuntu-latest on github actions

but also MacOS 13.2 etc

### Additional dependencies

N/A

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #8161 @MarcSchmitzer we can add you as co-author if you want (need your commit email) :)

### CODE REVIEW

**Comment by MarcSchmitzer** [comment]
> @MarcSchmitzer we can add you as co-author if you want (need your commit email) :)

That would be cool. Commit email would be marc@solute.de

**Comment by Pierre-Sassoulas** [comment]
Thank you for your help and congratulations on becoming a pylint contributor @MarcSchmitzer !

**Comment by Pierre-Sassoulas** [comment]
This part was not tested, it explains the crash. Should we blindly fix it or do you have a possible test in mind @DanielNoord ?

**Comment by DanielNoord** [comment]
Let's blindly fix. Can't be worse than current situation. I know this was pretty poorly tested code in general and the original fix is only because I made the typing stricter, which was already an improvement over previous state.

**Pull request merged**
